Rewrite countPoolCandidates api query with custom methods
GCTC-NTGC/gc-digital-talent pull request #1005
Opened 2021-11-01 16:47 UTC by tristan-orourke

Resolves #1002

2021-11-01 19:35 UTC, mnigh requested changes
Nice work! A few small suggestions to address and then ready to be approved.

2021-11-01 19:35 UTC, mnigh commented on api/graphql/schema.graphql
> +    hasDiploma: Boolean @where(key:  "has_diploma")
```suggestion
    hasDiploma: Boolean @where(key: "has_diploma")
```

2021-11-01 21:29 UTC, tristan-orourke commented
Note to self: make sure that false values for the booleans don't exclude people from the search.

2021-11-01 22:15 UTC, tristan-orourke commented
@mnigh I accepted your suggestions but also made a new commit that I forgot the first time

2021-11-02 13:23 UTC, mnigh approved these changes
👍

2021-11-02 13:23 UTC, merged