[Debt] Removes `OperationalRequirementV1`
GCTC-NTGC/gc-digital-talent pull request #10386
Opened 2024-05-15 13:49 UTC by mnigh

🤖 Resolves #9917.

## 👋 Introduction

This PR removes `OperationalRequirementV1` and associated code. It also renames `OperationalRequirementV2` to `OperationalRequirements` since there is no longer a reason to distinguish versions of the variable name.

## 🕵️ Details

It also adds a migration to remove the no longer used `OVERTIME_SCHEDULED` and `OVERTIME_SHORT_NOTICE` values from `pools.operation_requirements` and `users.accepted_operational_requirements` fields if they exist.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

### `users` SQL query
```sql
SELECT accepted_operational_requirements FROM users WHERE accepted_operational_requirements @> '"OVERTIME_SHORT_NOTICE"' OR accepted_operational_requirements @> '"OVERTIME_SCHEDULED"'
```

### `pools` SQL query
```sql
SELECT operational_requirements FROM pools WHERE operational_requirements @> '"OVERTIME_SHORT_NOTICE"' OR operational_requirements @> '"OVERTIME_SCHEDULED"'
```

1. `pnpm build`
2. Add different combinations of `OVERTIME_SCHEDULED` and `OVERTIME_SHORT_NOTICE` to the `pools.operation_requirements` and `users.accepted_operational_requirements` fields
3. Run `users` SQL query and `pools` SQL query to ensure values exist in each table
4. Run migration `make migrate`
5. Run `users` SQL query and `pools` SQL query to ensure no values exist in either table
6. Ensure other values in `pools.operation_requirements` and `users.accepted_operational_requirements` remain the same

2024-05-15 16:39 UTC, petertgiles requested changes
Nice to finally get this cleaned up!  Everyone looks great, except for one hitch...

2024-05-15 16:39 UTC, petertgiles commented on api/database/migrations/2024_05_14_194656_remove_operational_requirements_overtime_short_notice_overtime_scheduled.php
This migration is great for updating the database records but unfortunately they'll still be in profile snapshots which totally crash the app.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/e6a4873b-ab00-47e6-bd50-6045cc0aa6a1)

I don't think we want to update any snapshots - that kind of defeats the point of them.  I think in the past we talked about putting an error boundary around the component so that the worst-case scenario is that the application simply doesn't render but the app stays up.

The other thought that comes to me (but not discussed with the team) is that `getOrThrowError` in localizedConstants is pretty extreme.  It would probably be safer to just render the enum name (and log an error) if a description is not found and not take down the entire app.

2024-05-16 13:46 UTC, mnigh commented on api/database/migrations/2024_05_14_194656_remove_operational_requirements_overtime_short_notice_overtime_scheduled.php
@petertgiles should I block this on https://github.com/GCTC-NTGC/gc-digital-talent/issues/10395?

2024-05-16 14:11 UTC, petertgiles commented on api/database/migrations/2024_05_14_194656_remove_operational_requirements_overtime_short_notice_overtime_scheduled.php
Yeah, please.  I don't think there is any more dev work to be done on this branch though.  Good-to-go once the app error handling is improved.

2024-05-17 14:42 UTC, petertgiles commented on api/database/migrations/2024_05_14_194656_remove_operational_requirements_overtime_short_notice_overtime_scheduled.php
I just tested after the merge - looks good!

2024-05-17 14:42 UTC, petertgiles approved these changes

2024-05-17 15:05 UTC, merged