[Feature] Claim verification sorting update
GCTC-NTGC/gc-digital-talent pull request #10629
Opened 2024-06-10 23:28 UTC by vd1992

🤖 Resolves #10419

## 👋 Introduction

Has pool candidate queries or rendering take into account claim verification for purposes of sorting. 

## 🕵️ Details

Sorting for tab "Screening and assessment" was straightforward as it is sorted in the front end. 

Sorting for the table of candidates was a bit more complicated. Elected to introduce a sorting scope that supercedes other sorting scopes/actions when activated. It then executes a sorting operation. 

As well, there is the complication of also needing to account for citizenship as it is a part of "category". 

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. ...
2. ...

## 📸 Screenshot

Add a screenshot (if possible).

2024-06-10 23:31 UTC, vd1992 commented on apps/web/src/components/AssessmentStepTracker/utils.ts
>  };
Pulls the type from the graphql file so avoids being a circular reference. Enables better type safety with minimal refactor.

2024-06-10 23:35 UTC, vd1992 commented on apps/web/src/components/PoolCandidatesTable/helpers.tsx
Have sorting done in multiple functions at once feels messy so I wrote the new scope so that it is standalone, thus `getSortOrder` and `getClaimVerificationSort` do not both have effect. Followed in the steps of `getPoolNameSort`

2024-06-12 14:54 UTC, petertgiles requested changes
Looking good!  Just a few questions first.

2024-06-12 14:54 UTC, petertgiles commented on apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
Isn't the veteran an priority supposed to sort, by default, before name?
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/434b2ba1-a433-4f5b-944e-4ba122c888db)

2024-06-12 16:53 UTC, vd1992 commented on apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
No, not anymore. 
As of https://github.com/GCTC-NTGC/gc-digital-talent/issues/9224

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/bbf22704-7564-4ad3-8c18-a91e822f362c)

2024-06-12 17:14 UTC, vd1992 commented on api/app/Models/PoolCandidate.php
> +    public function scopeOrderByClaimVerification(Builder $query, ?string $sortOrder)
I operated under the assumption of preserving the bookmark sorting. 

I felt sorting should be in a single place, and is a single responsibility. Splitting sorting into different functions acting at the same time feels like not a good thing to me, hard to keep track of what is being tacked onto query builder and ensuring correct order of operation?

2024-06-13 12:38 UTC, petertgiles commented on api/app/Models/PoolCandidate.php
> +    public function scopeOrderByClaimVerification(Builder $query, ?string $sortOrder)
OK, just trying to understand - so is it that the bookmark should always be used for a sort?  Why isn't it in `scopeOrderByPoolName`?  Maybe that sort should be in a global scope?

2024-06-13 13:02 UTC, petertgiles requested changes
Nice, this is working well.  I have a few small suggestions but I think it's almost ready to merge.

2024-06-13 15:34 UTC, vd1992 commented on api/app/Models/PoolCandidate.php
> +    public function scopeOrderByClaimVerification(Builder $query, ?string $sortOrder)
`sortOrderByPoolName` never runs with bookmarks as far as I can tell?
Bookmarks don't appear on the all pool candidates table

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/44a4b496-c64b-41fb-a100-6386483125af)

And process name and sorting only appears on the all candidates table

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/08e18d27-9989-4db5-ba0a-86ecb65b3550)

2024-06-13 16:18 UTC, vd1992 commented on api/app/Models/PoolCandidate.php
> +        if ($sortOrder && $sortOrder == 'DESC') {
Hehe, I was wondering about doing that but wasn't sure if it was a good thing to do
Added/refactored in https://github.com/GCTC-NTGC/gc-digital-talent/pull/10629/commits/91cec9e72ccdee4dd22d08a5aa9f07946e82c0a3

2024-06-13 16:18 UTC, vd1992 commented on api/app/Models/PoolCandidate.php
> +                    foreach ($priorityWeights as $index => $priorityWeight) {
Done in https://github.com/GCTC-NTGC/gc-digital-talent/pull/10629/commits/91cec9e72ccdee4dd22d08a5aa9f07946e82c0a3

2024-06-13 17:01 UTC, petertgiles commented on api/app/Models/PoolCandidate.php
> +    public function scopeOrderByClaimVerification(Builder $query, ?string $sortOrder)
Yeesh, I'm still not sure I fully understand this.  It sounds like you've gone a lot deeper than me into this though.

2024-06-13 17:01 UTC, petertgiles approved these changes

2024-06-13 17:47 UTC, merged