[Feature] Add process number to tables
GCTC-NTGC/gc-digital-talent pull request #10763
Opened 2024-06-21 19:13 UTC by yonikid15

🤖 Resolves 10695

## 👋 Introduction

- Adds process number after pool name on the view candidate page - Other processes section.
- Adds process number after pool name on Candidate search page.
- The process number should be filterable on Candidate search table.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Login as `admin@test.com`
2. Go to Candidate search page and ensure process number is there and is filterable.
3. View a candidate in a pool and open Other processes accordion to reveal table. Ensure the table has the process number after name of pool.

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/22059495/f16886ee-eae4-4486-8b2c-756960297769)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/22059495/6512642b-77a2-4f69-9ef8-4997147f14cb)

2024-06-24 18:03 UTC, vd1992 commented
Little confused here, which is it supposed to be?

The issue screenshot marking where to place suggests combining it with the pool name as you have done

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/b50b8fde-cadb-4292-90f2-e72334ec0dce)

But the acceptance criteria says separate column

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/252579b7-8f4f-499a-818f-d25e92516db9)

2024-06-26 16:27 UTC, brindasasi commented
> Little confused here, which is it supposed to be?
> 
> The issue screenshot marking where to place suggests combining it with the pool name as you have done
> 
> ![image](https://private-user-images.githubusercontent.com/40485260/342444953-b50b8fde-cadb-4292-90f2-e72334ec0dce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MTk0OTcsIm5iZiI6MTcxOTQxOTE5NywicGF0aCI6Ii80MDQ4NTI2MC8zNDI0NDQ5NTMtYjUwYjhmZGUtY2FkYi00MjkyLTkwZjItZTcyMzM0ZWMwZGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDE2MjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MDc0N2Y3YWYzMWE4OTkxODBlYzgyZDc3NGRiYzYzMDY3OWFhODgyZWFlN2YyOTUxZDY5YTc0M2VlYTRjZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-JlguX475IWcvoi0OF-ucKcDeyS8Mwa1gQFfoVgxCNo)
> 
> But the acceptance criteria says separate column
> 
> ![image](https://private-user-images.githubusercontent.com/40485260/342445100-252579b7-8f4f-499a-818f-d25e92516db9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MTk0OTcsIm5iZiI6MTcxOTQxOTE5NywicGF0aCI6Ii80MDQ4NTI2MC8zNDI0NDUxMDAtMjUyNTc5YjctOGY0Zi00OTlhLTgxOGYtZDI1ZTkyNTE2ZGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDE2MjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1YzcxYjU5MzhkMzFkNmQ0MTQwNDkyZGM1YjZhMTFkMzJhZDFkMTc3NGFkNGI1NGEwOWNiZmRjZTQyODdiNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Xl0cYDirjULe21ZRIE-xzbksaM-K732pcrExAPyBCo)

This is a separate column

2024-06-26 21:00 UTC, yonikid15 commented
@brindasasi Gray said it's supposed to be a separate column. Should have it finished tomorrow for another review.

2024-06-27 14:51 UTC, petertgiles submitted a review, later dismissed
Nice!

2024-06-27 23:06 UTC, vd1992 requested changes
Took a look
One insignificant typo, one question, and one thing to definitely check on

2024-06-27 23:06 UTC, vd1992 commented on apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
@Jerryescandon 
The candidates table for a specific pool does not list the process name in each row, should the process number also be hidden here?

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/f3759083-f8b6-428d-b33e-741f714fcfa6)

2024-06-28 13:32 UTC, yonikid15 commented
@vd1992 @brindasasi @petertgiles Ready for a review now :laughing: whoever wants to jump on it first

2024-06-28 14:17 UTC, yonikid15 commented on apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
Nice catch, added by [dd8fe66](https://github.com/GCTC-NTGC/gc-digital-talent/pull/10763/commits/dd8fe661c4039f6748661e15f889d802430dbae2)

2024-06-28 14:17 UTC, yonikid15 commented on apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
Shouldn't be on this page nice catch! I missed the array :laughing: Fixed by [3a1d1d2](https://github.com/GCTC-NTGC/gc-digital-talent/pull/10763/commits/3a1d1d2947d5b42f3c096b1b79dbdba656fd138e)

2024-06-28 14:18 UTC, yonikid15 commented on api/app/Models/PoolCandidate.php
> +        // Early return if no publishing groups were supplied
Nice catch fixed by [2f021a0](https://github.com/GCTC-NTGC/gc-digital-talent/pull/10763/commits/2f021a07110f503e1fa01de113fc82b01b811146)

2024-06-28 16:37 UTC, vd1992 approved these changes
Nice, looks great!

2024-06-28 17:39 UTC, merged