[Bug] Filtering for archived pools fix
GCTC-NTGC/gc-digital-talent pull request #10970
Opened 2024-07-11 22:36 UTC by vd1992

🤖 Resolves #10865

## 👋 Introduction

Enable filtering for archived pools to work per intent. Filtered out by default, but returned if wanted

## 🕵️ Details

Just kicking the scope off the query as a blanket application and into the fields scope functions.
Permissions was decided to not be a problem for archived pools

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Navigate to pools table and also ensure you have a pool archived if not seeded
2. Default view returns all but archived pools
3. Play with the filters in the dialog, trying different combinations and check results
4. Ensure you can view archived pools when filtering for them

2024-07-11 22:42 UTC, vd1992 commented on api/graphql/schema.graphql
> +  language: LocalizedPoolLanguage @rename(attribute: "advertisement_language")
Format on save

2024-07-11 22:44 UTC, vd1992 commented on api/graphql/schema.graphql
>    processNumber: String @scope
If the field is not present, the scope is not run. Given the scope always needs to be used, even if just to apply the archived filtering, a default must exist

2024-07-12 12:17 UTC, esizer requested changes
Nice! Seems to do exactly what we want :+1: 

Can you also write a tests for this? I think three should assertions should it :thinking: 

- Create 2 pools (one archived, one not) 
   - Assert archived filtered by default
   - Assert passing in the non-archived pool returns only archived
   - Assert passing in an unrelated status returns no results

2024-07-12 17:14 UTC, vd1992 commented
> Nice! Seems to do exactly what we want 👍
> 
> Can you also write a tests for this? I think three should assertions should it 🤔
> 
>     * Create 2 pools (one archived, one not)
>       
>       * Assert archived filtered by default
>       * Assert passing in the non-archived pool returns only archived
>       * Assert passing in an unrelated status returns no results

We already had a test for this scope, so I just added on to it a bit in https://github.com/GCTC-NTGC/gc-digital-talent/pull/10970/commits/b56c05954104bd2dc59118082351eb37e1cd8e92

2024-07-12 19:01 UTC, esizer approved these changes
Cool! :sunglasses:

2024-07-12 19:16 UTC, merged