9948 add filters to screening and assessment page
GCTC-NTGC/gc-digital-talent pull request #11018
Opened 2024-07-19 13:21 UTC by yonikid15

🤖 Resolves #9948 

## 👋 Introduction

- Adds filter dialog to Screening and assessment page
- Adds the filters specified in design
- Question: The talent placement table (PoolCandidatesTable), filters out candidates that are expired or suspended by default. If we want the screening and assessment table to show the same data, then we need to filter those fields as well. 

![image](https://github.com/user-attachments/assets/9827bafc-62d7-4f49-ae1e-44f4058dcb83)

Do we want to filter the data by default like the talent placement table and allow the user to change it in the dialog, or not have that filter available in dialog at all, but still filter expired and suspended users in the query?

## 🕵️ Details

Add any additional details that could assist with reviewing or testing this PR.

## 🧪 Testing

1. Build app `pnpm run dev`
2. Login as `admin@test.com`
3. Go to process and view screening and assessment page
4. Ensure the dialog filters out the correct candidates. Ensure the other filters still work correctly.

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/dc30538f-c7ba-415d-903a-cef14dc273ce)

2024-07-19 14:38 UTC, Jerryescandon commented
I think it should be fine to have them be filtered out by default as long as we can go into the filters to show them again.

2024-07-23 13:54 UTC, esizer requested changes
Works well! :+1:  I just have a few suggestions.

2024-07-23 23:54 UTC, yonikid15 commented on apps/web/src/components/AssessmentStepTracker/AssessmentResultsFilterDialog.tsx
> +    }
How did I miss this :laughing: Fixed by [8c68e43](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11018/commits/8c68e439a9ddcb7cdac3e4a46fcf2a792d48c112)

2024-07-23 23:55 UTC, yonikid15 commented on apps/web/src/components/AssessmentStepTracker/AssessmentResultsFilterDialog.tsx
> +        </div> */}
This is not getting used I added it while it was undetermined whether these fields would exist on dialog  :laughing: Fixed by [8c68e43](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11018/commits/8c68e439a9ddcb7cdac3e4a46fcf2a792d48c112)

2024-07-23 23:57 UTC, yonikid15 commented on apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.tsx
> +        <div data-h2-margin-bottom="l-tablet(x.5)">
I tried to copy the styling for the other tables. If this doesn't suffice then I can try something else.
[c4309c2](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11018/commits/c4309c2c8d8515153f577bd8e8f87f3b8b2fde90)

2024-07-23 23:57 UTC, yonikid15 commented on apps/web/src/components/AssessmentStepTracker/AssessmentResultsFilterDialog.tsx
> +          nullSelection=""
Fixed by [890dec2](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11018/commits/890dec2bdc74d908bc829b0dfec81b729fec9756)

2024-07-23 23:57 UTC, yonikid15 commented on apps/web/src/components/AssessmentStepTracker/AssessmentResultsFilterDialog.tsx
> +            nullSelection=""
Fixed by [e03e60e](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11018/commits/e03e60e84bec96b7fbcb84d6867bf201d2c2571d)

2024-07-24 12:06 UTC, esizer approved these changes

2024-07-24 15:17 UTC, merged