[Feat] Add published date to pools table
GCTC-NTGC/gc-digital-talent pull request #11068
Opened 2024-07-25 16:51 UTC by esizer

🤖 Resolves #11044 

## 👋 Introduction

Adds published at date to the pools table.

## 🧪 Testing

1. Build `pnpm run dev:fresh`
2. Logion as admin `admin@test.com`
3. Navigate to pools table `/admin/pools`
4. Confirm the published column shows up
5. Confirm it sorts as expected
6. Confirm you can show/hide it

## 📸 Screenshot

![2024-07-25_12-49](https://github.com/user-attachments/assets/a2a08f1e-ad60-44cf-bb0d-cfd53be5f643)

2024-07-25 22:52 UTC, vd1992 requested changes

2024-07-25 22:52 UTC, vd1992 commented on apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx
Tiny tweak needed, needs to be hidden by default

![image](https://github.com/user-attachments/assets/618482ca-438d-451f-a0c7-ef62724b2a35)

2024-07-26 12:51 UTC, esizer commented on apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx
Good catch, thanks! Hidden by default after [hide published column by default](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11068/commits/7fcd5962b37c4c5994fac3646aeabb2d5982b026)

2024-07-26 16:21 UTC, vd1992 approved these changes
💯

2024-07-27 11:42 UTC, merged