[Feature] Use community relation of search requests
GCTC-NTGC/gc-digital-talent pull request #11132
Opened 2024-08-01 23:05 UTC by vd1992

🤖 Resolves #10366

## 👋 Introduction

Describe what this PR is solving.

## 🕵️ Details

Add any additional details that could assist with reviewing or testing this PR.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. ...
2. ...

## 📸 Screenshot

Add a screenshot (if possible).

## 🚚 Deployment

Run the role permission seeder

2024-08-02 22:50 UTC, vd1992 commented on Makefile
Fine tuned once I understood how the command worked

`make test` for all
or
`make test CMD="--filter abc"` to filter conveniently

2024-08-02 22:50 UTC, vd1992 commented on api/database/seeders/SearchRequestRandomSeeder.php
I think this is now the intent and not the prior state of 50 requests attached to a single applicant filter

2024-08-02 23:11 UTC, vd1992 commented on apps/playwright/tests/admin/auth.spec.ts
Definitely not the end state, but matching up the roles to everything they should be able to see will come later

2024-08-06 18:48 UTC, vd1992 commented on api/app/Models/Pool.php
Needing to add to `$selectable` tripped me up for a couple of hours 😞

2024-08-07 20:45 UTC, tristan-orourke requested changes
Looking good!

2024-08-07 22:09 UTC, vd1992 commented on api/database/seeders/SearchRequestRandomSeeder.php
Yeah sure, completed over the course of
https://github.com/GCTC-NTGC/gc-digital-talent/pull/11132/commits/ee16dc637466cb5e2cdad8e2afb4bd4c0e609bdb
https://github.com/GCTC-NTGC/gc-digital-talent/pull/11132/commits/8f895ac7eb5d59c99838ac89fb0d54d93fea8f42

2024-08-07 22:09 UTC, vd1992 commented on api/app/Models/PoolCandidate.php
> +        });
Yep, makes sense to me, done in https://github.com/GCTC-NTGC/gc-digital-talent/pull/11132/commits/8cbef0901856e209306779ea5cec37143dab2a8f

2024-08-07 22:09 UTC, vd1992 commented on api/app/Models/Pool.php
> +        'community_id',
https://github.com/GCTC-NTGC/gc-digital-talent/pull/11132/commits/e9a3b2063a598b835352e3ccfbf44364efb2fe54

2024-08-07 22:09 UTC, vd1992 commented on api/app/Models/PoolCandidateSearchRequest.php
> +        if (! $user) {
Yeah sure, done in https://github.com/GCTC-NTGC/gc-digital-talent/pull/11132/commits/7e3ee9174d44d125806e1b02a7b554adfdca7fd6

2024-08-07 22:10 UTC, vd1992 commented on api/database/factories/CommunityFactory.php
> +    public function configure()
Oh okay, I thought we wanted them created by default and it was missing
Reversed in https://github.com/GCTC-NTGC/gc-digital-talent/pull/11132/commits/8ce51cbbe75e3c69ceade956f12d573311b52200

2024-08-07 22:10 UTC, vd1992 commented on api/database/factories/PoolFactory.php
> +    public function configure()
https://github.com/GCTC-NTGC/gc-digital-talent/pull/11132/commits/8ce51cbbe75e3c69ceade956f12d573311b52200

2024-08-07 22:12 UTC, vd1992 commented on apps/playwright/fixtures/CommunityRecruiterPage.ts
> +  }
🤷‍♂️ 
I am just trying to keep things consistent with what already exists, so I dunno I just copied what was already there

2024-08-08 18:19 UTC, tristan-orourke commented on apps/playwright/fixtures/CommunityRecruiterPage.ts
> +  }
Yeah, this is duplicated now across  three different classes. Let's move `createUser` and `addRolesToUser` into the AppPage class.

2024-08-08 18:19 UTC, tristan-orourke requested changes
Thanks, just two small changes left I'd like to see.

2024-08-08 18:52 UTC, vd1992 commented on apps/playwright/fixtures/CommunityRecruiterPage.ts
> +  }
Sure
https://github.com/GCTC-NTGC/gc-digital-talent/pull/11132/commits/a3c5ce8ab8f37b98b7add4a2037a48ce30f3eddc
https://github.com/GCTC-NTGC/gc-digital-talent/pull/11132/commits/17dadd9c0ca1f531fd5475553f26326a7cd3771e
Turns out I didn't need the change in the second commit

2024-08-09 15:28 UTC, tristan-orourke requested changes
Just a couple comments about changes to tables:
- If you show the Community column in the Talent Requests table, it appears to be sortable, but clicking it doesn't change any ordering
- If you go to a View Talent Request page and open the filter dialogs, Community is always empty. It should be initialized with the community from the request filter.

2024-08-09 17:00 UTC, vd1992 commented
Ah, thanks 

1. Yeah, I overlooked that. Removed the sortability so it is like the rest of the columns with chained relations https://github.com/GCTC-NTGC/gc-digital-talent/pull/11132/commits/3c2c90f49cb5cacb0938a3e8f7db1007b69e9ecf
2. Oh, whoops. A little tricky to get to the bottom of, but think I got it in https://github.com/GCTC-NTGC/gc-digital-talent/pull/11132/commits/27791bcf7c46f36378e0e6c44f9bcf7e153a068a

2024-08-09 17:26 UTC, tristan-orourke approved these changes
All good!

2024-08-09 17:31 UTC, merged