[Debt] Removes `Hero`, `CheckButton`, and `Alert` css files
GCTC-NTGC/gc-digital-talent pull request #11197
Opened 2024-08-08 17:44 UTC by mnigh

🤖 Resolves #10933.

## 👋 Introduction

This PR consolidates css for `Hero`, `CheckButton`, and `Alert` making use of `data-h2` attributes instead of vanilla css within css files.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. `pnpm storybook`
2. Navigate to `Hero`, `CheckButton`, and `Alert` stories
3. Verify components appear and function as they did before without any changes

2024-08-08 22:24 UTC, vd1992 requested changes

2024-08-08 22:24 UTC, vd1992 commented on packages/ui/src/components/Alert/alert.css
Think you meant to delete this file and not just empty it out 😛 

![image](https://github.com/user-attachments/assets/6359a117-0ba3-45df-b7d3-d0879c9c1f4e)

2024-08-09 13:10 UTC, mnigh commented on packages/ui/src/components/Alert/alert.css
b9e301484a2b9c0a0ae6d1701a5d00bde7520609

2024-08-09 16:20 UTC, vd1992 approved these changes

2024-08-09 17:09 UTC, merged