Move template instructions and boilerplate into comments
GCTC-NTGC/gc-digital-talent pull request #11295
Opened 2024-08-20 16:54 UTC by petertgiles

## 👋 Introduction

I get a bit annoyed when I have to delete a bunch of template instructional text and boilerplate when writing up an issue or PR.  I also get annoyed when said text and boilerplate ends up in posted text.  I had the idea of using comments instead.

Let me know what you think of this idea.

## 🕵️ Details

A few small other changes:
- Removed example blocker item from the tasklist.  Those usually aren't added in the markdown editor anyway.
- Merged designer tag into design section.  We probably don't need a whole h3 section for a user name.

2024-08-20 17:19 UTC, mnigh requested changes
I'm ok with removing the designer section and incorporating it into the design section, but the Design File heading should be renamed accordingly.

2024-08-20 17:19 UTC, mnigh commented on .github/ISSUE_TEMPLATE/✨-feature-request.md
>  ## 🎨 Design File
```suggestion
## 🎨 Design
```

2024-08-20 17:19 UTC, mnigh commented on .github/ISSUE_TEMPLATE/🔤-copy.md
>  ## 🎨 Design File
```suggestion
## 🎨 Design
```

2024-08-20 17:19 UTC, mnigh commented on .github/ISSUE_TEMPLATE/⚙️-new-component.md
>  ## 🎨 Design File
```suggestion
## 🎨 Design
```

2024-08-20 17:35 UTC, mnigh approved these changes

2024-08-22 14:22 UTC, petertgiles commented
This has been up a few days and no one has objected.  I'll merge.

2024-08-22 14:23 UTC, merged