[Tests] Add PHP testing for new roles
GCTC-NTGC/gc-digital-talent pull request #11409
Opened 2024-08-28 20:11 UTC by vd1992

🤖 Resolves #10690 

## 👋 Introduction

## 🕵️ Details

## 🧪 Testing

## 📸 Screenshot

## 🚚 Deployment

2024-08-29 17:32 UTC, vd1992 commented on api/app/GraphQL/Mutations/UpdateUserTeamRoles.php
`UpdateUserTeamRolesTest` was removed in https://github.com/GCTC-NTGC/gc-digital-talent/pull/11353 but this mutation class was missed

2024-09-03 14:16 UTC, petertgiles requested changes
Looks great!  Love the new tests.  Let's take a second look at that policy update, though.

2024-09-03 16:35 UTC, vd1992 commented on api/app/Policies/PoolPolicy.php
> +        if ($pool->getStatusAttribute() === PoolStatus::DRAFT->name) {
Aye aye https://github.com/GCTC-NTGC/gc-digital-talent/pull/11409/commits/6b94944269b31fa4aeebefc90ceaf313e093098a

2024-09-03 17:32 UTC, petertgiles commented on api/app/Policies/PoolPolicy.php
> +        if ($pool->getStatusAttribute() === PoolStatus::DRAFT->name) {
Thanks, that looks better. :+1:

2024-09-03 17:32 UTC, petertgiles approved these changes

2024-09-03 19:15 UTC, merged