[Feature] Add "content below" to checklist
GCTC-NTGC/gc-digital-talent pull request #11423
Opened 2024-08-29 21:00 UTC by petertgiles

🤖 Related to (but does not close) #11285 

## 👋 Introduction

This branch adds the ability to add "content below" for checklists.  This is needed for the "area of selection" stuff.

## 🧪 Testing

1.Start Storybook or Chromatic.
2. Check the Checklist \ Content Below story

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/ca88ed46-2f44-48a4-8527-db9a86bd1acc)

2024-08-29 22:41 UTC, vd1992 requested changes

2024-08-29 22:41 UTC, vd1992 commented on packages/forms/src/components/Checklist/Checklist.stories.tsx
Should probably slap a `faker.seed(0)` here somewhere to avoid noise
The content below prop is varying

![image](https://github.com/user-attachments/assets/8ef4332d-e191-4d67-86e6-7604abb5ca5c)

2024-08-30 13:15 UTC, petertgiles commented on packages/forms/src/components/Checklist/Checklist.stories.tsx
Oh, good catch.
[reset seed](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11423/commits/5691e385b041f5337bd79f2578bfb9e3c6122efd)

2024-08-30 15:04 UTC, vd1992 approved these changes

2024-08-30 15:27 UTC, merged