[Feature] Last active at tracking
GCTC-NTGC/gc-digital-talent pull request #11437
Opened 2024-09-03 18:31 UTC by vd1992

🤖 Resolves #11426 

## 👋 Introduction

Adds a field to track last active and handles updating it through an authorization callback

## 🧪 Testing

1. Migration works
2. Open up database tool and check logging in updates the new field

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/797ce138-c5e1-4b2b-9383-8567b88582c3)

2024-09-04 12:57 UTC, petertgiles requested changes
Looking good!  I suggested a change to the implementation to get a little closer to the AC.

2024-09-04 12:57 UTC, petertgiles commented on api/app/Providers/AuthServiceProvider.php
Hmm, I'm not sure this is the best place for the timestamp update.  This gets called for every request so the timestamp is continually being updated - not just when they log in.  I recommend moving this over to the auth callback so it only occurs on login.  You can see that the token that we receive and decode there does have the sub available, just like we grab the nonce.
![image](https://github.com/user-attachments/assets/a7403d58-114f-403f-bbfd-5011165c0d7c)

2024-09-04 17:32 UTC, vd1992 commented on api/app/Providers/AuthServiceProvider.php
Oh, there actually is something called auth callback specifically and it wasn't meant in the general sense 😊 
Tweaked in https://github.com/GCTC-NTGC/gc-digital-talent/pull/11437/commits/91130bdc427a6eddcc0a988b1cf990c7012849f1
Wasn't sure how to test it

2024-09-05 14:51 UTC, petertgiles reviewed
Ooh, a bit stuck now...

2024-09-05 15:36 UTC, petertgiles commented on api/app/Providers/AuthServiceProvider.php
OK, decision in standup is that this is good enough for now.  I'll create a new issue to adjust this.

2024-09-05 15:44 UTC, merged