[Fix] Update manager dashboard UI
GCTC-NTGC/gc-digital-talent pull request #11667
Opened 2024-09-27 18:16 UTC by petertgiles

🤖 Resolves #11575

## 👋 Introduction

This branch corrects (almost) all the items from Josh's design review of the manager dashboard page.

## 🕵️ Details

Note that one AC was not done:
>  The final item in the request accordion shouldn't have bottom padding, as the card already provides it

I think it's already correct:
![image](https://github.com/user-attachments/assets/6c597619-66e9-4e9c-ad8d-0dc7d628a3ce)

## 🧪 Testing

1. Uncomment the loader in router.tsx to enable the manager dashboard page
2. Visit /en/manager/dashboard

2024-10-02 12:37 UTC, yonikid15 requested changes
Looking good so far! :+1: 

I found one thing: The preview list padding on the bottom is still larger than it needs to be (x1). Dropping it to x.5 should keep it balanced with the accordion heading at the top.
![image](https://github.com/user-attachments/assets/625f82b4-52be-4f38-9c82-516f3ef94a9b)

2024-10-02 14:48 UTC, petertgiles commented
Ah, that was the last one, thanks!
[The final item in the request accordion shouldn't have bottom padding…](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11667/commits/c579ba3ecbfdc92dffaa550d7f56b520d5ca3289)

2024-10-02 14:49 UTC, petertgiles commented
Looks like x0.25 is what Josh was looking for.
![image](https://github.com/user-attachments/assets/577fa800-dc86-4f82-b4e3-6ed8e165eecd)

2024-10-03 14:13 UTC, yonikid15 requested changes

2024-10-03 14:13 UTC, yonikid15 commented on apps/web/src/pages/ManagerDashboardPage/ManagerDashboardPage.tsx
> +                    data-h2-padding-bottom="base:selectors[>.Accordion__Item > .Accordion__Content](0)"
I think you want this to be x.5 so it matches the space at the top of the box.
![image](https://github.com/user-attachments/assets/a2553276-05d1-4dbc-9caf-0338a393ff93)


```suggestion
                    data-h2-padding-bottom="base:selectors[>.Accordion__Item > .Accordion__Content](x.5)"
```

Another option could be to update the TaskCard.Item bottom padding that wraps everything, but this works as well.

2024-10-03 14:28 UTC, yonikid15 approved these changes
LGTM :tada:

2024-10-03 16:31 UTC, merged