[Debt] User creation shifted to `authCallback()`
GCTC-NTGC/gc-digital-talent pull request #11759
Opened 2024-10-15 18:53 UTC by vd1992

🤖 Resolves #11466

## 👋 Introduction

Shift user creation to the callback in AuthController.php
Nothing fancy needed to be done

## 🧪 Testing

1. Can log in normally with existing user
2. User creation works
3. Sign in values updated or set appropriately
4. Test above with SiC

2024-10-15 18:57 UTC, vd1992 commented on api/tests/Feature/AuthServiceProviderTest.php
We've no testing for auth controller

2024-10-15 19:09 UTC, vd1992 commented
Thank you Larastan, that was indeed something to fix, done in https://github.com/GCTC-NTGC/gc-digital-talent/pull/11759/commits/14e866ebf30fa2f42ae1aac329b06ae3e985188b

2024-10-16 14:05 UTC, petertgiles requested changes
This works great!  I tried it with mock auth and SIC and it works well.  :medal_sports:  I'm worried about losing that test, though.  This functionality it too important to not have good testing, IMO.  Could you rewrite the test for this?  Let me know if you want a hand.

2024-10-16 22:50 UTC, vd1992 commented
> This works great! I tried it with mock auth and SIC and it works well. 🏅 I'm worried about losing that test, though. This functionality it too important to not have good testing, IMO. Could you rewrite the test for this? Let me know if you want a hand.

Had a nice learning experience and got something in https://github.com/GCTC-NTGC/gc-digital-talent/pull/11759/commits/2169efed5087c8df788a6a3869dc97cda416f80f

2024-10-17 00:41 UTC, vd1992 commented
Not sure what is going on with the PHP test 😕

2024-10-17 13:44 UTC, petertgiles approved these changes
I love this test!  Very easy to read and understand.  It's a great base to use in the future for more testing, too.

I deployed this branch to Azure and it works well, too.

I'm trying a few things on the phpunit test to try and get that to complete in GH.

2024-10-17 15:39 UTC, merged