[Feature] Admin depertment page styling
GCTC-NTGC/gc-digital-talent pull request #11853
Opened 2024-10-24 19:22 UTC by petertgiles

🤖 Resolves #11478

## 👋 Introduction

Updates the styling of the admin department pages and adds a new "view department" page.

## 🕵️ Details

## 🧪 Testing

1. Rebuild and log in as admin
2. View the department pages

- [ ] Mobile
- [ ] Desktop

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/08550b28-4abe-4648-bf85-dd50f7e0dc63)

2024-10-24 20:28 UTC, mnigh reviewed
Some comments related to copy.

2024-10-24 20:28 UTC, mnigh commented on apps/web/src/pages/Departments/components/DepartmentTable.tsx
> +            defaultMessage: "Create new department",
New is implied when creating something. Can we remove the word new?

2024-10-24 20:28 UTC, mnigh commented on apps/web/src/pages/Departments/components/DepartmentTable.tsx
> +        defaultMessage: "Number",
Everywhere else in the forms, it is referred to as Department number. Should it not be kept the same for consistency?

2024-10-24 20:28 UTC, mnigh commented on apps/web/src/pages/Departments/components/DepartmentTable.tsx
> +          defaultMessage: "Search by keyword",
What is a keyword?

2024-10-24 20:28 UTC, mnigh commented on apps/web/src/pages/Departments/components/DepartmentTable.tsx
> +            'Use the "Create new department" button to get started.',
Same as https://github.com/GCTC-NTGC/gc-digital-talent/pull/11853/files#diff-0fbd163c841c797ff5bf7a62a349a7d280b11674a638626e14ef6e128ecf6881R104.

2024-10-29 19:14 UTC, yonikid15 requested changes
Nice work as always :tada: 
For some reason the nav menu's z-index is overlapping the overlay only on the edit page, when the page is loading :confused: (why isn't it happening on the other pages too :laughing:). To fix this, we can create a new issue or just set them to "2" in lines [NavigationMenu-L45](https://github.com/GCTC-NTGC/gc-digital-talent/blob/11478-admin-departments-styling/apps/web/src/components/Hero/NavigationMenu.tsx#L45) and [NavigationMenu-L184](https://github.com/GCTC-NTGC/gc-digital-talent/blob/11478-admin-departments-styling/apps/web/src/components/Hero/NavigationMenu.tsx#L184)

![Screenshot from 2024-10-29 14-34-27](https://github.com/user-attachments/assets/92a203d2-c31b-401e-a233-8b3ef4f21c1f)

2024-10-29 19:21 UTC, yonikid15 commented
Also the sign out and notifications buttons dark/light modes, aren't synced up with the rest of the dialog. (See far right of nav menu in image in light mode).
![image](https://github.com/user-attachments/assets/3d8bfea5-d4da-4d9f-95a4-7c5c36a4b92d)

Again, this is out of scope, but seems like an easy fix. If not I can create a new issue. Otherwise everything looks good design and code wise:+1:

2024-10-30 12:43 UTC, petertgiles commented
As discussed with Josh, I just removed the navbar that was built-in to the hero and x3 of top padding.
[remove hero nav and padding](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11853/commits/7db6149a2ba4163bf270d0abe74a9b61c0edd4de)

2024-10-30 12:45 UTC, petertgiles commented on apps/web/src/pages/Departments/UpdateDepartmentPage.tsx
> +
This is a good catch.  I could have this be an empty string or "Loading" or something if you want.

2024-10-30 13:55 UTC, petertgiles commented on apps/web/src/pages/Departments/UpdateDepartmentPage.tsx
> +
OK, I added the loading string
[loading title for view page](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11853/commits/d881f102b23e050aa5a73566c917f2af46b80dd1)

2024-10-30 17:22 UTC, merged