[Style] Update classification page layouts
GCTC-NTGC/gc-digital-talent pull request #11901
Opened 2024-11-06 13:17 UTC by esizer

🤖 Resolves #11427 

## 👋 Introduction

Updates the classification pages to use the new layout/styles.

## 🧪 Testing

1. Build the app `pnpm run dev:fresh`
2. Login as admin `admin@test.com`
3. Navigate to the classifications section `/admin/settings/classifications`
4. Check all pages and confirm they function as expected and match the designs

2024-11-08 18:18 UTC, vd1992 reviewed
I probably should've just let @Jerryescandon do the design review first instead, mostly just have questions below 😅

2024-11-08 18:18 UTC, vd1992 commented on apps/web/src/pages/Classifications/components/ClassificationTable.tsx
As well as naming changes

Current

![image](https://github.com/user-attachments/assets/6ca5f555-4ee0-4c0f-ac5c-12b571ff4541)

Figma

![image](https://github.com/user-attachments/assets/1422248d-22e0-4013-8e94-d921ff9b0880)

2024-11-08 18:18 UTC, vd1992 commented on apps/web/src/pages/Classifications/ViewClassificationPage.tsx
> +  });
Crumbs vary

Current

![image](https://github.com/user-attachments/assets/328aa79f-6503-48aa-8e56-16a9faa6c9f3)

Figma (ignoring the admin dashboard one which is the same as the home link)

![image](https://github.com/user-attachments/assets/6a8b5cd5-b665-4562-9fd8-f193b4fde9ce)

2024-11-13 14:05 UTC, petertgiles commented
Please check my review for #11926.  I'm guessing a lot of the same things will come up here.  :smile:

2024-11-14 14:19 UTC, petertgiles requested changes
Cool!  A few more things to tidy up.

2024-11-14 14:19 UTC, petertgiles commented on apps/web/src/pages/Classifications/components/ClassificationTable.tsx
The button should be labelled "Create new classification"

2024-11-14 14:19 UTC, petertgiles commented on apps/web/src/pages/Classifications/components/ClassificationTable.tsx
Hero should be centered in mobile width

2024-11-14 14:19 UTC, petertgiles commented on apps/web/src/pages/Classifications/CreateClassificationPage.tsx
Label should be "Level number"

2024-11-14 14:19 UTC, petertgiles commented on apps/web/src/pages/Classifications/UpdateClassificationPage.tsx
Label should be "Level number"

2024-11-14 14:19 UTC, petertgiles commented on apps/web/src/pages/Classifications/UpdateClassificationPage.tsx
Icon should be the info cord, not cloud

2024-11-14 14:49 UTC, esizer commented on apps/web/src/pages/Classifications/UpdateClassificationPage.tsx
It is actually using a cloud in the design.

![2024-11-14_09-49](https://github.com/user-attachments/assets/cb37933f-bddd-401f-9bac-a38e7800fdf6)

2024-11-14 14:51 UTC, esizer commented on apps/web/src/pages/Classifications/components/ClassificationTable.tsx
I'm just using the default hero and it looks centered on my end :thinking: 

![2024-11-14_09-50](https://github.com/user-attachments/assets/e375f1b3-4b52-44c1-9c0c-6fe4e7fa6ba0)

2024-11-14 14:52 UTC, petertgiles commented on apps/web/src/pages/Classifications/UpdateClassificationPage.tsx
@Jerryescandon please confirm?

2024-11-14 14:54 UTC, esizer commented on apps/web/src/pages/Classifications/components/ClassificationTable.tsx
Weird, I though "new" was implied when creating something :laughing: 

Fixed in [update add label](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11901/commits/c6550f05aad00a20fa90b19819ae833b59584d65)

2024-11-14 14:54 UTC, esizer commented on apps/web/src/pages/Classifications/CreateClassificationPage.tsx
Updated all instances in [update level label to include number](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11901/commits/b9a44ce4d630db0789561060bd9f8c92a28683dd)

2024-11-14 16:37 UTC, Jerryescandon commented on apps/web/src/pages/Classifications/components/ClassificationTable.tsx
I would say yes, and get them over with now. But I dont know how big they are 😬

2024-11-14 17:02 UTC, petertgiles approved these changes

2024-11-15 16:07 UTC, merged