[Style] Update skill family page layouts
GCTC-NTGC/gc-digital-talent pull request #11926
Opened 2024-11-08 14:43 UTC by esizer

🤖 Resolves #11477 

## 👋 Introduction

Updates the layouts for the skill family pages.

## 🧪 Testing

1. Build `pnpm run dev:fresh`
2. Login as admin `admin@test.com`
3. Navigate to the skill families pages `/admin/settings/skill-families`
4. Confirm the pages match the mock ups

2024-11-13 14:04 UTC, petertgiles requested changes
Very nice!  I flagged a few things that came up in my reviews here.

2024-11-13 14:04 UTC, petertgiles commented on apps/web/src/pages/SkillFamilies/UpdateSkillFamilyPage.tsx
Key field should be visible on this page.

2024-11-13 14:04 UTC, petertgiles commented on apps/web/src/pages/SkillFamilies/UpdateSkillFamilyPage.tsx
I think the app should navigate to the view skill family page after submission

2024-11-13 14:04 UTC, petertgiles commented on apps/web/src/pages/SkillFamilies/CreateSkillFamilyPage.tsx
I think the app should navigate to the view skill family page after successful submission

2024-11-13 14:04 UTC, petertgiles commented on apps/web/src/pages/SkillFamilies/UpdateSkillFamilyPage.tsx
Title should be centred and form buttons should be centred in a column in mobile view

2024-11-13 14:41 UTC, esizer commented on apps/web/src/pages/SkillFamilies/components/SkillFamilyTable.tsx
Fixed in [update search input label](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11926/commits/7bcd159a5ff08e4b01f56b5ee7b08bc0d1af2762)

2024-11-13 14:42 UTC, esizer commented on apps/web/src/pages/SkillFamilies/ViewSkillFamilyPage.tsx
Completed all view related changes in [fix view page layout issues](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11926/commits/6290c79e8ef6507d347f12229fbf44f1ad0dcb56)

2024-11-13 17:37 UTC, petertgiles commented
I think everything is done except for centering the headings in mobile width

2024-11-13 18:01 UTC, esizer commented
> I think everything is done except for centering the headings in mobile width

I think I misenterpreted what you meant by section headings. I did some centering, but was it the wrong heading?

![2024-11-13_13-01](https://github.com/user-attachments/assets/35a3c1b5-464b-4718-9308-42037661cbeb)

2024-11-13 19:58 UTC, esizer commented
> I think everything is done except for centering the headings in mobile width

Thanks for helping me out, it should be fine now after [fix heading centering](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11926/commits/6f6153abf8ff7b9b4afbfa85bd4d4927911b88b7)

2024-11-13 20:29 UTC, petertgiles commented
Headings look good!  I noticed one last thing: the gap in the view page is very large.  Could you please double-check?
![image](https://github.com/user-attachments/assets/bccea814-34a9-417d-949d-5cc5464c1be6)

2024-11-14 12:59 UTC, esizer commented
> Headings look good! I noticed one last thing: the gap in the view page is very large. Could you please double-check?

Good catch, I missed zeroiing out the margin on that heading 😬 

[fix heading spacing](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11926/commits/08266ba2e33c95d2ee2bb568bf71a0cbaaa84183)

2024-11-14 13:52 UTC, petertgiles approved these changes
Nice!

2024-11-15 16:07 UTC, merged