[Bugfis] Fixing frontend permissions for new Community roles
GCTC-NTGC/gc-digital-talent pull request #12007
Opened 2024-11-18 20:58 UTC by tristan-orourke

🤖 Resolves #11767 

## 👋 Introduction

## 🕵️ Details

## 🧪 Testing

## 📸 Screenshot

## 🚚 Deployment

2025-01-07 19:29 UTC, mnigh commented
@tristan-orourke can this PR be closed and the branch be left around for reference?

2025-01-23 17:51 UTC, vd1992 commented on apps/playwright/tests/auth/admin.spec.ts
> +  const restrictedPathsChunk2 = AUTH.RESTRICTED_PATHS.ADMIN.slice(4);
Performance improvement attempt

2025-01-23 17:53 UTC, vd1992 commented on apps/playwright/tests/auth/admin.spec.ts
> +        ).toBeVisible();
I found negative assertions, checking something is hidden, unreliable off page load. Tests would perform contrary to expectation. Likely due to asserting something was hidden at a loading screen.
So, a positive assertion first then negative assertion.

2025-01-23 19:34 UTC, esizer commented on apps/web/src/constants/permissionConstants.ts
> +  const viewCandidates: RoleName[] = [
Is there a reason this was changed back to a function? Is it not just plain old arrays? We could just return the readonly record so we don't need to invoke a function call every time we read a permission

2025-01-23 19:40 UTC, vd1992 commented on apps/web/src/constants/permissionConstants.ts
> +  const viewCandidates: RoleName[] = [
🤷

2025-01-23 21:06 UTC, vd1992 commented on packages/auth/src/components/AuthorizationProvider.tsx
You need the teamable object id to test in `hasRole` to test against teams, but some teamable objects like draft pools aren't accessible off  non-protected URLs. It makes more sense query less information on non-protected URLs than to expose protected information given you only test teams on protected URLs

2025-01-23 21:07 UTC, vd1992 commented on packages/auth/src/utils/hasRole.ts
I thought this function was too important to play loosey-goosey with type
No Maybe<Maybe> welcome

2025-01-23 22:06 UTC, tristan-orourke commented on apps/web/src/constants/permissionConstants.ts
> +  const viewCandidates: RoleName[] = [
I'm pretty sure this code is from when this was originally a function. That got changed in #12065 but hasn't been properly merged here. Long story short, I'd rather this go back / stay as plain old arrays.

2025-01-23 22:22 UTC, tristan-orourke commented on packages/auth/src/components/AuthorizationProvider.tsx
That's a good catch, but this conditional bevaviour in a high-level component will force the whole app to re-render if you switch between a protected and non-protected url. Is there an alternative?

My first question is, does `hasRole` need to accept a `teamableId`? I see that there's only one place in the app right now where we pass that in. We could re-evaluate whether that's really necessary. Or we could try to make it work by passing in a `teamId` instead of `teamableId`? Or, if some teamable objects are not accessible, we could probably make `teamableId` itself accessible directly on the Team object, without being a security risk.

2025-01-23 22:48 UTC, vd1992 commented on packages/auth/src/components/AuthorizationProvider.tsx
To be honest, I'm just following the A/C without thinking too much on it

2025-01-23 22:48 UTC, vd1992 commented on apps/web/src/constants/permissionConstants.ts
> +  const viewCandidates: RoleName[] = [
Aye aye, https://github.com/GCTC-NTGC/gc-digital-talent/pull/12007/commits/2626e777b3d42106e0f12c7e2c9354afffc604f7

2025-01-23 23:49 UTC, vd1992 commented on packages/auth/src/components/AuthorizationProvider.tsx
Okay, I got an idea and elected to try using `teamIdForRoleAssignment` instead  https://github.com/GCTC-NTGC/gc-digital-talent/pull/12007/commits/156573aba8b24c7b391a59072ee422f2e058b561

2025-01-27 13:29 UTC, esizer requested changes
Sorry, I don't want to drip feed stuff but I feel like this possible change may end up with a lot of file touches :cry:

2025-01-27 13:29 UTC, esizer commented on packages/auth/src/components/AuthorizationProvider.tsx
I noticed we are needing to wrap the `roleAssignments` from the `useAuthorization` hook every time. It probably makes more sense to do it in the provider and update the type so we can use it directly and avoid running the filter every time we use them.

2025-01-27 18:41 UTC, vd1992 commented on packages/auth/src/components/AuthorizationProvider.tsx
https://github.com/GCTC-NTGC/gc-digital-talent/pull/12007/commits/04959eb4ece39d83541f241db1161377b5ab1626
https://github.com/GCTC-NTGC/gc-digital-talent/pull/12007/commits/520111be7a8c6e48fc3576c61654cf4fc1eb08a1

Filtering was already done here 
![image](https://github.com/user-attachments/assets/509e24c0-c644-4a7e-8263-b2ebf3c1e4af)

2025-01-27 19:45 UTC, esizer requested changes
Some of these may not be actionable. We will likely need someone to weigh in on them.

2025-01-27 19:45 UTC, esizer commented on apps/web/src/pages/Communities/CommunityLayout.tsx
>      [ROLE_NAME.PlatformAdmin, ROLE_NAME.CommunityAdmin],
Do we have a permission we can use here? Or do we expect to sometimes just pass a one-off array of roles?

2025-01-27 19:45 UTC, esizer commented on packages/auth/src/utils/hasRole.ts
> +  return !!result?.length;
This is effectivley `Array.protoype.some()`. We could just do:

```return userRoleAssignments.some((roleAssignment) => { ... });```

Instead of using `filter` and the checking the length

2025-01-27 19:45 UTC, esizer commented on apps/web/src/pages/Communities/CommunityMembersPage/components/useAvailableRoles.ts
>      }
Should this be replaced with a permission constant?

2025-01-27 19:45 UTC, esizer commented on apps/web/src/pages/Communities/IndexCommunityPage/components/CommunityTable/CommunityTable.tsx
> +  const canCreateMembers = hasRole([ROLE_NAME.PlatformAdmin], roleAssignments);
Another instance where we could use a permission constant

2025-01-27 23:45 UTC, vd1992 commented on apps/web/src/pages/Communities/CommunityLayout.tsx
>      [ROLE_NAME.PlatformAdmin, ROLE_NAME.CommunityAdmin],
In some cases, yeah it'd be one-offs, but not here. https://github.com/GCTC-NTGC/gc-digital-talent/pull/12007/commits/8e0598ea3565b544d8f1f0e50221c082e7bc2707

2025-01-27 23:45 UTC, vd1992 commented on apps/web/src/pages/Communities/CommunityMembersPage/components/useAvailableRoles.ts
>      }
Not here I think, this really isn't dealing in permissions stuff at all

2025-01-27 23:46 UTC, vd1992 commented on apps/web/src/pages/Communities/IndexCommunityPage/components/CommunityTable/CommunityTable.tsx
> +  const canCreateMembers = hasRole([ROLE_NAME.PlatformAdmin], roleAssignments);
Yeah, added in https://github.com/GCTC-NTGC/gc-digital-talent/pull/12007/commits/8e0598ea3565b544d8f1f0e50221c082e7bc2707

2025-01-27 23:48 UTC, vd1992 commented on apps/web/src/pages/Communities/IndexCommunityPage/components/CommunityTable/CommunityTable.tsx
> +  const canCreateMembers = hasRole([ROLE_NAME.PlatformAdmin], roleAssignments);
Permission name I added does not match variable name, instead I matched it to what it controls 

![image](https://github.com/user-attachments/assets/3de1b661-a360-4de6-a7a6-4617da56bee1)

2025-01-27 23:48 UTC, vd1992 commented on packages/auth/src/utils/hasRole.ts
> +  return !!result?.length;
Aye aye, done in https://github.com/GCTC-NTGC/gc-digital-talent/pull/12007/commits/c0c71b5e64f42e58e7ade947484e728d317031af

2025-01-28 13:08 UTC, esizer commented on apps/web/src/pages/Communities/CommunityMembersPage/components/useAvailableRoles.ts
>      }
Okay, that makes sense to me :+1:

2025-04-29 22:44 UTC, vd1992 commented
🏳️

2025-04-30 17:43 UTC, vd1992 commented
Re-open if someone wants to push for this

2025-04-30 17:43 UTC, closed without merging