[Fix] Signout action in nav menu
GCTC-NTGC/gc-digital-talent pull request #12031
Opened 2024-11-20 19:36 UTC by esizer

🤖 Resolves #11981 

## 👋 Introduction

Updates the signout action to be a link to `/logged-out` to preserve keyboard shortcuts and styling.

## 🕵️ Details

This can act as an interim fix since it is better than what we currently have. The main issue right now is that the confirmation is still a dialog which comes with the expectation of focus management. Since we are visting a new page we lose focus entirely and it will shift back to the heading of the previous page when cancelling.

A solution could be, instead of using a dialog, we add the confirmation directly on the page like how GitHub does it currently.

## 🧪 Testing

1. Build `pnpm run dev:fresh`
2. Sign in as any existing user
3. Tab to the "Your account" dropdown
4. Confirm that arrow keys allow you to navigate all items in the dropdown (including sign out)
5. Confirm sign out action has the proper styles (specifically hover and focus)
6. Confirm activating the sign out link navigates you to `/logged-out` with confirmation
7. Confirm the cancel action returns you to your previous page
 -->

## 📸 Screenshot

![2024-11-20_14-35](https://github.com/user-attachments/assets/38ea0f78-59d8-49d4-a088-f7bb721ab49d)

2024-11-21 23:33 UTC, vd1992 requested changes
Found some things for your attention below

2024-11-21 23:33 UTC, vd1992 commented on apps/web/src/components/NavMenu/useMainNavLinks.tsx
It disappears in light mode

![image](https://github.com/user-attachments/assets/513dff16-b22c-4fe1-8871-7d1a94e5563c)

2024-11-21 23:33 UTC, vd1992 commented on apps/web/src/components/NavMenu/useMainNavLinks.tsx
Opening signout dialog logs a console warning

![image](https://github.com/user-attachments/assets/ed8dea15-345f-432f-921c-51ce59d2aee3)

2024-11-22 13:58 UTC, esizer commented on apps/web/src/components/NavMenu/useMainNavLinks.tsx
Fixed in [fix sign out link colour](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12031/commits/24a15b441ed629235b3c2fc12774672f714cbbdc)

2024-11-22 13:58 UTC, esizer commented on apps/web/src/components/NavMenu/useMainNavLinks.tsx
Good catch! Added a description in [add description to signout confirmation](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12031/commits/51a767a9c6e400bf725aa280d067b69ec0c4fdd2)

2024-11-22 17:30 UTC, vd1992 requested changes
Might've been present for my last review, sorry I missed this

2024-11-22 17:30 UTC, vd1992 commented on apps/web/src/components/NavMenu/useMainNavLinks.tsx
Got a little bit of a hiccup, look at the background. You aren't actually logged out, hitting cancel takes you back, but it is quite confusing

![image](https://github.com/user-attachments/assets/48b1e10c-670e-493f-bfa5-bc86c092f3ba)

2024-11-22 17:38 UTC, vd1992 approved these changes
Looking good, nice 👍

2024-11-22 17:38 UTC, esizer commented on apps/web/src/components/NavMenu/useMainNavLinks.tsx
Yeah, not my favourite solution but it works for now :sweat_smile:

2024-11-22 17:41 UTC, merged