[Feature] Generated docs add work experience fields
GCTC-NTGC/gc-digital-talent pull request #12108
Opened 2024-11-27 19:21 UTC by vd1992

🤖 Resolves #11869

## 👋 Introduction

## 🕵️ Details

## 🧪 Testing

## 📸 Screenshot

## 🚚 Deployment

2024-12-02 23:34 UTC, vd1992 commented
Now in French too! https://github.com/GCTC-NTGC/gc-digital-talent/pull/12108/commits/811691dfe4bd4ef683becca2d50050f50d7e2eae

2024-12-03 14:29 UTC, petertgiles requested changes
Works great!  Two small suggestions.

2024-12-03 17:45 UTC, vd1992 commented on api/app/Models/WorkExperience.php
> +            if ($this->end_date > $now) {
Yeah sure, https://github.com/GCTC-NTGC/gc-digital-talent/pull/12108/commits/ddaf14a1feb2a54bc336f628d403ed378674fdf8

2024-12-03 17:45 UTC, vd1992 commented on api/app/Traits/Generator/GeneratesUserDoc.php
> +                    $classification = Classification::findOrFail($experience->classification_id);
That makes sense to me, yeah changed in https://github.com/GCTC-NTGC/gc-digital-talent/pull/12108/commits/ddaf14a1feb2a54bc336f628d403ed378674fdf8

2024-12-03 19:56 UTC, petertgiles approved these changes

2024-12-03 20:50 UTC, merged