Updated applicant-facing PoolCandidate status chips
GCTC-NTGC/gc-digital-talent pull request #12365
Opened 2024-12-20 02:44 UTC by JamesHuf

🤖 Will resolve #12164

## 👋 Introduction

Creates/updates some functions for getting applicant-facing status chips for applications.

## 🕵️ Details

The logic for the Received, Under review, Pending assessment, and Under assessment statuses doesn't exactly match the issue but I don't think applicants have access to that much assessment information.

The getQualifiedRecruitmentStatusChip function still needs finished up.

## 🧪 Testing

The labels (but not their descriptions) can be viewed on the Applicant Dashboard `/en/applicant/` and Career Timeline `en/applicant/career-timeline` pages.
Testing the descriptions can only really be done by logging the output.

2025-01-17 17:02 UTC, NienkeBr commented
Not sure how to easily use tables in GitHub, so I'm attached a word file with the updated statuses, descriptions, and translations.

status chips that need to be updated:
- Pending assessment > Application reviewed
- Successful > Qualified in process
- Open to jobs > Open to job offers

See the document for all the updated descriptions: [2025.01.17 Status table.docx](https://github.com/user-attachments/files/18457692/2025.01.17.Status.table.docx)

2025-01-20 14:51 UTC, petertgiles requested changes
Looking cool!  I think I found some bugs but I'm not sure.  :sweat_smile:

2025-01-20 14:51 UTC, petertgiles commented on apps/web/src/utils/poolCandidate.ts
I think I found a bug.  I completed the assessments for step 1 and 2 but the status hasn't flipped to Pending Assessment.
![image](https://github.com/user-attachments/assets/f9fd7226-20b4-471a-a40a-7f37cd65aa46)

2025-01-20 14:51 UTC, petertgiles commented on apps/web/src/utils/poolCandidate.ts
It didn't flip to Under Assessment after completing step 3, either.  I guess step 2 is incomplete, from the exclamation at the top of the column?

2025-01-20 14:51 UTC, petertgiles commented on apps/web/src/utils/poolCandidate.ts
I finished assessment and I'm seeing "Qualified in process" (without a shield) but I haven't actually recorded the final decision yet.
![image](https://github.com/user-attachments/assets/ccb988ba-3f76-4370-9056-bd90eb166d8c)

2025-01-20 21:41 UTC, JamesHuf commented on apps/web/src/utils/poolCandidate.ts
This should be fixed with [0fbc8e8](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12365/commits/0fbc8e8bb54a52e0e48c1fd6f6f18b60773412c0).

2025-01-20 21:47 UTC, JamesHuf commented on apps/web/src/utils/poolCandidate.ts
This appears to be a long lasting discrepancy in how we handle asset behavioural skills. I updated the assessment tracker to match the backend function but am realising that may not have been right. I'll bring it up in standup tomorrow.

2025-01-21 20:37 UTC, JamesHuf commented on apps/web/src/utils/poolCandidate.ts
After a discussion with @Jerryescandon it sounds like we don't actually want non-essential behavioural skills to require assessment. I've reverted my change and created [12552](https://github.com/GCTC-NTGC/gc-digital-talent/issues/12552) for updating both front-end and back-end to never require assessment for non-essential behavioural skills.

2025-01-21 20:39 UTC, JamesHuf commented on apps/web/src/utils/poolCandidate.ts
Until then asset behavioural skills will still require assessment but won't visually appear like it.

2025-01-21 21:19 UTC, petertgiles approved these changes
I've run through an assessment and I _think_ it's working well.  :sweat_smile: I'm approving but I still recommend a demo/review with Gray or Jerbo before merging.

2025-01-23 19:12 UTC, petertgiles approved these changes
Latest change seems good.  :+1: I went through another assessment exercise and saw the chips I expected.

2025-01-23 19:20 UTC, merged