[Feature] Dialogs for applicant dashboard
GCTC-NTGC/gc-digital-talent pull request #12366
Opened 2024-12-20 14:29 UTC by yonikid15

🤖 Resolves #12214 

## 👋 Introduction

> [!NOTE]
> Waiting on [Updated applicant-facing PoolCandidate status chips](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12365)

- Adds preview lists and dialogs for reviewing applications and reviewing recruitment processes.
- **Still needs to be updated to use front-facing pool candidate statuses.** Currently, there's just dummy booleans (e.g. `isSuccessfulStatus = true`) that can be changed to view different states.
- New translations are all scattered. They will be moved into a new `/ApplicantDashboard/applicationDashboardMessages.ts` file.

## 🕵️ Details

- Please check the [detailed requirements](https://github.com/GCTC-NTGC/gc-digital-talent/issues/12214) and figma designs ([Components](https://www.figma.com/design/oZhQe9ahidHFfaiqgREvxa/Dashboard-(All-users)?node-id=1728-34473&t=maEhCofvrlvbtRss-0) and [Requirements](https://www.figma.com/design/oZhQe9ahidHFfaiqgREvxa/Dashboard-(All-users)?node-id=2086-69748&t=maEhCofvrlvbtRss-0)) when testing

- You'll also need to add the route `/applicant/dashboard-test` to see the page:
![image](https://github.com/user-attachments/assets/40ec10c3-7306-4680-a39a-a80b0e975831)
 

## 🧪 Testing

1. Login as whoever
2. Create applications and play around with statuses to view different states
3. View the preview list and dialog and ensure it meets design requirements

2025-01-28 22:00 UTC, mnigh reviewed
Some copy suggestions to avoid duplication.

2025-01-28 22:29 UTC, esizer requested changes
I haven't done a full review but I noticed some stuff in the code that might impact other stuff so it might make sense to resolve some before completion of a more thorough review.

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +  const applications = getFragment<ReviewApplicationPreviewListFragment>(
You do not need to strongly type this generic, passing the fragment as the first argument does this.

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +            subtitle={""}
Is there actually a subtitle and we missed it or should we just omit this?

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +              },
I don't think this check is necessary, we already confirmed the user exists on L 69

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +}) => {
Nitpick but can we type these as an interface? We don't typically inline types like this

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +  return null;
I feel like we could move this to the top of the file so we have an early return and do not need to run through all these checks just to return null.

This applies all of the other components that also return null.

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +        {intl.formatMessage(commonMessages.awarded)}{" "}
I think we need to remove this space since the diving colon includes it and English does not

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +}) => {
We could also move this to an interface

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +  ) {
We seem to be doing this pattern a lot where we assign status checks to a variable and check it immediatley.

I wonder if we could create some arrays that group status and do a single `statusArr.includes(status)` instead :thinking:

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +              timeZone: "Canada/Pacific",
Is this supposed to be pacific time? I fee like it makes more sense to use the users local timezone but I may be wrong

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +        {intl.formatMessage(commonMessages.removed)}{" "}
Need to remove the trailing space

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +      }
If you want, you can replace all of these `{ en fr }` with just `{ localized }`

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +  applicationQuery: ReviewApplicationPreviewListFragment;
I think the type is wrong here. Typically it looks like:

```
  applicationQuery: FragmentType<ReviewApplicationPreviewList_Fragment>;
````

So we get the benefits of fragment masking for type checking.

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +  const application = applicationQuery;
If you are just aliasing this you can do it in the param destructing:

```
({ applicationQuerty: application })
```

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +        }}
Hmm, this makes me wonder if there is a bug somewhere else. Do you remember why this was necessary?

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +            />
I believe all the separators here should have the `decorative` prop

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +                'You can find a job using the "Browse jobs" button or navigation to the "Browse jobs" page from the main navigation.',
I think button is the incorrect term. We had users fail tasks during user testing due to  use of the term "button" when we really mean "link".

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessPreviewList.tsx
> +  recruitmentProcessQuery: ReviewRecruitmentProcessPreviewListFragment;
I tyhink the type should be closer to:


```
recruitmentProcessQuery: FragmentType<ReviewRecruitmentProcessPreviewList_Fragment>;
```

2025-01-28 22:29 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessPreviewList.tsx
> +}) => {
Two things. Can this be an interface and secondly, I think it should be using the `FragmentType` generic.

2025-01-28 22:29 UTC, esizer commented on packages/ui/src/components/Well/Well.tsx
> +export type WellColor = Color | "default";
Having a bit of trouble with the `default` addition. Could we not just fallback to this when we exclude the colour attribute?

2025-01-28 22:29 UTC, esizer commented on packages/ui/src/index.tsx
> +import Well, { WellProps, WellColor } from "./components/Well";
Do we need to export this? I don't tihnk I see it being used outside of this package

2025-01-29 00:33 UTC, JamesHuf reviewed
I found a couple extra things to include in the first round of changes.

2025-01-29 00:36 UTC, JamesHuf commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +          <SEO title={""} description={""} />
We probably don't want empty strings here

2025-01-29 00:37 UTC, JamesHuf commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +    isDraftStatus ||
I don't think you want the first check of `isDraftStatus` here

2025-01-29 15:55 UTC, mnigh commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +                'You can find a job using the "Browse jobs" button or navigation to the "Browse jobs" page from the main navigation.',
In addition to @esizer's comment, I think it should be a verb instead of a noun and therefore change "or navigation to the" should be "or navigate to the". @NienkeBr can you can confirm?

2025-01-29 16:24 UTC, yonikid15 commented on packages/ui/src/index.tsx
> +import Well, { WellProps, WellColor } from "./components/Well";
I was using it in StatusSummary.tsx, however I forgot to switch it back to use Color after refactoring so I can remove these exports now :+1:

2025-01-29 16:35 UTC, yonikid15 commented on packages/ui/src/components/Well/Well.tsx
> +export type WellColor = Color | "default";
That is an excellent point Eric :laughing:

2025-01-29 16:42 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +                'You can find a job using the "Browse jobs" button or navigation to the "Browse jobs" page from the main navigation.',
@JoshBeveridge and @NienkeBr  Is it okay if we change "button" to "link"?

2025-01-29 16:49 UTC, NienkeBr commented on apps/web/src/messages/talentRequestMessages.ts
> +    defaultMessage: "Optional skills",
In the job ads and applications we label them as required and optional, so applicants will recognize these terms. merits the question whether we can't also move to use this on the admin side as it's plainer language.

2025-01-29 16:52 UTC, NienkeBr commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +                'You can find a job using the "Browse jobs" button or navigation to the "Browse jobs" page from the main navigation.',
How about avoiding both and saying "You can start a new application by visiting the “Browse jobs” page and selecting an opportunity."

2025-01-29 18:32 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +        }}
I think it had to do with the structure of the PreviewList component, but I did do this a month ago so it's hard to remember the specifics :sweat_smile:

2025-01-29 20:30 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +  ) {
We have to get this in asap since it's blocking a lot of other issues, so I'll make a ticket to refactor all places using this pattern and change it to the way you mentioned. That work?

2025-01-29 20:42 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +            subtitle={""}
Like I said to James.. This is just a [placeholder page](https://github.com/GCTC-NTGC/gc-digital-talent/issues/12236) at the moment so we didn't receive any titles when it was built.

2025-01-29 20:51 UTC, mnigh commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +            subtitle={""}
subtitle is an optional prop so it can be omitted.
```suggestion
```

2025-01-29 21:08 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +          <SEO title={""} description={""} />
The whole page is hidden in the route, so we just need to make sure this is filled in after.

2025-01-29 21:28 UTC, yonikid15 commented on packages/ui/src/components/Well/Well.tsx
> +export type WellColor = Color | "default";
This is fixed by [9b1511d](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/9b1511d6b8d9bc0f10b7b18e69d161231a2814c4)

2025-01-29 21:29 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +          <SEO title={""} description={""} />
You know it's all good I removed it [e92683d](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/e92683dd7dd8a884929c71c0e2e3f2549454a7f9)

2025-01-29 21:30 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +    isDraftStatus ||
Fixed in [51cf495](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/51cf495516a1b728326d2427eda87c444d0702ed)

2025-01-29 21:31 UTC, yonikid15 commented on packages/ui/src/index.tsx
> +import Well, { WellProps, WellColor } from "./components/Well";
Changed in [d0158a5](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/d0158a5dede6229a8a5ec42b248ce3b817d869b8)

2025-01-29 21:32 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessPreviewList.tsx
> +}) => {
Changed in [b7e4eb3](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/b7e4eb30269e46bbc3948d9cbf267c7c15a45111)

2025-01-29 21:32 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessPreviewList.tsx
> +  recruitmentProcessQuery: ReviewRecruitmentProcessPreviewListFragment;
Changed in [b7e4eb3](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/b7e4eb30269e46bbc3948d9cbf267c7c15a45111)

2025-01-29 21:33 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +  const application = applicationQuery;
Changed in [b107fc6](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/b107fc6b2eec3d0bb76c0655b4b138371675889a)

2025-01-29 21:33 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +  applicationQuery: ReviewApplicationPreviewListFragment;
Changed in [b7e4eb3](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/b7e4eb30269e46bbc3948d9cbf267c7c15a45111)

2025-01-29 21:33 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +      }
Changed in [d3df6a8](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/d3df6a87e7ff109b65f0f9d03590c960f09407b5)

2025-01-29 21:35 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +            subtitle={""}
Removed in [fa32530](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/fa325300416b98b5bd79f99d42db3d568cdf158a)

2025-01-29 21:36 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +        {intl.formatMessage(commonMessages.removed)}{" "}
Fixed in [74f9438](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/74f94387d46c080ee8c94ee18897bdb729dcdacc)

2025-01-29 21:36 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +              timeZone: "Canada/Pacific",
Yup fixed in [33de8ab](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/33de8ab0c0cddbced251c5a5ae1cd8122902367e)

2025-01-29 21:37 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +  ) {
@mnigh Is something confusing?

2025-01-29 21:38 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +}) => {
Changed in [74f9438](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/74f94387d46c080ee8c94ee18897bdb729dcdacc)

2025-01-29 21:38 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +        {intl.formatMessage(commonMessages.awarded)}{" "}
Changed in [74f9438](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/74f94387d46c080ee8c94ee18897bdb729dcdacc)

2025-01-29 21:38 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +  return null;
Changed in [74f9438](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/74f94387d46c080ee8c94ee18897bdb729dcdacc)

2025-01-29 21:38 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +}) => {
Changed in [74f9438](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/74f94387d46c080ee8c94ee18897bdb729dcdacc)

2025-01-29 21:39 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +              },
Yup removed in [e4d72f5](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/e4d72f517847ac4ee139b4ae04ac9a0fd1439bfe)

2025-01-29 21:39 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +            subtitle={""}
I removed this and the other title and subtitle in the SEO

2025-01-29 21:40 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +  const applications = getFragment<ReviewApplicationPreviewListFragment>(
Changed in [b7e4eb3](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/b7e4eb30269e46bbc3948d9cbf267c7c15a45111)

2025-01-29 22:14 UTC, yonikid15 commented on apps/web/src/messages/talentRequestMessages.ts
> +    id: "cR8L3T",
I moved this and all the ones mentioned below into commonMessages :+1:  (expect for the formMessages.submitted)
Changed in [d28426e](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/d28426eb3a76c706ea6a0768a74f84f3d4f909a0)

2025-01-30 15:13 UTC, esizer requested changes
I have not done a full accessibility review yet but I have a strong feeling that there will be plenty of problems surrrounding the applications appears twice on the page and attempting to link to them when a page does not exist. 

I am not sure how we want to proceed though :cry:

2025-01-30 15:13 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +      }
I see localzied was added but `en` and `fr` were not removed. If we need those then it isn't much benefit to do `localized` :sweat_smile: 

If not, then they should be removed so we don;t over fetch

2025-01-30 15:32 UTC, mnigh reviewed
The copy issues I commented on have been resolved.

2025-01-30 15:59 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessPreviewList.tsx
> +  recruitmentProcessQuery: ReviewRecruitmentProcessPreviewListFragment;
Oh missed that! Thanks :+1:

2025-01-31 00:08 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +        }}
Oh ya it's for this requirement:
- For Successful, there is a "View recruitment process" button/link that **Closes the dialog**, **Expands the processes tool**, and **focuses the related process**

There's a ticket that would build on top of this to open the accordion then focus on the related process. However, I remember we talked (awhile ago now :laughing:) that this would most likely present an be accessibility issue. 

If we remove this then we would have to remove the button from the dialog as well (it appears on **successful** applications). I'll need to talk to the designers about that.

2025-01-31 00:33 UTC, JamesHuf requested changes
I found a few more things needing looked at.

2025-01-31 00:33 UTC, JamesHuf commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessPreviewList.tsx
> +              defaultMessage: "You don't have any applications at the moment.",
It looks like the null state copy for this is different in the designs.
![image](https://github.com/user-attachments/assets/4a03b1bb-780a-4bd1-8c21-5e620a04e8e9)

2025-01-31 00:33 UTC, JamesHuf commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +    ? differenceInDays(Date.now(), parseDateTimeUtc(pool.closingDate)) < 3
This doesn't seem to be calculating correctly - I think you need to reverse the parameters to differenceInDays.
![image](https://github.com/user-attachments/assets/a781baa5-eed6-4a05-8f91-d88a3187115d)

2025-01-31 00:33 UTC, JamesHuf commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +              {pool.location?.localized}
It looks like pools considered remote won't display anything for location.
![image](https://github.com/user-attachments/assets/be38814d-d8a2-4c88-be8a-29ddd8e43c86)

2025-01-31 00:39 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +    ? differenceInDays(Date.now(), parseDateTimeUtc(pool.closingDate)) < 3
Haha ya I saw that too, let me know if this is good [2797ae0](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/2797ae0ec0795e3a4381dbf51e202d15142d31f7)

2025-01-31 00:40 UTC, JamesHuf commented
We ended up [removing](https://github.com/GCTC-NTGC/gc-digital-talent/issues/12164#issuecomment-2587867547) the suspended status chip and qualified applications now appear the same regardless of their expiry date. Is there any point in continuing to display the expiry date to applicants?
![image](https://github.com/user-attachments/assets/943c5f4f-c1ae-45ee-8c28-76ded53c9af2)

2025-01-31 00:43 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +      }
I thought they were required :sweat_smile: Fixed in [eabc236](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/eabc2365100916752a224bf0c454f02bad65d8ea)

2025-01-31 00:44 UTC, JamesHuf commented
We rolled back the ability for candidates to (un)suspend their hired applications. This section should probably be removed in that situation.
![image](https://github.com/user-attachments/assets/a3812547-99b8-434f-9dee-7281dcd87cf9)

2025-01-31 00:44 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +export const ReviewApplicationPreviewList_Fragment = graphql(/* GraphQL */ `
Fixed in [988d3bb](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/988d3bb22efa2d2da6544b633783b3c70a3f7ab5)

2025-01-31 00:45 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessPreviewList.tsx
> +  recruitmentProcessQuery: ReviewRecruitmentProcessPreviewListFragment;
Fixed in [988d3bb](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/988d3bb22efa2d2da6544b633783b3c70a3f7ab5)

2025-01-31 00:45 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +  applicationQuery: ReviewApplicationPreviewListFragment;
Fixed in [988d3bb](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/988d3bb22efa2d2da6544b633783b3c70a3f7ab5)

2025-01-31 00:45 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +  const applications = getFragment<ReviewApplicationPreviewListFragment>(
Fixed in [988d3bb](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/988d3bb22efa2d2da6544b633783b3c70a3f7ab5)

2025-01-31 00:45 UTC, yonikid15 commented on apps/web/src/utils/poolCandidate.ts
> +
Fixed in [3b7254d](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/3b7254dc35badd216db5034b2d8a549e0d5847fc)

2025-01-31 00:46 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/StatusSummary.tsx
> +      <p data-h2-font-weight="base(bold)" data-h2-padding-bottom="base(x.5)">
Changed in [92634d8](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/92634d83c6f09e70759bdd0d6a0117f85a8073ca)

2025-01-31 00:47 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +              }
Good catch! Fixed in [2797ae0](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/2797ae0ec0795e3a4381dbf51e202d15142d31f7)

2025-01-31 00:48 UTC, JamesHuf commented
The design shows a different icon for draft applications (and for recruitment processes). Is there a reason you aren't doing this?
![image](https://github.com/user-attachments/assets/ce625ac2-7442-4e04-9639-b29c9c1f1382)

2025-01-31 00:48 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessPreviewList.tsx
> +export const ReviewRecruitmentProcessPreviewList_Fragment = graphql(
Removed in [988d3bb](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/988d3bb22efa2d2da6544b633783b3c70a3f7ab5)

2025-01-31 13:48 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +        }}
I'm not sure that you described is possible which is the issue. Regardless of all that though, we need to change the cards to differentiate between Applications and Recruitment processes. 

Right now, the buttons are identical even though they open different dialogs.

2025-01-31 13:51 UTC, esizer commented on apps/web/src/utils/poolCandidate.ts
> +
If we need the type, can we change the case of the object to avoid name collisions?

```tsx
const applicationStatus | APPLICATION_STATUS = { };

type ApplicationStatus = {};
```

2025-01-31 14:23 UTC, mnigh commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +  ) {
> @mnigh Is something confusing?

If it will take a long time to do this refactor, sure, push it to another issue but if @esizer has a solution already, why not do it right the first time instead of pushing a slower solution?

2025-01-31 23:41 UTC, vd1992 commented
`ApplicantDashboardPage` is not a stub anymore
The placeholders can be left until https://github.com/GCTC-NTGC/gc-digital-talent/issues/10772 probably, at which point we can make sure links/breadcrumbs/titles are correctly populated

2025-02-03 15:24 UTC, brindasasi commented
> We rolled back the ability for candidates to (un)suspend their hired applications. This section should probably be removed in that situation. ![image](https://private-user-images.githubusercontent.com/49166751/408354551-a3812547-99b8-434f-9dee-7281dcd87cf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg1OTYwOTQsIm5iZiI6MTczODU5NTc5NCwicGF0aCI6Ii80OTE2Njc1MS80MDgzNTQ1NTEtYTM4MTI1NDctOTliOC00MzRmLTlkZWUtNzI4MWRjZDg3Y2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjAzVDE1MTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYzE2MzZjYTMzNjAwY2VkMzg2NWNhZWY5YzRkZjQwMmEwMWQ1OWQ1OWJiMTE1YjkyZmI0YjIzYWU1OGQxY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u9Yg7iA5ldhMw6Vhm062Yc9qYKNNF1ppjZQKAgakMVo)

@JamesHuf Could you connect the relevant PR  you are talking about? I'm confused as I thought we rollbacked only for placed candidates and  Qualified Available should function as before. I could be wrong .

2025-02-03 16:21 UTC, mnigh commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessPreviewList.tsx
> +      isQualifiedFinalDecision(recruitmentProcess.finalDecision?.value),
see: https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/13074982240/job/36484825551#step:11:91

2025-02-03 16:22 UTC, mnigh commented
@yonikid15 Missing translations and has merge conflicts with `main` branch that need to be resolved.

2025-02-03 16:48 UTC, JamesHuf commented
> @JamesHuf Could you connect the relevant PR you are talking about? I'm confused as I thought we rollbacked only for placed candidates and Qualified Available should function as before. I could be wrong .

I think you're right on that and it's what I was referring to. This was still designed for users to suspend their **placed** candidates.

2025-02-03 18:51 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessPreviewList.tsx
> +              defaultMessage: "You don't have any applications at the moment.",
Fixed in [91a34bc](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/91a34bcc8e0e630bf731050ab7e818c47aba6f1e)

2025-02-03 18:54 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +              {pool.location?.localized}
Fixed in [6faad8c](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/6faad8ce0d342369bcbff089b97c7905dce2f780)

2025-02-03 18:58 UTC, mnigh commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessPreviewList.tsx
> +                            "{poolName} <hidden>recruitment process</hidden>",
Space should be in hidden text: `{poolName}<hidden> recruitment process</hidden>`

2025-02-03 18:58 UTC, mnigh commented on apps/web/src/lang/fr.json
> +    "defaultMessage": "<hidden>Processes de recrutement pour</hidden> {poolName}",
Space should be in hidden text: `<hidden>Processes de recrutement pour </hidden>{poolName}`

2025-02-03 19:40 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessPreviewList.tsx
> +                            "{poolName} <hidden>recruitment process</hidden>",
Nice catch! Fixed in [cd98a19](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/cd98a19c3e3ee182c0b81d16570dc25c194c723a)

2025-02-03 19:40 UTC, yonikid15 commented on apps/web/src/lang/fr.json
> +    "defaultMessage": "<hidden>Processes de recrutement pour</hidden> {poolName}",
Nice catch! Fixed in [cd98a19](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/cd98a19c3e3ee182c0b81d16570dc25c194c723a)

2025-02-03 20:20 UTC, JamesHuf commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +    ? differenceInDays(Date.now(), parseDateTimeUtc(pool.closingDate)) < 3
I'm not sure this worked - in the list deadlines never appear in red even when within 3 days
![image](https://github.com/user-attachments/assets/b4014511-51f8-42d3-b43b-62ed234a7647)
and in the dialog for expired applications it shows "Received" instead of the deadline.
![image](https://github.com/user-attachments/assets/c026b49b-c611-4df9-8201-17422b3e5e34)

2025-02-03 20:44 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +    ? differenceInDays(Date.now(), parseDateTimeUtc(pool.closingDate)) < 3
@JoshBeveridge in the first image, is the "Deadline" date supposed to appear in red? I don't see it in the design.

2025-02-03 22:00 UTC, mnigh commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +import { differenceInDays } from "date-fns/differenceInDays";
`differenceInDays` is defined but never used.
```suggestion
```

2025-02-04 00:07 UTC, JamesHuf reviewed
I'm happy enough with this now.

2025-02-04 14:30 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +import { differenceInDays } from "date-fns/differenceInDays";
Fixed in [5ddc989](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/5ddc989c3b33933fccfba9a2af5672e6b429b038)

2025-02-04 14:31 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessPreviewList.tsx
> +      isQualifiedFinalDecision(recruitmentProcess.finalDecision?.value),
Fixed in [078eac4](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/078eac46db2fce25a7adb6689e87d4d264cade38)

2025-02-04 14:38 UTC, esizer requested changes

2025-02-04 14:38 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +        <PreviewList.Button label={poolName} />
We got the title for the card updated with the additional context. However, we need to replicate that here and possibly toss an action word in. The trigger for the dialog is just as important as the heading to distinguish it from the other items on the page.

2025-02-04 14:38 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessDialog.tsx
> +          label={poolName}
Same thing about adding the additional context for the button here.

2025-02-04 14:38 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +                  ? getClassificationName(pool?.classification, intl)
We need to add something in here for abbreviations. Right now it reads as the word "it" for IT instead of I-T separately.

2025-02-04 14:38 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessDialog.tsx
> +            );
Since you can update multiple different items on this page, I tihnk we need to be specific in the toast. "...remove from search results for {title}."

2025-02-04 14:38 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +                            "<hidden>Application for </hidden>{poolName}",
I don't think you can fix this and I don't expect you to even attempt it here since it is way out of scope. But I just need to highlight that our hidden text is cuaisng issues in both voiceover and NVDA.

This reads in NVDA as such:

 - Heading level 4, application for
 - Heading level 4, {poolName}
 
 This is incredibly confusing since it seems as though there are two separate headings here when there are not. I feel like we need to reduce our usage of hidden text where possible if this is going to continute to be an issue in 2/4 most commonly used screen readers 👎

2025-02-04 16:36 UTC, NienkeBr commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +                      />
Continue application<hidden> for {processName}</hidden>.
Poursuivre la demande<hidden> pour {processName}</hidden>

2025-02-04 16:39 UTC, NienkeBr commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessDialog.tsx
> +              "Check out the details of a recruitment process you belong to and update your interest in receiving jobs.",
"... and update your interest in receiving job offers."
French doesn't need to be updated.

2025-02-05 12:51 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +  }
Good catch! I removed these

2025-02-05 12:52 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +  }
Good catch! I removed these

2025-02-05 12:56 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +        }}
Yup! Removed in [a7dfe2a](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/a7dfe2a6b8795427db6d6393231182535af536b2)

2025-02-05 12:58 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +                    data-h2-font-weight="base(normal)"
The number is supposed to be a but fainter in color and weight. This is the [dialog](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12667/files#diff-54dfe204f082357c774d5af99107dcb650c8f8d17785228d8beaee1408724bedL254-L264) we had for the talent requests that was approved by Josh, with the same design. However, it looks like you found a new bug with the dark theme not working when focused.

2025-02-05 13:00 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +                <Accordion.Content data-h2-margin-bottom="base(-x.5)">
The accordion **content** has extra padding at the bottom so we need to negate it. The negative spacing is only needed when it's open.

2025-02-05 13:03 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +          {applications.map((application) => {
That's a good question. We weren't sorting them in the "Track your applications" section. However, this should be done in a separate issue. These new statuses don't match up with the `pool_candidate_status` weights, so we can't use them to determine the order. 

Do we have a sort order in mind @JoshBeveridge ?

2025-02-05 13:05 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessDialog.tsx
> +              {pool.workStream?.name?.localized}
Good catch, I missed those! Fixed in [a7dfe2a](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/a7dfe2a6b8795427db6d6393231182535af536b2)

2025-02-05 13:06 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +              <Separator data-h2-margin="base(0)" />
I think we should keep for now (and make it decorative). It separates the two lists, making it easier to read the page for UAT testing. When the dashboard issue is worked on, I'm sure they'll be able to notice and remove two lines :stuck_out_tongue_closed_eyes: .

2025-02-05 13:13 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessDialog.tsx
> +      })
What's the edge case? So I can test it

2025-02-05 13:15 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessPreviewList.tsx
> +  ).filter(
I believe `getFragment` for an array always returns an array, so it would just filter an empty array. However I can check if it's null just in case [a7dfe2a](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/a7dfe2a6b8795427db6d6393231182535af536b2)

2025-02-05 13:16 UTC, yonikid15 commented on apps/web/src/utils/poolCandidate.ts
> +};
Ya forsure! Moved to classification.ts and used in PoolCard in [a7dfe2a](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/a7dfe2a6b8795427db6d6393231182535af536b2)

2025-02-05 13:16 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
> +            })
Yup, I accidentally removed that one :sweat_smile: I added it back [a7dfe2a](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/a7dfe2a6b8795427db6d6393231182535af536b2)

2025-02-05 13:18 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +          <p data-h2-font-weight="base(bold)">
I saw other parts of the site use `data-h2-margin=base(x.5)"`. I used that here to keep things consistent.

2025-02-05 13:18 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessPreviewList.tsx
> +          <p data-h2-font-weight="base(bold)">
I added the data-h2-margin=base(x.5)"` margin here as well.

2025-02-05 13:21 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +                  ? getClassificationName(pool?.classification, intl)
Is this the only page it happens on? Because we use this function on a few other pages (e.g. JobPosteTemplate) I just want to know if I have a unique case or not.

2025-02-05 13:21 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessDialog.tsx
> +            );
@NienkeBr is the current copy okay? Or should we change it to what Eric suggested?

2025-02-05 13:24 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +                        <li key={skill?.id}>{skill?.name.localized}</li>
To keep things easy and move them forward, you could use a flat map here. I think the following should work:

```tsx
const skills = unpackMaybes(poolSkills.flatMap(({ skill }) => skill));
```

2025-02-05 13:27 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessDialog.tsx
> +      })
An unexpected error in the server where a response is returned. It might be difficult to test since it is an edge case. 

We should generally be checking for success rather than the inverse so we fallback to an error if we do not get expected results.

2025-02-05 13:30 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +              <Separator data-h2-margin="base(0)" />
Huh, okay. I assumed we'd only start UAT testing once the entire feature was complete :sweat_smile:

2025-02-05 15:21 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +              <Separator data-h2-margin="base(0)" />
I'm pretty sure Brinda wanted to test it if it got in the last release :shrug:

2025-02-05 15:24 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +                    data-h2-color="base(black.light)"
@JoshBeveridge can we change the color of the (*number_of_skills*) to black to avoid having to fix the bug above?

2025-02-05 15:31 UTC, JoshBeveridge commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +          {applications.map((application) => {
@yonikid15 Great question, sorry I hadn't specified that earlier. At least for this dashboard widget, applications should be sorted by status in the order those statuses occur:

* Drafts (closest deadline first)
* Received
* Under review
* Application reviewed
* Under assessment
* Qualified in process
* Unsuccessful
* Ineligible
* Expired

2025-02-05 15:35 UTC, JoshBeveridge commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +                        formatString: "PPP",
@yonikid15 My only hesitation here is that we can't nest that giant block of text behind a click, because we're already inside a preview dialog... What if we append something like

```
Deadline to apply
August 5th, 2025 (11:59PM PST)
```

2025-02-05 15:37 UTC, JoshBeveridge commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +                    data-h2-color="base(black.light)"
@yonikid15 Not sure what you mean by bug in this case 🤔 however you should be able to target the `<span>` using `:children` on whatever element is receiving focus to change the `(2)` to black

2025-02-05 15:39 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +          {applications.map((application) => {
Should this be done in this PR or passed as a new requirement in #10788 ? I'm okay with passing it on

2025-02-05 16:34 UTC, petertgiles commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +                        timeZone: "Canada/Pacific",
Yoni confirmed this is done.

2025-02-05 16:40 UTC, petertgiles commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +                    data-h2-font-weight="base(normal)"
This will be split off

2025-02-05 16:41 UTC, petertgiles commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +                    data-h2-font-weight="base(normal)"
same font bug

2025-02-05 16:42 UTC, petertgiles commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +                <Accordion.Content data-h2-margin-bottom="base(-x.5)">
I'll make an issue to review this.

2025-02-05 16:49 UTC, petertgiles commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +                        formatString: "PPP",
I will push this to next issue

2025-02-05 16:57 UTC, petertgiles commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +                  ? getClassificationName(pool?.classification, intl)
I will move this to the polish ticket

2025-02-05 17:03 UTC, petertgiles commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +                            "<hidden>Application for </hidden>{poolName}",
I'll bring this up in retro again.

2025-02-05 17:54 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +        <PreviewList.Button label={poolName} />
Added in here [e9fa102](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/e9fa10262e89daca332eefdd9ec54cc02242e5e8)

2025-02-05 17:54 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessDialog.tsx
> +          label={poolName}
Added in here [e9fa102](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/e9fa10262e89daca332eefdd9ec54cc02242e5e8)

2025-02-05 17:55 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessDialog.tsx
> +      })
Fixed in [e9fa102](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/e9fa10262e89daca332eefdd9ec54cc02242e5e8)

2025-02-05 17:55 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessDialog.tsx
> +              "Check out the details of a recruitment process you belong to and update your interest in receiving jobs.",
Added in [e9fa102](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/e9fa10262e89daca332eefdd9ec54cc02242e5e8)

2025-02-05 17:55 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +                      />
Added in [e9fa102](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12366/commits/e9fa10262e89daca332eefdd9ec54cc02242e5e8)

2025-02-05 17:55 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +            >
Outdated

2025-02-05 17:55 UTC, yonikid15 commented on apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
> +              <Separator />
Outdated

2025-02-05 18:01 UTC, petertgiles commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +                    data-h2-font-weight="base(normal)"
https://github.com/GCTC-NTGC/gc-digital-talent/issues/12698

2025-02-05 18:01 UTC, petertgiles commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +                    data-h2-font-weight="base(normal)"
https://github.com/GCTC-NTGC/gc-digital-talent/issues/12698

2025-02-05 18:03 UTC, petertgiles commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +          {applications.map((application) => {
Added to the AC of #10788

2025-02-05 18:05 UTC, petertgiles commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +                        formatString: "PPP",
https://github.com/GCTC-NTGC/gc-digital-talent/issues/12699

2025-02-05 18:07 UTC, petertgiles commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
> +                  ? getClassificationName(pool?.classification, intl)
https://github.com/GCTC-NTGC/gc-digital-talent/issues/12699

2025-02-05 18:08 UTC, petertgiles commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessDialog.tsx
> +            );
https://github.com/GCTC-NTGC/gc-digital-talent/issues/12699

2025-02-05 18:09 UTC, JamesHuf approved these changes
I think this is good to go now :rocket:

2025-02-05 19:03 UTC, petertgiles commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +                        <li key={skill?.id}>{skill?.name.localized}</li>
Added to https://github.com/GCTC-NTGC/gc-digital-talent/issues/12699

2025-02-06 13:00 UTC, esizer approved these changes
I have noted another possible item for the next ticket but otherwise it looks good ot move ahead to unblock the other stuff now :+1:

2025-02-06 13:00 UTC, esizer commented on apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
> +        />
One for the polish ticket. Should we do the fallback in the argument so the button label would be "Application for not found" instead?

2025-02-06 15:06 UTC, merged