[Feature] Increases classification level options
GCTC-NTGC/gc-digital-talent pull request #12399
Opened 2024-12-31 18:53 UTC by mnigh

🤖 Resolves #12248.

## 👋 Introduction

This PR increases classification level options and accounts for the absence or presence of a leading zero in the levels.

## 🧪 Testing

Coming soon.

2025-01-04 00:02 UTC, JamesHuf requested changes
Looks good! I just found a couple more places needing tweaked.

2025-01-04 00:02 UTC, JamesHuf commented on apps/web/src/utils/nameUtils.tsx
>            <span aria-label={splitAndJoin(stringifyText.replace("-0", ""))}>
This is removing the colon in aria labels for single digit classifications but leaving it for double digit ones.
For example "IT-03" => "I T 3" as opposed to "IT-19" => "I T - 1 9".

2025-01-04 00:03 UTC, JamesHuf commented
![image](https://github.com/user-attachments/assets/f77bacae-fc4d-43a5-8d52-19f934a02d73)
Levels not sorted on the Employee Information page (during registration).

2025-01-04 00:04 UTC, JamesHuf commented
![image](https://github.com/user-attachments/assets/6ef0b1f1-c64c-473d-a46b-4e0dc27ee040)
"IT-**0**19" x2 on the Browse Jobs page.

2025-01-06 15:55 UTC, mnigh commented on apps/web/src/utils/nameUtils.tsx
>            <span aria-label={splitAndJoin(stringifyText.replace("-0", ""))}>
3ecdaea8c77cc8a8ca2dd0df2ff30e14714288ac

## Screenshots
<img width="638" alt="Screen Shot 2025-01-06 at 10 51 21" src="https://github.com/user-attachments/assets/12a74759-67ff-4d3d-bb8f-c351a01c186d" />
<img width="718" alt="Screen Shot 2025-01-06 at 10 51 36" src="https://github.com/user-attachments/assets/f0dae420-4fed-444b-b666-14975138362d" />

2025-01-06 15:56 UTC, mnigh commented
> Levels not sorted on the Employee Information page (during registration).

fa6195a8a240929e4315ffb6948c98ccfd8179ae

## Screenshot
<img width="1162" alt="Screen Shot 2025-01-06 at 10 02 34" src="https://github.com/user-attachments/assets/7407d4c3-0a44-4e40-8b41-5a985451adf2" />

2025-01-06 15:57 UTC, mnigh commented
> "IT-**0**19" x2 on the Browse Jobs page.

3c83c58224e058391d6292c3bc7218724ddc3e73

## Screenshot

<img width="638" alt="Screen Shot 2025-01-06 at 10 51 21" src="https://github.com/user-attachments/assets/5df98d8f-bc1a-46c8-b2b2-0c67273c9f49" />

2025-01-06 18:13 UTC, mnigh commented
Created https://github.com/GCTC-NTGC/gc-digital-talent/issues/12424 for possible related refactoring for the future.

2025-01-06 20:32 UTC, JamesHuf approved these changes
You've gotten everything I can find! :+1:

2025-01-07 14:02 UTC, merged