Allow clean form submission for validation
GCTC-NTGC/gc-digital-talent pull request #1273
Opened 2021-12-03 14:59 UTC by petertgiles

Closes #1201

Allows the submit button on a form to be used even if the form is clean.  So even if no fields have been touched the validation messages will appear and the focus will jump to a field with a validation error.

2021-12-03 19:27 UTC, yonikid15 requested changes
Nice job finding the reason why it stopped validating without focusing on an input. However, I noticed that the text changes to "Submitted" when you initially click on it. I'm still thinking of solution to fix that...

2021-12-03 19:44 UTC, petertgiles commented
> the text changes to "Submitted" when you initially click on it

Yeah, I noticed that too and thought it was weird but wasn't sure if that was the way it was supposed to be.  OK, I'll assume we don't want it that way and I'll update it. 😁

2021-12-06 19:01 UTC, yonikid15 approved these changes
LGTM 👍

2021-12-06 19:02 UTC, yonikid15 approved these changes

2021-12-06 19:02 UTC, merged