Feature - Candidate count unit tests
GCTC-NTGC/gc-digital-talent pull request #1594
Opened 2021-12-31 14:11 UTC by yonikid15

Closes #500 

Creates tests for the countPoolCandidates query. I still need to fix the pool filter tests atm. However, if someone has any better suggestions on the rest of the code let me know.

2021-12-31 19:54 UTC, petertgiles requested changes
This is very cool!  I didn't know Lighthouse could a test API like this.

I've suggested a few bugfixes and copypasta corrections below.

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +use GraphQL\Type\Definition\EnumType;
```suggestion
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +// use PHPUnit\Framework\TestCase;
```suggestion
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +      'id' => 'new_cmo_asset'
```suggestion
      'key' => 'new_cmo_asset'
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +        'cmoAssets' => [[ 'id' => 'new_cmo_asset' ]],
```suggestion
        'cmoAssets' => [[ 'key' => 'new_cmo_asset' ]],
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +        'cmoAssets' => [[ 'id' => 'unknown_id' ]],
```suggestion
        'cmoAssets' => [[ 'key' => 'unknown_id' ]],
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    $id = strtolower(preg_replace('/\s+/', '_', 'test'));
```suggestion
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +        'pools' => [[ 'id' => $id ]],
```suggestion
        'pools' => [[ 'id' => $pool['id'] ]],
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +        'pools' => [[ 'id' => 'unknown_id' ]],
```suggestion
        'pools' => [[ 'id' => '00000000-0000-0000-0000-000000000000' ]],
```
Needs to be a valid UUID to run

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Assert query with unknown operationalRequirement filter will return 0
```suggestion
    // Assert query with filter set to false will return all candidates
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Create new operationalRequirement and attach to 2 new pool candidates.
```suggestion
    // Create one new candidate for each EmploymentEquity filter
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Assert query will with no operationalRequirements filter will return all candidates
```suggestion
    // Assert query will with no EmploymentEquity filter will return all candidates
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Assert query with operationalRequirement filter will return correct candidate count
```suggestion
    // Assert query with EmploymentEquity filter will return correct candidate count
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Assert query with operationalRequirement filter will return correct candidate count
```suggestion
    // Assert query with EmploymentEquity filter will return correct candidate count
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Assert query with operationalRequirement filter will return correct candidate count
```suggestion
    // Assert query with EmploymentEquity filter will return correct candidate count
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Assert query with operationalRequirement filter will return correct candidate count
```suggestion
    // Assert query with EmploymentEquity filter will return correct candidate count
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Assert query with unknown operationalRequirement filter will return 0
```suggestion
    // Assert query with all EmploymentEquity filters set to false will return all candidates
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Create new operationalRequirement and attach to 2 new pool candidates.
```suggestion
    // Create new LanguageAbility and attach to 3 new pool candidates.
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Assert query will with no operationalRequirements filter will return all candidates
```suggestion
    // Assert query will with no LanguageAbility filter will return all candidates
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Assert query with operationalRequirement filter will return correct candidate count
```suggestion
    // Assert query with LanguageAbility filter will return correct candidate count
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    ]);
```suggestion
```
Duplicate test

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Assert query with operationalRequirement filter will return correct candidate count
```suggestion
    // Assert query with LanguageAbility filter will return correct candidate count
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Assert query with operationalRequirement filter will return correct candidate count
```suggestion
    // Assert query with LanguageAbility filter will return correct candidate count
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Assert query with operationalRequirement filter will return correct candidate count
```suggestion
    // Assert query with a null LanguageAbility filter will return no candidates
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Create new operationalRequirement and attach to 2 new pool candidates.
```suggestion
    // Create 2 new pool candidates for TELEWORK.
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +
```suggestion
    // Create 5 new pool candidates for ONTARIO.
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Assert query will with no operationalRequirements filter will return all candidates
```suggestion
    // Assert query will with no WorkRegion filter will return all candidates
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Assert query with operationalRequirement filter will return correct candidate count
```suggestion
    // Assert query with WorkRegion filter will return correct candidate count
```

2021-12-31 19:54 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +    // Assert query with unknown operationalRequirement filter will return 0
```suggestion
    // Assert query with empty WorkRegion filter will return 0
```

2022-01-04 13:46 UTC, petertgiles requested changes
I was thinking about this over the weekend.  Would it be possible to add a test for the "match by mapping classification to salary" logic from PR #1195?

2022-01-04 13:48 UTC, petertgiles commented on api/tests/PoolCandidateTest.php
> +      'group' => 'CS',
It might be better to create control classifications for testing that are less likely to be generated by the faker factory, like ZZ or something.

2022-01-04 20:29 UTC, yonikid15 commented
> I was thinking about this over the weekend. Would it be possible to add a test for the "match by mapping classification to salary" logic from PR #1195?

Good Idea!

2022-01-05 15:06 UTC, petertgiles approved these changes
I love it.  Great work! 💪

2022-01-05 15:06 UTC, merged