created SkillFamilyPage and SkillFamilyTable
GCTC-NTGC/gc-digital-talent pull request #1800
Opened 2022-01-19 23:09 UTC by JamesHuf

Created SkillFamilyPage for #1681

2022-01-20 14:04 UTC, petertgiles requested changes
Wow, turned this one around fast!
Could you please add a storybook story for the new table?  That might require you to make a fake data generator as well.

2022-01-20 14:54 UTC, yonikid15 requested changes
Great work James 👍. Just found one typo that I made a suggestion for.

2022-01-20 14:54 UTC, yonikid15 commented on admin/resources/js/components/PoolDashboard.tsx
> +      key="skill-family"
```suggestion
      key="skill-families"
```

2022-01-20 19:13 UTC, JamesHuf commented on admin/resources/js/components/PoolDashboard.tsx
> +      key="skill-family"
Thanks! It's fixed now.

2022-01-21 21:46 UTC, petertgiles commented
Heads up, I merged main for your branch.

2022-01-24 13:47 UTC, petertgiles requested changes
Nice, this is looking great!  Just a few small things to check.  Also, I see that description is not populating properly but I see that's an issue with the seeder.  It seems to work fine in the storybook story.  I'll submit an issue for that.

2022-01-24 13:47 UTC, petertgiles commented on frontend/admin/resources/js/api/skillFamilyOperations.graphql
> +  skillFamilies {
The SkillFamily model has a `key` field that needs to be returned as well.

2022-01-24 13:47 UTC, petertgiles commented on frontend/admin/resources/js/components/skillFamily/SkillFamilyTable.tsx
> +        accessor: "category",
I think this should be localized as well.  It's an enum so check the localizedstrings files for examples.

2022-01-24 21:45 UTC, petertgiles approved these changes
I merged in Tristan's French toggle PR which has caused a conflict here.  Everything looks good to me.  The page is crashing due to that seeder issue but I could verify it works on my system after fixing it.  Nice work! 👍

2022-01-24 21:49 UTC, merged

2022-01-24 22:02 UTC, petertgiles commented
Fix for the seeder issue: https://github.com/GCTC-NTGC/gc-digital-talent/pull/1862