Feature/1534 accordion component - version 2
GCTC-NTGC/gc-digital-talent pull request #1966
Opened 2022-02-01 16:00 UTC by brindasasi

2022-02-02 15:39 UTC, tristan-orourke requested changes
The component and stories look great! However, something seems to have gone wrong with merging frontend/common/package.json. A lot of dependencies have been rolled back or removed entirely. I think you can replace your file with the version in main.

2022-02-02 15:40 UTC, brindasasi commented
> The component and stories look great! However, something seems to have gone wrong with merging frontend/common/package.json. A lot of dependencies have been rolled back or removed entirely. I think you can replace your file with the version in main.

yeah .. I noticed that as well.. I would revert this file.

2022-02-02 20:40 UTC, tristan-orourke approved these changes

2022-02-02 20:40 UTC, merged

2022-02-04 17:47 UTC, patcon commented
Yeow! Happy to see this merged @brindasasi. sorry for me part in the folder re-org :)