Fix outstanding JS lint issues
GCTC-NTGC/gc-digital-talent pull request #2082
Opened 2022-02-16 17:49 UTC by patcon

Resolves: https://github.com/GCTC-NTGC/gc-digital-talent/issues/2043

Depends on: https://github.com/GCTC-NTGC/gc-digital-talent/pull/1993 (requires merge first)

## To Do

- [x] auto-fix all in frontend/*
- [ ] manually fix frontend/common
- [ ] manually fix frontend/admin
- [ ] manually fix frontend/talentsearch
- [ ] enable failures on lint workflow https://github.com/GCTC-NTGC/gc-digital-talent/pull/1993

2022-02-18 15:21 UTC, patcon commented on frontend/common/.eslintrc.yml
> +      - then
Specifically this was added beyond a straight convert.

2022-02-18 16:10 UTC, patcon commented
Sorry @petertgiles, misspoke -- filed bug and "minimal bug reproduction", not bugfix (yet? on my own time perhaps)

2022-02-18 16:31 UTC, petertgiles commented
> Sorry @petertgiles, misspoke

No, this is cool.  I was wondering about that linting error assuming I just didn't understand how it was supposed to work.  Cool to see the discussion in the other thread.

2022-02-21 04:44 UTC, patcon commented on frontend/.eslintrc.yml
> +    - fixToUnknown: true
Added this to allow `npm run lint:fix` to change all `any` to `unknown`

2022-02-21 04:45 UTC, patcon commented on .github/workflows/lint.yml
>          run: npm run lint --workspaces --if-present
If we want `npm run lint` to fail if there are even any warnings, we can use this, which passed the flag through `npm run` down to `eslint`.

```suggestion
        run: npm run lint --workspaces --if-present -- --max-warnings=0
```

2022-02-21 04:49 UTC, patcon commented on frontend/admin/resources/js/types/react-table-config.d.ts
> +    V = unknown,
Not sure why this is here, but related to react-table. To ignore

```suggestion
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    V = unknown,
```
```suggestion
    V = unknown,
```

2022-02-21 04:51 UTC, patcon commented on frontend/common/src/types/utilityTypes.ts
> -type flattened = FlattenNested<test>;
All unused

2022-02-21 04:52 UTC, patcon commented on frontend/talentsearch/resources/js/components/search/SearchForm.tsx
> +  const submitDebounced = useCallback(() => {
This was required by an obscure rule. Apparently useCallback need an inline function:
https://reactjs.org/docs/hooks-reference.html#usecallback

2022-02-21 04:53 UTC, patcon commented on frontend/talentsearch/resources/js/tests/skills/SkillResults.test.tsx
> +      }}
No empty functions rule

2022-02-21 04:56 UTC, patcon commented on frontend/.eslintrc.yml
> +  ecmaVersion: 2020
Standardized all on 2020 (some were 2018)

2022-02-21 05:04 UTC, patcon commented on frontend/admin/resources/js/types/react-table-config.d.ts
> +    V = unknown,
Not sure how interfaces are working, and whether this is false positive or something real.

2022-02-21 05:16 UTC, patcon commented
Ready for review again. When I consolidated the eslint config, a bunch more errors popped up.

I dealt with all the warnings (called attention to the things that might catch your attention).

There's a suggested change above to make it so that all warnings fail the lint test. This might be annoying at first, but strikes me as maybe worthwhile. Might be simpler to correct if someone implements https://github.com/GCTC-NTGC/gc-digital-talent/issues/1869

2022-03-08 19:14 UTC, patcon commented
Wrote throwaway git-bisect script, and ran it over lunch... Figured out the first bad commit! https://gist.github.com/patcon/5cd649196e113ab74cf30255ca8164e7

2022-03-15 03:05 UTC, patcon commented
Ugh! Fixing this final errors in the morning :/
https://github.com/GCTC-NTGC/gc-digital-talent/runs/5547789383?check_suite_focus=true#step:9:33

2022-03-15 14:59 UTC, patcon commented on frontend/talentsearch/resources/js/components/search/SearchForm.tsx
> +  const submitDebounced = useCallback(() => {
I'm actually having issues with this one, specifically where it's called below context in L155 and L159

Can anyone advise on how debouncing should work here? It's new to me :)

The examples of can find for addressing the rule use [`debounce-fn`](https://github.com/sindresorhus/debounce-fn) pkg, and we use [`debouce`](https://github.com/component/debounce)

cc @tristan-orourke as author

2022-03-15 17:02 UTC, patcon commented on frontend/common/.eslintrc.yml
> +      - then
was just FYI. no action

2022-03-15 17:06 UTC, patcon commented on frontend/.eslintrc.yml
> +  ecmaVersion: 2020
fyi only. no needed actions.

2022-03-15 17:07 UTC, patcon commented on frontend/talentsearch/resources/js/tests/skills/SkillResults.test.tsx
> +      }}
fyi only. no needed actions.

2022-03-15 17:07 UTC, patcon commented on frontend/common/src/types/utilityTypes.ts
> -type flattened = FlattenNested<test>;
fyi only. no needed actions.

2022-03-15 17:07 UTC, patcon commented on .github/workflows/lint.yml
>          run: npm run lint --workspaces --if-present
Added to todos to spin out another issue. no action here

2022-03-15 17:07 UTC, patcon commented on frontend/admin/resources/js/types/react-table-config.d.ts
> +    V = unknown,
fyi only. no needed actions.

2022-03-15 20:06 UTC, petertgiles requested changes
Sorry, Pat, I think there are some things that are no bueno.  On the admin site I'm getting the "tab is unresponsive error" and on the talent site my scrolling is stuck to the top of the page.  Are these things happening for you?

2022-03-15 22:22 UTC, patcon commented
> Sorry, Pat, I think there are some things that are no bueno. On the admin site I'm getting the "tab is unresponsive" error and on the talent site my scrolling is stuck to the top of the page. Are these things happening for you?

@petertgiles Ah drats. I don't even know all the corners of the app yet, so I admit I didn't do QA testing. Plus I didn't think this would affect anything. Alas...

Might you be able to confirm reproductions in general BDD(ish) format, and I'll do a git-bisect sorta deal to figure out where things went wrong? Great simple docs here: https://cucumber.io/docs/gherkin/reference/

We could use anything we write here to kinda kick-off the version-controlling of some manual QA tests. Plus, if we ever get e2e test framework in place, we can maybe convert these to executable 🎉 

My stubs that I could use your help with to be absolutely clear what you were seeing :)

---

### Admin: Tab issue
```
Scenario: Changing tabs
  Given the following page is loaded: /some/admin/path
  And I try to click the tab "xxxxx"
  Then the tab loads
```

### Talent: scrolling
```
Scenario: Scroll on a page
  Given the following page is loaded: /some/talent/path
  And I try to scroll down with the mouse wheel
  Then the page scrolls down
```

2022-03-16 12:49 UTC, petertgiles commented
I'm afraid I don't know any BDD (yet!) but here's my general "Is the app still working?" test when I'm doing a review:

Setup
1. Check out the branch
2. Run the refresh_all script

Talent
1. Navigate to /talent
2. Expect that a non-zero candidate estimate comes up
3. Scroll to the bottom and click _Request Candidates_
4. Fill in junk data to the request form and click _Submit Request_
5. Expect the _Request created successfully!_ toast.

Admin
1. Navigate to /admin
2. If I'm logged in then click _Logout_
3. Click _Login_
4. Follow through the login procedure
5. Click the _Users_ link and expect to see the list of users
6. Click the _Edit_ link beside the first one
7. Edit the first name of the user and click _Submit_
8. Expect to see the edited name showing in the list

It's manual testing :-1: but I feel like I can catch about 90% of errors in about 2 minutes :+1:

2022-03-16 14:54 UTC, brindasasi commented
I see the same issue as talent/search stuck in page top. can't scroll down

2022-05-19 17:30 UTC, closed without merging