Feature/1806 link experiences to users/applicants
GCTC-NTGC/gc-digital-talent pull request #2124
Opened 2022-02-21 19:10 UTC by JamesHuf

Addresses #1806.

Added Applicant graphql type which contains the subset of User fields which would be relevant to an interested manager.
Also changed the user seeder to generate experiences.

2022-02-21 21:21 UTC, petertgiles commented
Wow, this is pretty impressive, James.  The implementation looks good to me.  I have a few questions about the design but these might be for you or @tristan-orourke .

- Should there be a query for Applicants implemented here?
- I'm not sure the Experience interface is very useful right now.  I'm guessing it has `details` since that's a field that's common to all experience models but I think what we really want is some kind of `displayName` that can be shown in a list or a chip or something?
- Should the experience models have `@belongsTo` a User or an Applicant?

2022-02-21 21:22 UTC, petertgiles commented
In case it's useful, here's a graphql query:
```
query {
  me {
    email
    sub
    experiences {
      id
      details
    }
    awardExperiences {
      title
      issuedBy
      awardedDate
      awardedTo
      awardedScope
      details
    }
    communityExperiences {
      title
      organization
      project
      startDate
      endDate
      details
    }
    educationExperiences {
      institution
      areaOfStudy
      thesisTitle
      startDate
      endDate
      type
      status
      details
    }
    personalExperiences {
      title
      description
      startDate
      endDate
      details
    }
    workExperiences {
      organization
      division
      startDate
      endDate
      details
    }
  }
}
```

2022-02-21 22:02 UTC, JamesHuf commented
I think the main benefit of the Experience interface is the ability to query for every experience type in a single array using something like:
`query {
  me {
    email
    sub
    experiences {
      id
      details
        ... on WorkExperience {
          role
          organization
        }
        ... on PersonalExperience {
          description
        }
    }
  }
}`

2022-02-22 13:33 UTC, petertgiles commented
> the ability to query for every experience type in a single array using something like

Oh, I didn't know about that.  Very cool!

2022-02-23 17:17 UTC, tristan-orourke commented
Like @JamesHuf showed, its already worth having the Experience interface. However, a `displayName` field is a very interesting idea @petertgiles! Each type of experience has a different way of generating its display name, as seen in #1925. Constructing it on the api side might save us from doing it in multiple places on the frontend. Think its worth making an issue for?

2022-02-24 02:36 UTC, JamesHuf commented
I've changed experiences to reference Applicants instead of Users and have added queries for applicants. Applicants can currently be queried by anyone because I'm not sure how we plan on determining access to them.

2022-02-24 13:54 UTC, petertgiles requested changes
This is looking great!  I don't mind that anyone can query the applicants right now.  At least the hooks are ready for when we want to formalize the roles and policies.  I'm going to put in an issue for it though.

It looks like the seeder for fake data is not populating `details` on `award_experiences` and `education_experiences`.  Could you please double-check those?

2022-02-24 15:30 UTC, tristan-orourke requested changes
Thanks for the prompt updates. For now, lets use the same logic on the viewApplicant and viewAnyApplicant methods as we already have on viewUser and viewAnyUser. We can make them less restrictive when we have actual manager roles.

2022-02-24 15:30 UTC, tristan-orourke commented on api/app/Policies/UserPolicy.php
> +        return true;
Should check that user is an admin

2022-02-24 15:30 UTC, tristan-orourke commented on api/app/Policies/UserPolicy.php
> +        return true;
Should check that user is an admin, OR user and model have the same id.

2022-02-24 18:27 UTC, petertgiles approved these changes

2022-02-28 17:00 UTC, brindasasi commented
@JamesHuf as discussed in the scrum , you could go ahead and merge this PR

2022-02-28 17:46 UTC, merged