Dependabot documentation
GCTC-NTGC/gc-digital-talent pull request #2177
Opened 2022-02-28 20:08 UTC by petertgiles

Based on #2152 I've tried to codify a guide to merging Dependabot PRs.  These are just my opinions 😁 so feel free to chime in.

I also created a `documentation` top level folder so feel free to comment on that too.

2022-03-01 23:16 UTC, vd1992 commented
Definitely a handy thing to have, it is a regular enough task to merit documentation. 
I think the major/minor change distinction is intuitive enough that people understand implicitly, in example, 2.2.X to 2.2.Y as opposed to 2.2.X to 3.00

Looking at the future thing, can you even automate Dependabot with something as nebulous as how big an update is? (Major vs Minor)

2022-03-02 06:55 UTC, patcon commented
> can you even automate Dependabot with something as nebulous as how big an update is?

Good point! We hadn't actually validated that it was possible before, but just found these docs which make it look simple enough:
- https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
- https://github.com/ahmadnassri/action-dependabot-auto-merge

2022-03-02 13:43 UTC, petertgiles commented
> can you even automate Dependabot with something as nebulous as how big an update is?

That's definitely something Patrick and I discussed.  My opinion is that we should look into it once E2E testing is in place and Chromatic diffs are running again.  Perhaps we could ease into it by automating just the patch updates first and then working our way up.

2022-03-07 15:38 UTC, brindasasi commented
Thanks for this documentation @petertgiles 
Regd, automation , my 2 cents , we could start from auto merging patch updates and still do major version changes with manual merge.
Once we are confident on our automated tests code coverage , we could make it fully automated.

2022-03-09 16:23 UTC, tristan-orourke approved these changes
Everyone seems happy with this 👍

2022-03-09 16:23 UTC, merged

2022-03-09 16:23 UTC, yonikid15 requested changes

2022-03-09 16:23 UTC, yonikid15 commented on documentation/dependabot.md
> +We used [Dependabot](https://github.com/dependabot) to manage the dependency updates on this project.  Currently, it is set to automatically open pull requests (PRs) every Monday for updated dependen
```suggestion
We used [Dependabot](https://github.com/dependabot) to manage the dependency updates on this project.  Currently, it is set to automatically open pull requests (PRs) every Monday for updated dependencies for NPM, Composer, Docker, and GitHub Actions. These PRs are reviewed and merged by developers on the team.  We consider this a fairly low risk activity and encourage all developers on the team to participate.
```

2022-03-09 16:23 UTC, yonikid15 commented on documentation/dependabot.md
> +We used [Dependabot](https://github.com/dependabot) to manage the dependency updates on this project.  Currently, it is set to automatically open pull requests (PRs) every Monday for updated dependen
Removed an extra space 😄

2022-03-09 16:24 UTC, yonikid15 commented on documentation/dependabot.md
> +We used [Dependabot](https://github.com/dependabot) to manage the dependency updates on this project.  Currently, it is set to automatically open pull requests (PRs) every Monday for updated dependen
Nvm 😆