Don't loss form data
GCTC-NTGC/gc-digital-talent pull request #2183
Opened 2022-03-03 16:42 UTC by petertgiles

This spike is a proposed solution to the "how do we keep our users from accidentally losing their form data" problem.

The implementation is to subscribe to form changes using the [React Hook Forms watch API](https://react-hook-form.com/api/useform/watch) and save the form values locally on every change.  The save implementation is the [useLocalStorage function from the usehooks site](https://usehooks.com/useLocalStorage/). 

The proof of concept for this spike is implemented on the Create Request form.

Do we need a "Don't navigate away!" alert?
Do we need a "Your data is being saved locally" message?

Closes #1797

2022-03-08 19:25 UTC, yonikid15 approved these changes
Looks great Peter! I'm seeing the data saved on the local storage and persisting after leaving the page and after page refresh. The only thing I noticed was the `poolCandidateFilter wasn't getting stored, since it's only watching the create request form. I'm assuming you knew that though and this was just a proof of concept for specifically the create request form? Anyways, if that's the case looks awesome, nice work!

2022-03-09 13:46 UTC, petertgiles commented
> I'm assuming you knew

Thanks Yoni, I'll check it.  I thought it was saving all form values.

2022-03-09 14:20 UTC, yonikid15 requested changes
This is just to change from aprroved to request changes

2022-03-09 14:38 UTC, petertgiles commented
> I'll check it.

OK, I took a look and this page was maybe a poor choice for a spike since it's a bit weird. 😁  The filters are not actually part of the form but come from the previous page and are displayed statically.  You can see in the `formValuesToSubmitData` function how they get stitched onto the submit object right before submission.  I think it's working as expected...  Do we need any changes?

2022-03-09 16:17 UTC, yonikid15 commented
> Do we need any changes?
Ya I thought that was the case, since the react-hook-form watch method is the one triggering adding the data, and since their is no `poolCandidateFilter` input anywhere on this page it wouldn't get added till the submission. This is just a proof of concept so this is good for now! We can refactor those changes in another issue.

2022-03-09 16:33 UTC, merged