Feature update/create User new fields
GCTC-NTGC/gc-digital-talent pull request #2260
Opened 2022-03-15 23:29 UTC by vd1992

resolves #1935 

draft, edits to follow
experimenting

2022-03-16 20:56 UTC, tristan-orourke requested changes
Hey, good job! This is nearly done. Besides a details you accidentally overwrote, we have to give a bit more thought to user permissions now.

2022-03-16 20:56 UTC, tristan-orourke commented on api/graphql/schema.graphql
> +    roles: [Role]
Please keep the default value
```suggestion
    roles: [Role] = []
```

2022-03-16 22:08 UTC, vd1992 commented
@tristan-orourke 
Okey, made a lot of changes.

- incorporate feedback from above in deleting/adjusting fields
- add AsUser and AsAdmin inputs
- clean up in various areas to try and patch the issues resulting from above changes

2022-03-17 23:24 UTC, vd1992 commented
Attempting to troubleshoot UpdateUser.tsx

I presume as a result of the graphQL changes, types are mismatched now. Adding all those fields on has resulted in type conflicts. With a hacky attempt I got property acceptedOperationalRequirements to not mismatch, instead cmoAssets is erroring now. It seems like some type fixing will be needed to reconcile the schema changing so much.

2022-03-18 23:20 UTC, vd1992 commented
@petertgiles 
Yeah, I'm going in circles I think and undoing things you just did. So please see if you can divine out the answers when you can, I'll avoid touching things for the moment.

2022-03-21 18:43 UTC, vd1992 commented
thanks peter!
okay, think this is ready for proper review

2022-03-21 19:34 UTC, brindasasi commented on frontend/admin/resources/js/api/userOperations.graphql
>      firstName
Wouldn't an user be able to update his own fields on below fields as well? 

   ```
 currentProvince
    currentCity

    languageAbility
    preferredLang
    lookingForEnglish
    lookingForFrench
    lookingForBilingual
    bilingualEvaluation
    comprehensionLevel
    writtenLevel
    verbalLevel
    estimatedLanguageAbility

    isGovEmployee
    interestedInLaterOrSecondment
    currentClassification {
      id
      name {
        en
        fr
      }
      group
      level
      minSalary
      maxSalary
    }

    isWoman
    hasDisability
    isIndigenous
    isVisibleMinority

    jobLookingStatus
```

2022-03-21 19:34 UTC, brindasasi commented on frontend/admin/resources/js/api/userOperations.graphql
> +      #assetCriteria
are these not required any more ? can we remove instead of commenting out?

2022-03-21 19:34 UTC, brindasasi commented on frontend/admin/resources/js/api/userOperations.graphql
> +      #assetCriteria
are these not required any more ? can we remove instead of commenting out?

2022-03-21 19:42 UTC, brindasasi commented on api/graphql/schema.graphql
> +    pools: PoolsHasMany #Pools that a user owns
could we create a pool & pool candidate that user owns when we create the user himself for the first time ?  I'm not sure we need this here.

2022-03-21 19:52 UTC, brindasasi commented on frontend/admin/resources/js/api/userOperations.graphql
> +    poolCandidates {
I don't think this is required in here

2022-03-22 15:49 UTC, brindasasi commented on api/graphql/schema.graphql
> +    pools: PoolsHasMany #Pools that a user owns
`interestedClassifications: relationship to many Classifications` is missing here

2022-03-22 18:39 UTC, brindasasi approved these changes

2022-03-22 20:38 UTC, petertgiles requested changes
Code looks really good!  Setting my review to _Request changes_ until I've had a chance to run some test mutations in graphql playground.

2022-03-23 15:11 UTC, petertgiles requested changes
Yeah, I think let's take out the pool and pool candiate from the three mutations.  Also, here's my test query
[CreateUser.txt](https://github.com/GCTC-NTGC/gc-digital-talent/files/8334187/CreateUser.txt)
.

2022-03-23 17:04 UTC, petertgiles approved these changes
Great work! :100:

2022-03-23 17:14 UTC, merged