Fix api user vulnerability
GCTC-NTGC/gc-digital-talent pull request #2331
Opened 2022-03-27 03:17 UTC by tristan-orourke

Removes User as a nested object from other types. In places, User has been replaced with another type with a subset of User fields.

Its still possible to create and update users when creating or updating Pool Candidates, but those mutations were renamed to AsAdmin to be really explicit about that not being a normal ability.

2022-03-28 14:07 UTC, petertgiles requested changes
I think there's some trouble on the pool candidate forms.  When I created the candidate with the _No Longer Interested_ status they were created with the _Available Status_.  When I ran an update on the same record I got  some errors:
![image](https://user-images.githubusercontent.com/8978655/160415599-ca408cf6-e167-490c-aadb-4b6e43ef2af5.png)
Of course it's possible these pre-existed... hopefully e2e testing starts soon!

I noticed that search requests are created without a pool assigned but I guess that's the lack of auth on talent again.

2022-03-28 17:17 UTC, JamesHuf requested changes
I'm getting an error anytime I try to update a user currently. I think this is new. 
![image](https://user-images.githubusercontent.com/49166751/160451916-8a9837cc-9e05-46f2-ba47-9df666b000e4.png)

2022-03-28 17:25 UTC, JamesHuf commented
> @JamesHuf That probably has to do with the issue being addressed by @petertgiles in this PR #2330

Yeah you're probably right, I'll update my review.

2022-03-28 17:36 UTC, JamesHuf approved these changes
As Vachan pointed out my issue is not actually a part of this PR.

2022-03-28 17:41 UTC, tristan-orourke commented
I've approved and merge #2330, I'll merge it into this branch so the issues aren't confused

2022-03-28 19:56 UTC, tristan-orourke commented
@petertgiles the Status not being saved was a bug in the CreatePoolCandidate component, it just wasn't being submitted and it defaults to AVAILABLE. Fixed in https://github.com/GCTC-NTGC/gc-digital-talent/pull/2331/commits/155192dc8bb3f3f129baaa5e85819cfde0c72676

2022-03-28 20:08 UTC, tristan-orourke commented on api/graphql/schema.graphql
> +    user: ConnectOrCreateBelongsTo! # TODO: This should be switched to UserBelongsTo as soon as possible. Permission to create a PoolCandidate shouldn't imply permission to create a User.
Good suggestion. I created an issue and referenced it in comment - I'll expand on the issue later.

2022-03-28 20:33 UTC, petertgiles commented
The create pool candidate now has right status.  An update is still failing though with the _missing primary key_ error.  I bet it's the user update part of the mutation since it doesn't have an user ID 
![image](https://user-images.githubusercontent.com/8978655/160482181-03fa181e-082e-49b9-8822-69d7f85b9beb.png)

2022-03-28 21:14 UTC, tristan-orourke commented
It turns out that using the `update` [nested mutation](https://lighthouse-php.com/master/eloquent/nested-mutations.html#belongsto) requires you to include the id - and it can be a different id! Meaning that it would allow you to update any arbitrary User, while attaching that User to the PoolCandidate. That is unintended behaviour, so I've removed it entirely.
On the form side, I've simply disabled the User field inputs. They're still there for read-only convenience. The form submits now.

2022-03-29 12:53 UTC, petertgiles approved these changes
Great solution!  Thanks for all the tidying up on this one too!

2022-03-29 12:58 UTC, merged