Talent Search - Pluralize Candidate Result Count #2370
GCTC-NTGC/gc-digital-talent pull request #2424
Opened 2022-04-08 11:38 UTC by RVany

The candidate search should properly pluralize the word _candidates_ for a result count of 1 in the search results:
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/b3e49eb1-2638-49a4-a483-f3146e45a796)

Resolves #2370

2022-04-08 13:14 UTC, petertgiles commented
There's actually a simpler way to do this that doesn't require useState or useEffect hooks.  Check out this commit from Yoni that does it using only the intl library: https://github.com/GCTC-NTGC/gc-digital-talent/pull/2140/commits/45a6e549e7019ab728ec849220128feac69f6a8a

2022-04-08 13:17 UTC, petertgiles commented
Here's to documentation on it.  The section on pluralizing is near the top: https://formatjs.io/docs/intl-messageformat/

2022-04-08 13:23 UTC, RVany commented
> 

Ok! I will do that!

2022-04-08 17:33 UTC, petertgiles requested changes
This is the right approach, great job!  The word for 0 is not right though.

Now, I just noticed something else that I did not see before so it was not in the issue.  But for one candidate there are two other words that should change as well. "There _is_ approximately 1 candidate right now who _meets_ your criteria.  Could you explore if it is possible to solve that in the same way?  On [this page](https://unicode-org.github.io/icu/userguide/format_parse/messages/#complex-argument-types) they suggest writing the full sentence as the submessage which would allow you to substitute several words in the sentence at the same time.
![image](https://user-images.githubusercontent.com/8978655/162492182-902e433b-6cc5-432d-9d77-9c964c2a37c4.png)

2022-04-08 17:33 UTC, petertgiles commented on frontend/talentsearch/src/js/components/search/EstimatedCandidates.tsx
> +                "There are approximately <weight>{candidateCount}</weight> {candidateCount,plural, =0 {candidate} =1 {candidate} other {candidates}} right now who meet your criteria.",
```suggestion
                "There are approximately <weight>{candidateCount}</weight> {candidateCount,plural, =0 {candidate} =1 {candidate} other {candidates}} right now who meet your criteria.",
```
```suggestion
                "There are approximately <weight>{candidateCount}</weight> {candidateCount,plural, =0 {candidates} =1 {candidate} other {candidates}} right now who meet your criteria.",
```

2022-04-11 16:56 UTC, RVany commented
Ha Ha! I didn't think about There are/There is part. Yes this is way better.

2022-04-12 13:43 UTC, petertgiles approved these changes
Nice, we got it!  :handshake:

2022-04-12 13:44 UTC, merged