2423 buttons wrapped by links
GCTC-NTGC/gc-digital-talent pull request #2431
Opened 2022-04-08 17:20 UTC by esizer

## Summary

Introduced a new API for the `<Link>` component to apply the same styles found with the `<Button>` component to avoid having to nest interactive elements and improve accessibility.

Resolves #2423 

## New API

I did my best to make this as identical to the API for the `<Button>` component but we could make some changes to simplify.

```typescript
export interface LinkProps extends React.HTMLProps<HTMLAnchorElement> {
  /** The style colour of the link */
  color?: Color;
  /** The style mode of the element. */
  mode?: "solid" | "outline" | "inline";
  block?: boolean;
  type?: "button" | "link";
}
```

### Example

```tsx
import { Link } from '@common/components/Link';
...
<Link type="button" mode="solid" color="primary" href="/">Home</Link>
... 
```

## Notes

### Simplify API

My only thought is that for the **type** prop, instead of accepting `"link" | "button"`, replace it with a `boolean` "button" prop that is false by default. The reason is constructed that way is to mimc the `<Button>` which accepts `"button" | "submit" | "reset" | undefined`.  Though, with the `<Button>` component, it is mapping directly to an HTML property so it is not exactly apples to apples and could be changed to simplify.

#### Example

```tsx
export interface LinkProps extends React.HTMLProps<HTMLAnchorElement> {
...
button?: boolean;
...
}

const Link: React.FC<LinkProps> = ({ button = false, ... rest }) => {...}
```

2022-04-08 19:36 UTC, petertgiles commented
I think this is a PR that would benefit from a review by the designers.  I recommend posting a note on #desfam on slack asking them if they have time to take a look.  Maybe post a link to the issue, the PR, and the chromatic story page to make it quick and easy for them.

2022-04-08 22:53 UTC, vd1992 commented
Going through, I think you've found all instances of `<Link>` nested in `<Button>` and vice-versa, didn't find anything else.
Good work!

2022-04-11 12:38 UTC, petertgiles requested changes
I'm not sure there was any consensus in the discussion but at least they had a chance to review. :man_shrugging: Don't forget to remove the unused imports to the Button file.

2022-04-11 12:57 UTC, esizer commented
> I'm not sure there was any consensus in the discussion but at least they had a chance to review. 🤷‍♂️ Don't forget to remove the unused imports to the Button file.

I think there was enough to move forward. While they did not necessarily agree with two separate components for Button and Link, they approved the look and functionality.

2022-04-11 16:09 UTC, petertgiles requested changes
I managed to find a few more unused Button imports :grin: 

DepartmentPage.tsx
PoolPage.tsx
PoolCandidatePage.tsx
SkillPage.tsx
SkillFamilyPage.tsx

2022-04-11 16:41 UTC, esizer commented
> I managed to find a few more unused Button imports 😁
> 
> DepartmentPage.tsx PoolPage.tsx PoolCandidatePage.tsx SkillPage.tsx SkillFamilyPage.tsx

I swear I ran the linter  😅

Resolved with [remove more unused Button imports](https://github.com/GCTC-NTGC/gc-digital-talent/pull/2431/commits/ebaa1cb9309d5d50abb52779e7cb997f96202281)

2022-04-11 17:04 UTC, petertgiles approved these changes
Nice one!

2022-04-12 12:51 UTC, merged