Language information form
GCTC-NTGC/gc-digital-talent pull request #2461
Opened 2022-04-13 02:53 UTC by JamesHuf

Resolves #1917 

Notes:
- Adds the LanguageInformationForm and LanguageInformationFormContainer components.
- Created storybook and tests for new form component.

2022-04-13 19:08 UTC, petertgiles requested changes
Looks super tidy!  Could you add a route so that I can load the page in the site and test initial data?  I know Vachan is finding that really sticky on his form since it also has controls that disappear depending on state.

2022-04-13 19:59 UTC, esizer approved these changes
Great work! I think this is ready to go but if you have time, it would be cool to see the use of the `renderWithReactIntl` util [Peter mentioned in his review](https://github.com/GCTC-NTGC/gc-digital-talent/pull/2461#discussion_r849800822).

2022-04-13 19:59 UTC, esizer commented on frontend/talentsearch/src/js/components/languageInformationForm/LanguageInformationForm.test.tsx
> +const renderWithReactIntl = (
I was actually going to suggest this. We have a utility to render with the provider to make things easier. You can find it [frontend/talentsearch/src/js/tests/testUtils.tsx](https://github.com/GCTC-NTGC/gc-digital-talent/blob/dd3bf526a4af761c569d38126cf161f262b305b2/frontend/talentsearch/src/js/tests/testUtils.tsx)

2022-04-13 20:43 UTC, JamesHuf commented on frontend/talentsearch/src/js/components/languageInformationForm/LanguageInformationForm.tsx
> +        Government of Canada language evaluation.
Good catch!

2022-04-13 20:46 UTC, JamesHuf commented on frontend/talentsearch/src/js/components/languageInformationForm/LanguageInformationForm.test.tsx
> +const renderWithReactIntl = (
Updated to use the testUtils version instead.

2022-04-14 14:05 UTC, petertgiles approved these changes
Looks great.  Nice work!  :1st_place_medal:

2022-04-14 19:39 UTC, merged