Remove Required tag from some User & PoolCandidate fields
GCTC-NTGC/gc-digital-talent pull request #2478
Opened 2022-04-13 14:50 UTC by tristan-orourke

Resolves #2455 

Removes required rule from multi-select inputs in PoolCandidate forms on Admin dashboard. An empty selection is reasonable for these fields.

Removes required rule from User telephone fields. 

Adds a default value for status field on new PoolCandidates, for convenience.

2022-04-13 17:51 UTC, petertgiles requested changes
When I try to create or update a user without a phone number I'm getting an error.  It looks like the validator is still running against the empty string.
![image](https://user-images.githubusercontent.com/8978655/163240144-a0bdbeb7-8b51-4e3e-a39a-b7c14643282d.png)
Pool candidate changes seem OK though.

2022-04-13 19:30 UTC, vd1992 commented
Yeah, the validate is tripping things up. I tried Googling, maybe this will help?

https://github.com/react-hook-form/react-hook-form/issues/1781#issuecomment-775632786

2022-04-14 16:51 UTC, tristan-orourke commented
@petertgiles @vd1992 Thanks. Instead of changing the API validation for phone numbers to include empty strings (which technically isn't a valid phone number 😛 ) I set the forms to submit null instead, which *is* allowed.

2022-04-14 16:52 UTC, vd1992 commented
Is the linting/prettier being a bit weird for you too? I'm noticing some files get their spacing drastically changed, create and update poolCandidate in the latest commit

2022-04-14 17:12 UTC, tristan-orourke commented
> Is the linting/prettier being a bit weird for you too? I'm noticing some files get their spacing drastically changed, create and update poolCandidate in the latest commit

Definitely a bit awkward that one line of Prettier fixing changes the indentation of the entire file :/
But I do want to allow Prettier to do its thing. @vd1992 does it not recommend that change on your machine?

2022-04-14 17:16 UTC, vd1992 commented
> > Is the linting/prettier being a bit weird for you too? I'm noticing some files get their spacing drastically changed, create and update poolCandidate in the latest commit
> 
> Definitely a bit awkward that one line of Prettier fixing changes the indentation of the entire file :/ But I do want to allow Prettier to do its thing. @vd1992 does it not recommend that change on your machine?

I had something weird where it wanted everything re-spaced, so I let it do it. Then later on, it was unhappy again wanting everything re-spaced. 
https://github.com/GCTC-NTGC/gc-digital-talent/pull/2323/commits/f907f621f7d7bb220f09956e5fe693a78168fa8b
https://github.com/GCTC-NTGC/gc-digital-talent/pull/2323/commits/3812aa1c315f17421b51b225d57eaaf33096b90b
InfoForm component spacing changed and then it wanted to change it back

2022-04-14 17:21 UTC, vd1992 commented
Not happy at all! @tristan-orourke 
![image](https://user-images.githubusercontent.com/40485260/163440972-4adaae47-b1be-425b-8916-5ebc55a02e62.png)

2022-04-14 18:08 UTC, petertgiles approved these changes
Works for me!  :+1:

2022-04-14 18:30 UTC, merged