1994 ensure routing is working for all profile edit forms
GCTC-NTGC/gc-digital-talent pull request #2586
Opened 2022-04-29 22:55 UTC by RVany

Resolve #1994 
# Description
Ensure each profile form page has routing (can be reached via a url) and that the links on the main Profile page work properly.

Set up pages, with correct routing between them, for:
- Main profile page 
- About Me
- Language Information
- Government Information
- Work Location
- Work Preferences
- Skills and Experience
- Create Experience x 5 and Edit Experience x5 (nearly identical pages, but different urls for each type, and for new vs existing items)

2022-04-29 23:02 UTC, RVany commented
ExperienceAndSkill Component added with hard coded Applicant ID.  DiversityEquityInclusionForm is not ready for development yet so Place holder component added.

2022-05-02 13:45 UTC, esizer approved these changes
Awesome! 😎

2022-05-02 17:19 UTC, petertgiles requested changes
Nice work!  Just found one small typo.

2022-05-02 17:19 UTC, petertgiles commented on frontend/talentsearch/src/js/components/diversityEquityInclusion/DiversityEquityInclusionForm.tsx
> +        <p>Comming Soon!</p>
Typo

2022-05-02 18:23 UTC, petertgiles approved these changes

2022-05-02 18:26 UTC, RVany commented
> You might want to add a few KB to bundlewatch.

Ok I will do that before merge it.

2022-05-02 20:43 UTC, merged