Feature - 2922 - Login Page
GCTC-NTGC/gc-digital-talent pull request #2995
Opened 2022-06-07 19:02 UTC by esizer

Resolves #2922 

## Summary

This creates the `/login-info` route and page for users to get information before logging into `talentsearch` profiles.

## Screenshot
<img width="1512" alt="Screen Shot 2022-06-07 at 3 02 28 PM" src="https://user-images.githubusercontent.com/4127998/172461728-f3802093-48e7-4341-9e11-416ca1f1f8dc.png">

2022-06-07 19:41 UTC, petertgiles commented
I think this PR needs an htaccess file change?

2022-06-07 19:49 UTC, esizer commented
> I think this PR needs an htaccess file change?

Dang, I used `git add .` inside of frontend 😆 

Added with [add login-info rule](https://github.com/GCTC-NTGC/gc-digital-talent/pull/2995/commits/3d855701262b6cdf23d8a958d79b09f7dc4645cc)

2022-06-08 13:07 UTC, petertgiles requested changes
Looks really nice!  I think you're missing this AC though:
_When you click login, the post-redirect url should be the profile page_
Right now it goes to admin.

2022-06-08 13:12 UTC, esizer commented
> _When you click login, the post-redirect url should be the profile page_
> Right now it goes to admin.

That makes more sense 😅 . Fixed with [fix login link redirect](https://github.com/GCTC-NTGC/gc-digital-talent/pull/2995/commits/bfe50dad472837effd1bf5ab7f1f2cbc85d4d124)

2022-06-08 14:12 UTC, petertgiles approved these changes
My first thought was that register should redirect as well but I guess anyone who is registering will get taken to the welcome profile page anyway.  All good!

2022-06-08 14:13 UTC, merged