3070 filtering applicants by classification should use generics on backend
GCTC-NTGC/gc-digital-talent pull request #3147
Opened 2022-06-21 21:02 UTC by RVany

Resolve #3070 
On the Pool Candidate and Applicant search, filtering by Classification currently has a implementation on the backend where it matches against expectedClassifications **or** against expected Salary.

Leave the Pool Candidate search alone, but update the User/Applicant search so that classifications match classification to
- expectedClassifications OR
- expectedSalary OR
- expectedGenericJobTitle

2022-06-22 14:52 UTC, tristan-orourke requested changes
Besides some formatting improvements, the code looks right to me! We should just add some tests to UserTest.php before merging this. If you don't have experience with phpunit, I can help with that.

2022-06-22 14:52 UTC, tristan-orourke commented on api/app/Models/User.php
> +     public function orfilterByClassificationToGenericJobTitles(Builder $query, array $classifications): Builder
Follow casing convention for method names
```suggestion
           $this->orFilterByClassificationToGenericJobTitles($query, $classifications);


        });

        return $query;
    }
     public function orFilterByClassificationToGenericJobTitles(Builder $query, array $classifications): Builder
```

2022-06-22 14:52 UTC, tristan-orourke commented on api/app/Models/User.php
> +           $this->orfilterByClassificationToGenericJobTitles($query, $classifications);
Indentation inconsistency
```suggestion
            $this->orfilterByClassificationToGenericJobTitles($query, $classifications);
```

2022-06-22 15:44 UTC, RVany commented
> Besides some formatting improvements, the code looks right to me! We should just add some tests to UserTest.php before merging this. If you don't have experience with phpunit, I can help with that.

Ok. Thank you!

2022-06-27 18:39 UTC, vd1992 commented
![image](https://user-images.githubusercontent.com/40485260/176012421-93a6f241-4d14-4512-9661-5374940567d7.png)

2022-06-27 20:58 UTC, petertgiles commented
I'm getting this error in my Laravel log from the search requests:
```
[2022-06-27 20:56:57] local.ERROR: Method 'filterByClassifications' does not exist on class 'App\Models\User' {"userId":"d36f699b-cbf9-4104-bec0-7d724e27be61","exception":"[object] (Nuwave\\Lighthouse\\Exceptions\\DefinitionException(code: 0): Method 'filterByClassifications' does not exist on class 'App\\Models\\User' at /var/www/html/api/vendor/nuwave/lighthouse/src/Support/Utils.php:53)
```
Are you seeing this?

2022-06-28 18:08 UTC, vd1992 commented
hm, it runs now but I'm trying to wrap my head around the query so I don't think I can really test if the results are what they should be
@petertgiles @JamesHuf can I request either of you to put the query through its paces?

2022-06-28 18:10 UTC, JamesHuf commented
> hm, it runs now but I'm trying to wrap my head around the query so I don't think I can really test if the results are what they should be @petertgiles @JamesHuf can I request either of you to put the query through its paces?

I'm looking at it now. 😃

2022-06-28 20:16 UTC, JamesHuf approved these changes
Everything seems to work as expected. 👍

2022-06-29 15:06 UTC, merged