tc-report documentation
GCTC-NTGC/gc-digital-talent pull request #3273
Opened 2022-07-06 17:18 UTC by petertgiles

Documentation on the tc-report directory.

2022-07-06 17:23 UTC, petertgiles commented on documentation/tc-report.md
> +git checkout -b staging-branch origin/main
Honestly, I'm not sure what purpose the staging-branch has or what would happen if this step was skipped.

2022-07-06 20:59 UTC, mnigh requested changes
a trivial change requested for punctuating (or not) a list consistently but otherwise, very nice!

2022-07-06 20:59 UTC, mnigh commented on documentation/tc-report.md
> +4. Have your feature branch merged into `main`.
```suggestion
4. Have your feature branch merged into `main`
```

2022-07-07 13:24 UTC, mnigh approved these changes
👍

2022-07-07 13:56 UTC, yonikid15 approved these changes
This looks great Peter 👍

2022-07-07 14:25 UTC, merged