Feature - 3158 - Admin View Pool Page
GCTC-NTGC/gc-digital-talent pull request #3274
Opened 2022-07-06 18:32 UTC by esizer

Resolves #3158 

## Summary

This adds the new pool advertisement page to admin behind the direct intake feature flag.

## Testing

1. Ensure you enable the `FEATURE_DIRECTINTAKE` flag in `.apache_env`
2. Rebuild the php container
  1. `docker-compose stop php`
  2. `docker-compose rm php`
  3. docker-compose up --detach --build`
3. Navigate to `/admin/pools`
4. Click on the name of the pool
5. Ensure the page matches the [prototype](https://www.figma.com/proto/b6lDM86QCJQ6iaAh7qrTYH/Admin-v4-(Direct-Intake)?page-id=0%3A1&node-id=1919%3A3386&viewport=-3442%2C1747%2C0.59&scaling=min-zoom&starting-point-node-id=1618%3A6064)

## Note

The URL field just displays the title until we have on available.

## Screenshot
![localhost_8000_en_admin_pools_081a27ce-8dab-4e4c-814b-003757cd60e9](https://user-images.githubusercontent.com/4127998/177619007-9324f808-9ae1-4712-8054-0f09dcd3ab17.png)

2022-07-06 18:59 UTC, vd1992 commented
for anyone else who may look at this, and find that for some reason things won't load despite doing the php inject
try this handy tip courtesy of @petertgiles 

if that red line bit is less than 3 items, open the highlighted config.sjs in a separate tab and mash refresh a couple of times and things (hopefully) resolve
(this happened to me just now and the above fixed it)

![image](https://user-images.githubusercontent.com/40485260/177622747-397ac813-d901-4214-b996-00912a79afc6.png)

2022-07-06 19:08 UTC, vd1992 reviewed
![image](https://user-images.githubusercontent.com/40485260/177623839-0c8687e7-a50d-4b5c-b076-6423a8640d9e.png)

It is a bit odd to not see the entire pool advertisement URL thing, the arrowed bit, can it be lengthened? 
as well, marked with the vertical line, the three elements do not have equal height, per wireframe they look as they do 

wireframe ref
![image](https://user-images.githubusercontent.com/40485260/177624211-8d33d0c5-c9e7-4a5e-ae6e-58d701e3ae99.png)

breadcrumbs also appears different in the wireframe
![image](https://user-images.githubusercontent.com/40485260/177624519-a7d3a276-5d80-4a62-a130-27de8a77e8d0.png)

2022-07-06 19:58 UTC, Jerryescandon commented
> 3\. leave as is

Leave as is.

The components in the design system should address this on a global scale, so we either fix for all or not. I think as a practice we should avoid doing any finagling with component design unless it is crucial to the interaction for some reason.

2022-07-06 19:59 UTC, Jerryescandon commented
> We can do the full word but we _should_ avoid using all caps unless they are acronyms.

Fair enough. Sentence case it is. Will update the wireframe.

2022-07-07 13:03 UTC, esizer commented
> It is a bit odd to not see the entire pool advertisement URL thing, the arrowed bit, can it be lengthened?

While the URL will likely be too long to be reasonably shown on most screen sizes, i have increased the width to more closely match the prototype with [increase url field width](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3274/commits/df33e0c687bc32a7baf7cc8a61f11a66ead1bf71)

> breadcrumbs also appears different in the wireframe

Updated breadcrumbs to use ID rather than title in [updated breadcrumbs to use pool id](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3274/commits/41a036061a170b3c0ce5b117c200d48866a3faa4)


> Fair enough. Sentence case it is. Will update the wireframe.

Thanks @Jerryescandon this has been fixed in [update short langs to full](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3274/commits/a69d73a18f9015e3d040ce47862dc31ad779f075)

2022-07-07 14:31 UTC, petertgiles commented
Regarding pool status, I assume since this is a pool advertisement page that you want the new derived pool advertisement status (DRAFT/PUBLISHED/CLOSED) rather than the older pool status (TAKING APPLICATIONS/NOT TAKING APPLICATIONS).  I thinking we should probably remove the old pool status field from the the pool application model in the API.

2022-07-07 14:55 UTC, petertgiles commented
@Jerryescandon what is process number?  We have a field like that on pool candidate but not pool.
![image](https://user-images.githubusercontent.com/8978655/177804689-9e27f763-1228-40e1-8556-7286a6b6adb4.png)

2022-07-07 15:36 UTC, petertgiles requested changes
Very nice!  I remembered to run Axe tools on it and 0 issues!  A few small things below but this looks 99% done.

2022-07-07 16:25 UTC, esizer commented on frontend/admin/src/js/components/pool/ViewPool.tsx
> +        <div data-h2-display="b(flex)" data-h2-align-items="b(flex-end)">
Good eye! 👀 

Fixed with [fix flex alignment](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3274/commits/93947a4eabf39edb8a20aa13eb4857543cdfc9a6)

2022-07-07 16:26 UTC, esizer commented on frontend/admin/src/js/components/pool/ViewPool.tsx
> +const getLocalizedName = (
I was contemplating this, makes sense to me. Completed in [move localize name to common/helpers](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3274/commits/d740ade28ebbdff9373d0a86b411e7da68f27d94)

2022-07-07 16:36 UTC, petertgiles commented on frontend/admin/src/js/components/pool/ViewPool.tsx
> +            href="#"
Looks great!

2022-07-07 16:36 UTC, petertgiles commented on frontend/admin/src/js/components/pool/ViewPool.tsx
> +const getLocalizedName = (
Nice.

2022-07-07 16:36 UTC, petertgiles commented on frontend/admin/src/js/components/pool/ViewPool.tsx
> +        <div data-h2-display="b(flex)" data-h2-align-items="b(flex-end)">
Very nice!

2022-07-07 17:03 UTC, Jerryescandon commented
> what is process number? We have a field like that on pool candidate but not pool.

For this one I believe we have something that is call DCMO ID or something like that on profiles, which basically groups all the current applicants into "pools" however this number is currently being inputted into the OLD profile as a field. 

The proposal was to have an auto-generated key (process number) that replaces the DCMO ID that we can use to tie applicants to pools. I was expecting this now to be generated when the pool is created as opposed to letting DCMO input it.

thoughts?

2022-07-07 17:03 UTC, Jerryescandon commented on frontend/admin/src/js/components/pool/ViewPool.tsx
> +                dateStyle: "medium",
I think localized is fine

2022-07-07 18:09 UTC, petertgiles commented
> The proposal was to have an auto-generated key (process number) that replaces the DCMO ID

Each pool has an auto-generated ID (like 3e3fff38-84d8-4c9d-a21e-1bec3ca84392) already.  The database uses this internally to associate an applicant to a pool.  Does this work for the use case?

We missed this in the database work that has been done already.  Can we kick this to a later sprint when we have a clear idea of the purpose of the field?

2022-07-07 18:23 UTC, petertgiles approved these changes

2022-07-07 18:36 UTC, merged