Debt - 3290 - default rich text intl
GCTC-NTGC/gc-digital-talent pull request #3359
Opened 2022-07-15 16:05 UTC by esizer

Resolves #3290 

## Summary

This adds default rich text tags to `react-intl` as well as replacing all of our custom tags with the new defaults.

## Default Tags

- `<strong>` : Sets font weight to 800
- `<hidden>` : Hides text for visual users to provide additional context for assistive technology
- `<heavyPrimary>` : Sets font weight to 800 and colour to light purple
- `<primary>`: Sets font  colour to light purple
- `<red>` : Sets font  colour to, you guessed it...red
- `<gray>` : Sets font colour to gray

## Testing

1. `npm run intl-extract --workspaces --if-present`
2. `npm run intl-compile --workspaces --if-present`

 > Please review chromatic thoroughly to catch any visual changes.

2022-07-15 17:13 UTC, petertgiles requested changes
Oh, you're going to hate me.  :grimacing: 
This is extremely cool!  But it disconnects all the French translations for strings where you've changed the tag.  For example, when I rerun `intl-extract` and `check-intl-admin` you can see that the string described as "Text in view user page saying they currently have the 'Inactive' status, ignore things in <> tags please" has changed from has 9KUJ50 to S0ghpc and is now untranslated.  :cry: 
![image](https://user-images.githubusercontent.com/8978655/179274364-5891f29e-923b-4b5f-868c-32cf424311d8.png)

To complete this correctly you'll need to resupply all the translations for the strings that changed.  Let me know if you need help getting up to speed with the translation process.

2022-07-15 17:35 UTC, esizer commented
> To complete this correctly you'll need to resupply all the translations for the strings that changed. Let me know if you need help getting up to speed with the translation process.

No! :( I was worried about this but wasn't sure how to check. Are you able to assist me with this?

2022-07-18 14:16 UTC, petertgiles commented
I noticed you added some important context around bold, strong, and heavy in your comment on the issue.  Could you add that information as comments to frontend/common/src/helpers/format.tsx for future reference?

2022-07-18 14:23 UTC, esizer commented
> I noticed you added some important context around bold, strong, and heavy in your comment on the issue. Could you add that information as comments to frontend/common/src/helpers/format.tsx for future reference?

Great idea, added with [add context for intl strong tag](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3359/commits/a22c21302e61b9979445770572fb2e6a25f66718)

2022-07-18 14:46 UTC, petertgiles approved these changes
Looks great!

2022-07-18 14:55 UTC, merged

2022-07-18 18:02 UTC, patcon commented
This is great! But seems that there might still be a related issue in jest tests failing?
Re: https://github.com/GCTC-NTGC/gc-digital-talent/runs/7394466546?check_suite_focus=true#step:7:71

```
countNumberOfWords tests
    ✓ should return the zero for empty string
    ✓ should return the correct number of words of string with extra white space
    ✓ should return the correct number of words of string with numbers and special characters (1 ms)
  console.warn
    [@formatjs/intl] "defaultRichTextElements" was specified but "message" was not pre-compiled. 
    Please consider using "@formatjs/cli" to pre-compile your messages for performance.
    For more details see https://formatjs.io/docs/getting-started/message-distribution
      at Object.defaultWarnHandler [as onWarn] (../node_modules/@formatjs/intl/src/utils.js:30:17)
      at verifyConfigMessages (../node_modules/@formatjs/intl/src/create-intl.js:22:16)
      at createIntl (../node_modules/@formatjs/intl/src/create-intl.js:52:5)
      at createIntl (../node_modules/react-intl/src/components/provider.js:[66](https://github.com/GCTC-NTGC/gc-digital-talent/runs/7394540472?check_suite_focus=true#step:7:67):42)
      at new IntlProvider (../node_modules/react-intl/src/components/provider.js:88:42)
      at constructClassInstance (../node_modules/react-dom/cjs/react-dom.development.js:12716:18)
      at updateClassComponent (../node_modules/react-dom/cjs/react-dom.development.js:17425:5)
  console.warn
    [@formatjs/intl] "defaultRichTextElements" was specified but "message" was not pre-compiled. 
    Please consider using "@formatjs/cli" to pre-compile your messages for performance.
    For more details see https://formatjs.io/docs/getting-started/message-distribution
      at Object.defaultWarnHandler [as onWarn] (../node_modules/@formatjs/intl/src/utils.js:30:17)
      at verifyConfigMessages (../node_modules/@formatjs/intl/src/create-intl.js:22:16)
      at createIntl (../node_modules/@formatjs/intl/src/create-intl.js:52:5)
      at createIntl (../node_modules/react-intl/src/components/provider.js:66:42)
      at new IntlProvider (../node_modules/react-intl/src/components/provider.js:88:42)
      at constructClassInstance (../node_modules/react-dom/cjs/react-dom.development.js:12[71](https://github.com/GCTC-NTGC/gc-digital-talent/runs/7394540472?check_suite_focus=true#step:7:72)6:18)
      at updateClassComponent (../node_modules/react-dom/cjs/react-dom.development.js:1[74](https://github.com/GCTC-NTGC/gc-digital-talent/runs/7394540472?check_suite_focus=true#step:7:75)25:5)
```

Seeing that for Fancy Filter PR (recently rebased) and @petertgiles "edit pool - readonly" PR:
https://github.com/GCTC-NTGC/gc-digital-talent/actions/workflows/jest.yml

2022-07-18 18:37 UTC, patcon commented
Related fix from Eric: https://github.com/GCTC-NTGC/gc-digital-talent/pull/3385 🙏