workflow troubleshooting
GCTC-NTGC/gc-digital-talent pull request #3361
Opened 2022-07-15 17:53 UTC by vd1992

trying to troubleshooting the docker/e2e issues

2022-07-15 18:45 UTC, vd1992 commented
looking at some previous runs, this one for example, post-run took 6 minutes
https://github.com/GCTC-NTGC/gc-digital-talent/runs/7346142902?check_suite_focus=true

2022-07-18 13:43 UTC, petertgiles commented
What are the "docker/e2e issues"?  I'm not sure what this branch is solving.

2022-07-18 16:07 UTC, patcon commented
Nice! If I'm understanding correctly, 8782930 looks like it also resolved it by clearing up space on the VM? This feels like the least change to get things working.

(I believe that the `skip-save: true` alternative totally turns off updating of the cache, which is the same as removing the cache step.)

Preference is for the first solution 8782930, since it preserves caching. But if you do go with the `skip-save` option (because I'm missing some consideration), I'd propose adding a comment and maybe a TODO to "re-enable once PR #### is resolved", as my experience is that temporary work-arounds get forgotten if not annotated in code :)

2022-07-18 16:08 UTC, patcon requested changes
Preference for solution in prior commit, unless I'm missing some consideration :)

2022-07-18 17:08 UTC, vd1992 commented
> Preference for solution in prior commit, unless I'm missing some consideration :)

aye aye

2022-07-18 22:38 UTC, patcon approved these changes
Thanks!

2022-07-18 22:41 UTC, vd1992 commented
> Thanks!

workflows please cooperate now!

2022-07-18 22:42 UTC, merged