Admin - Print user table profiles
GCTC-NTGC/gc-digital-talent pull request #3363
Opened 2022-07-15 19:45 UTC by mnigh

Resolves #2644. h/t @esizer.

### Bonus

- [updates Loading component padding, background color](https://github.com/GCTC-NTGC/gc-digital-talent/commit/9dc64ec258173407ebc0591f42db8ccaf9f39ed9)

### Steps to Test
1. Refresh containers `docker-compose run --rm maintenance bash refresh_all.sh`
2. Navigate and login as admin user at `/admin`
3. Navigate to Users Table `/en/admin/users`
4. Slect all or a few of the rows using the checkbox on the far right column
6. Scroll to table footer at the bottom
7. Near **Selected actions** click **Print** button
8. See print preview screen with rows of users selected

2022-07-15 21:37 UTC, vd1992 commented on frontend/admin/src/js/components/user/UserProfileDocument.tsx
> +          ;
I think this is might be an accident
and is probably causing this orphaned semicolon here

![image](https://user-images.githubusercontent.com/40485260/179314399-8319fba9-6b56-4889-bb89-5ea17042c803.png)

2022-07-15 22:16 UTC, vd1992 commented
very clever reworking the other print document to fit single or multiple users, enables consistency too
elegant solution!

also
maybe a small suggestion, not important, but as a quality of life (QoL) improvement can it be more easy to distinguish where one user ends and another begins? for when you are printing a bunch of users at once you could easily push to 15, 30 pages
doesn't need to be a new page, maybe a divider line

![image](https://user-images.githubusercontent.com/40485260/179318022-23c9a8c3-503f-41a8-bb20-21ac802b6196.png)

2022-07-18 14:10 UTC, petertgiles requested changes
Awesome!  It's very performant, too.  I like the loader over the print button while fetching, especially.  I agree with Vachan that some more visible separation between applicants would be good.

2022-07-18 14:56 UTC, petertgiles approved these changes
Love it!

2022-07-18 15:38 UTC, merged