Design - 3453 - update add experience buttons
GCTC-NTGC/gc-digital-talent pull request #3529
Opened 2022-07-28 13:58 UTC by esizer

Resolves #3453 

## Summary

This improves the display of block level `<IconLink />` component and converts the links to add new experiences to use the `<IconLink />` component.

## Screenshot

<img width="1202" alt="Screen Shot 2022-07-28 at 9 56 56 AM" src="https://user-images.githubusercontent.com/4127998/181523714-f0ab2f7f-9ad7-489c-9486-0f2eeee24cde.png">

2022-07-28 19:22 UTC, yonikid15 requested changes
Looking good so far! One last thing is to make it responsive:
<img width="181" alt="image" src="https://user-images.githubusercontent.com/22059495/181620384-892a3f02-961b-49f6-9eec-7de150c349e6.png">

2022-07-28 19:26 UTC, mnigh requested changes
A few notes:

1. It appears that a few items from the acceptance criteria of the issue are not resolved, basically the text changing from links to buttons: Update copy on Null state (English); Update copy on Null state (French): https://github.com/GCTC-NTGC/gc-digital-talent/blob/7688f0c0b3655b73e522e131d3413a96039a1819/frontend/talentsearch/src/js/components/applicantProfile/ExperienceAndSkills.tsx#L183
2. Would it be possible to stack the buttons on small screen widths? See screenshot for what it looks like on this branch:
![Screen Shot 2022-07-28 at 15 21 50](https://user-images.githubusercontent.com/3046459/181620454-32fee34d-da49-421f-8a7a-0c26582f6b9e.png)
3. For screen readers, the button text doesn't indicate what the button is doing. Could it be something like `Add {experienceType} new experience` with everything but `{experienceType}` being hidden for everything but screen readers?

2022-07-28 19:41 UTC, esizer commented
@yonikid15 @mnigh fixed all issues, disappointingly in a single commit: [update null state + button copy, mobile responsive](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3529/commits/491560d44fcaad247d166796058e4a096309cce5). Sorry!

2022-07-28 20:03 UTC, mnigh commented on frontend/talentsearch/src/js/components/applicantProfile/ExperienceAndSkills.tsx
> +                    "<hidden>Add new </hidden>{title}<hidden> experience</hidden>",
```suggestion
                    "<hidden>Add new <hidden>{title}</hidden> experience</hidden>",
```

2022-07-28 20:06 UTC, esizer commented
@Jerryescandon How do you feel about the following null state text so we can avoid the directional language?

"There are no experiences on your profile yet. You can add some using the preceding buttons."

2022-07-28 20:15 UTC, mnigh approved these changes
Responsive button stacking looks good, screen reader text is nice, and I like the replacing of the directional language from _add some using the links above_!
👍

2022-07-28 20:34 UTC, yonikid15 approved these changes
Looks great!

2022-07-29 17:23 UTC, Jerryescandon commented
> @Jerryescandon How do you feel about the following null state text so we can avoid the directional language?

to be honest im not sure what the A11y best practice is on this, I would err on that, but if it doesn't conflict with anything go for it.

2022-07-29 17:46 UTC, merged