migrate data from PoolCandidate to User
GCTC-NTGC/gc-digital-talent pull request #3567
Opened 2022-08-02 21:19 UTC by vd1992

closes #3148 
not a lot of lines, just tricky logic and plenty of room for error! 

### TESTING
       STAGE ONE - SETUP
 - Checkout + run all migrations/seeder to ensure things are on the right track
 - run `php artisan migrate:rollback --step=1`
 - ensure the rolled back migration is the poolcandidate_data one

       STAGE TWO - DATA PREPARATION 
- go to classification_pool_candidate table
- pick a random entry or two, write down the pool candidate id and classification id, as well, write down the user id attached to that candidate
- next, go to users table
- pick a user, note who you selected, edit said user and set various fields to null (specifically field noted in the migration)

       STAGE THREE - DATA CLEARANCE
- go to classification_users, select all entries and delete them
- go to cmo_assets_users, select all entries and delete them

      STAGE FOUR - RUN THE MIGRATION
- run 'php artisan migrate --path=/database/migrations/2022_08_02_193722_poolcandidate_data_to_user.php'

      STAGE FIVE - EVALUATING THE MIGRATION
- go to users table, go to the user you noted, ensure the fields you nulled have values 
- go classifications_users and cmo_assets_users tables, ensure they have values again
- go to classifications_users, using what you noted down, ensure the pool candidate with the user id attached to some classification was added in and remains the same

      STAGE SIX - CONGRATULATIONS FOR FOLLOWING INSTRUCTIONS

2022-08-02 21:22 UTC, vd1992 commented
### DEPLOYMENT
BIG MIGRATIONS

2022-08-03 15:57 UTC, petertgiles requested changes
It works!  A comment below to make it safer though.

2022-08-03 16:00 UTC, petertgiles commented
Here's a query I wrote for a more thorough check.  Note that if you switch to combining ID arrays instead of overwriting it might cause a false positive.
<details>
  <summary>Click to see SQL</summary>

```
select
  case
    when u.is_woman <> pc.is_woman then 'is_woman'
    when u.has_disability <> pc.has_disability then 'has_disability'
    when u.is_indigenous <> pc.is_indigenous then 'is_indigenous'
    when u.is_visible_minority <> pc.is_visible_minority then 'is_visible_minority'
    when u.has_diploma <> pc.has_diploma then 'has_diploma'
    when u.language_ability <> pc.language_ability then 'language_ability'
    when u.location_preferences <> pc.location_preferences then 'location_preferences'
    when u.accepted_operational_requirements <> pc.accepted_operational_requirements then 'accepted_operational_requirements'
    when u.expected_salary <> pc.expected_salary then 'expected_salary'
    when cu.classification_ids <> cpc.classification_ids then 'classification_ids'
    when cau.cmo_asset_ids <> capc.cmo_asset_ids then 'cmo_asset_ids'
    else null
  end matching_error,
  u.id user_id,
  pc.id pool_candidate_id,
  u.is_woman,
  pc.is_woman,
  u.has_disability,
  pc.has_disability,
  u.is_indigenous,
  pc.is_indigenous,
  u.is_visible_minority,
  pc.is_visible_minority,
  u.has_diploma,
  pc.has_diploma,
  u.language_ability,
  pc.language_ability,
  u.location_preferences,
  pc.location_preferences,
  u.accepted_operational_requirements,
  pc.accepted_operational_requirements,
  u.expected_salary,
  pc.expected_salary,
  cu.classification_ids,
  cpc.classification_ids,
  cau.cmo_asset_ids,
  capc.cmo_asset_ids
from users u
join pool_candidates pc  on u.id = pc.user_id
left join (
  select user_id, string_agg(cast(classification_id as varchar), ', ' order by classification_id) classification_ids
  from classification_user
  group by user_id
) cu on u.id = cu.user_id
left join (
  select pool_candidate_id, string_agg(cast(classification_id as varchar), ', ' order by classification_id) classification_ids
  from classification_pool_candidate
  group by pool_candidate_id
) cpc on pc.id = cpc.pool_candidate_id
left join (
  select user_id, string_agg(cast(cmo_asset_id as varchar), ', ' order by cmo_asset_id) cmo_asset_ids
  from cmo_asset_user
  group by user_id
) cau on u.id = cau.user_id
left join (
  select pool_candidate_id, string_agg(cast(cmo_asset_id as varchar), ', ' order by cmo_asset_id) cmo_asset_ids
  from cmo_asset_pool_candidate
  group by pool_candidate_id
) capc on pc.id = capc.pool_candidate_id
```
</details>

2022-08-03 19:11 UTC, vd1992 commented on api/database/migrations/2022_08_02_193722_poolcandidate_data_to_user.php
> +	        $allUsers->where('id', $userId)->first()->expectedClassifications()->sync($classifications);
![image](https://user-images.githubusercontent.com/40485260/182689856-e517b72f-8801-440b-9ca3-ae8fd7826ae3.png)

makes this happen, so no I guess?

![image](https://user-images.githubusercontent.com/40485260/182690033-bff512be-0f99-43a9-9be9-5367ec816729.png)

2022-08-03 19:26 UTC, vd1992 commented on api/database/migrations/2022_08_02_193722_poolcandidate_data_to_user.php
> +	        $allUsers->where('id', $userId)->first()->expectedClassifications()->sync($classifications);
you may have to handhold me here if this isn't what you meant
okay, I took a stab at what I think you meant

![image](https://user-images.githubusercontent.com/40485260/182692515-96ef872b-eddb-4657-8324-6f06af4efcab.png)

2022-08-04 13:41 UTC, petertgiles commented on api/database/migrations/2022_08_02_193722_poolcandidate_data_to_user.php
> +	        $allUsers->where('id', $userId)->first()->expectedClassifications()->sync($classifications);
Yeah, that looks right to me!

2022-08-04 13:55 UTC, petertgiles commented on api/database/migrations/2022_08_02_193722_poolcandidate_data_to_user.php
> +	        $allUsers->where('id', $userId)->first()->expectedClassifications()->sync($classifications);
I'm still learning my Eloquent but I think this works.
![image](https://user-images.githubusercontent.com/8978655/182864582-f89cca7c-bd60-4da0-916e-de054166ca3b.png)
We don't have PHP linting yet but watch the tabs.

2022-08-04 16:13 UTC, vd1992 commented on api/database/migrations/2022_08_02_193722_poolcandidate_data_to_user.php
> +	        $allUsers->where('id', $userId)->first()->expectedClassifications()->sync($classifications);
added in the latest commit
guess we aren't merging this yet so just let me know if everything works fine and we can merge it down the road
don't approve it either please, so it isn't accidentally merged 🤣

2022-08-04 16:13 UTC, vd1992 commented on api/database/migrations/2022_08_02_193722_poolcandidate_data_to_user.php
> +	        $allUsers->where('id', $userId)->first()->expectedClassifications()->sync($classifications);
how do you get those dots and things to show? I don't have it in my editor

2022-08-04 16:29 UTC, petertgiles commented on api/database/migrations/2022_08_02_193722_poolcandidate_data_to_user.php
> +	        $allUsers->where('id', $userId)->first()->expectedClassifications()->sync($classifications);
I've got an extension called "Render Line Endings" installed.

2022-08-04 18:44 UTC, petertgiles commented
I approve!  I'll hold-off "github approving" until we're ready to merge this.

2022-08-05 15:07 UTC, vd1992 commented
merging waiting until Applicant Search live

2022-09-07 14:59 UTC, merged