archive applications mutation
GCTC-NTGC/gc-digital-talent pull request #3577
Opened 2022-08-04 19:17 UTC by vd1992

resolves #3417 

To test, open up graphQL Playground and Adminer
Add this operation
```
mutation archivingTest($poolCanId: ID!) {
  archiveApplication(id: $poolCanId) {
    id
    status
    isArchived
  }
}
```
And this input variable

`"poolCanId": "________",`

filling the variable with `id` values from the `pool_candidate` **table**, noting their `pool_candidate_status` _value_
then run some operations

also, thank you very much @yonikid15, I basically recycled your validation/resolvers stuff wholesale 🙇

2022-08-04 19:44 UTC, petertgiles commented
The policy, mutation, and validation is looking :fire: 

I wonder if this could be made simpler though?  The table already has [soft deletes](https://laravel.com/docs/8.x/eloquent#soft-deleting).  @tristan-orourke should we use that instead of making our own archive column?
![image](https://user-images.githubusercontent.com/8978655/182939216-914a58e5-97c2-460a-bcee-764972734512.png)

2022-08-05 00:01 UTC, esizer commented
> I wonder if this could be made simpler though? The table already has [soft deletes](https://laravel.com/docs/8.x/eloquent#soft-deleting).

+1 to soft deletes

2022-08-05 16:36 UTC, vd1992 commented
#3416 adds deleting applications
does that cause confusion if there are two things with delete operations?

2022-08-05 19:42 UTC, tristan-orourke commented
> @tristan-orourke #3416 adds deleting applications doesn't that cause confusion if there are two things with delete operations?

Well, we could implement #3416 with hard deletes, and this one with soft deletes. 

The main thing to be aware of with Laravel's [soft deletes](https://laravel.com/docs/9.x/eloquent#soft-deleting) is that Laravel will automatically exclude them queries. That can be overridden of course, but it might be tricky/annoying to add to our schema. 

If we do use soft-deleting for archiving, we should expect an API query like `me.poolCandidates` to NOT include archived ones. And maybe that's a good thing? I think we'd want to either include a special field (`me.poolCandidatesArchived`) implemented with an accessor, or a special query using the [ softDeletes](https://lighthouse-php.com/5/api-reference/directives.html#softdeletes) directive (`poolCandidates(userId: ID!): [PoolCandidates!]! @where @softDeletes`).

It might be simpler (ie less "magic") to simply use our own `archived_at` field. If we do that, I like Laravel's approach of making it a nullable date.

I'm happy with either approach, honestly, and leave it up to the implementer.

2022-08-05 19:49 UTC, vd1992 commented
> I'm happy with either approach, honestly, and leave it up to the implementer.

I'm gonna be honest, I am a bit biased towards the one I already did

2022-08-05 20:12 UTC, brindasasi commented
I vote for using a sep field for archiving. 
Pros: differentiates from actual soft deletes , 
          easy to extract archived applications later  for showing in the front end

2022-08-08 12:35 UTC, petertgiles commented
I do prefer the built-in soft deletes but majority seems to prefer a custom field.
> It might be simpler (ie less "magic") to simply use our own archived_at field. If we do that, I like Laravel's approach of making it a nullable date.

I like this, it would at least be consistent with the existing database fields and provide some context for the user.

2022-08-08 19:11 UTC, petertgiles requested changes
Nice, I tried a few out and it seems to work as advertised!  I'm gonna pick a few nits below but the behavior seems all good.

2022-08-08 21:01 UTC, vd1992 commented on api/database/migrations/2022_08_04_162942_add_archiving_pool_candidate.php
> +            $table->timestamptz('archived_date')->nullable();
aye aye
https://github.com/GCTC-NTGC/gc-digital-talent/pull/3577/commits/bd974086d3b5cb8e430d25caeb2c097a40ab1018

2022-08-08 21:01 UTC, vd1992 commented on api/tests/Feature/PoolCandidateTest.php
> +      'pool_candidate_status' => $statusesThatShouldFail[array_rand($statusesThatShouldFail)],
okey
https://github.com/GCTC-NTGC/gc-digital-talent/pull/3577/commits/650f753a0e8db2aa0ca8bff3066344191a5b244d

2022-08-08 21:03 UTC, vd1992 commented on api/tests/Feature/PoolCandidateTest.php
> +        'message' => 'Unauthenticated.',
think so, the test would fail otherwise
might just be the default message for failing the `@guard` directive

2022-08-09 13:30 UTC, petertgiles commented on api/tests/Feature/PoolCandidateTest.php
> +        'message' => 'Unauthenticated.',
No, I think it's a problem with the test.  In the test, it's running before the admin user is added to the test database and so authentication is failing.  Here's a demo of what it looks like when the "applicant@test.com" user tries (which is like a regular applicant who shouldn't be able to archive)

https://user-images.githubusercontent.com/8978655/183659989-fc42a101-8583-4db2-9b82-f29ade4c9257.mp4

.

2022-08-09 13:32 UTC, petertgiles commented on api/tests/Feature/PoolCandidateTest.php
> +        'message' => 'Unauthenticated.',
How to fix this is a much thornier question though.  Right now we've got phpunit always just setting the admin user [here](https://github.com/GCTC-NTGC/gc-digital-talent/blob/9bc07b61b5ec5461ccf6f7616f798ea604ada264/api/phpunit.xml#L30) but I think we've hit the limit of that and maybe need to instead start setting the user on a per-test basis.  Let me know if you want help digging into that.

2022-08-09 14:08 UTC, petertgiles commented on api/tests/Feature/PoolCandidateTest.php
> +        'message' => 'Unauthenticated.',
Also, if you don't want to tackle this change now I'd approve this PR is you commented out the test and put an issue on the board for reworking the test.

2022-08-09 18:49 UTC, vd1992 commented
spun out #3642 and #3643

2022-08-09 18:50 UTC, petertgiles approved these changes

2022-08-09 18:54 UTC, merged