Copy - 3393 - Update profile back button text
GCTC-NTGC/gc-digital-talent pull request #3652
Opened 2022-08-11 13:50 UTC by esizer

Resolves #3393 

## Summary

This updates the props for the `ProfileFormWrapper` and `CancelButton` to components to allow more customisation. As well, it changes the cancel link text on `/talent/profile/skills-and-experiences` and `/talent/profile/diversity-and-inclusion` for improved context.

## Screenshot
<img width="673" alt="Screen Shot 2022-08-11 at 9 49 09 AM" src="https://user-images.githubusercontent.com/4127998/184148718-557e27f2-5b6a-41b9-bce1-125113781e8a.png">

## Testing

1. Build talentsearch `cd frontend && npm run production --workspace=talentsearch`
2. Navigate to `/talent/profile/skills-and-experiences` and `/talent/profile/diversity-and-inclusion`
3. Confirm the cancel links contain the text "Go back to my profile"

2022-08-11 20:09 UTC, yonikid15 requested changes
Nice work Eric, just found a couple small bugs that should take no time:

- Experience and Skills page: button on footer is incorrect.
![experience_and_skills_3652](https://user-images.githubusercontent.com/22059495/184231504-84c9958b-7ff4-41ce-8983-613703e7a25a.png)

- Diversity and inclusion: Footer button is missing completely

![diversity_and_inclusion_3652](https://user-images.githubusercontent.com/22059495/184232774-768f0e07-973d-4345-97a4-a6d50fcde485.png)

2022-08-11 20:09 UTC, yonikid15 commented on frontend/talentsearch/src/js/components/applicantProfile/ExperienceAndSkills.tsx
> +      }}
You're going to need to update the `<ProfileFormFooter />` [on line 210](https://github.com/GCTC-NTGC/gc-digital-talent/blob/dd9a2915d67008f44763b236cd68f9cff807fdd4/frontend/talentsearch/src/js/components/applicantProfile/ExperienceAndSkills.tsx#L210) to accept a cancelLink as well.

2022-08-12 12:03 UTC, esizer commented on frontend/talentsearch/src/js/components/applicantProfile/ProfileFormWrapper.tsx
> +import CancelButton, { type CancelButtonProps } from "./CancelButton";
I don't think it is **_necessary_**, but with some bundlers it hints to not include it as part of the bundle so I try to use it when importing something only as a type.

2022-08-12 12:13 UTC, esizer commented on frontend/talentsearch/src/js/components/diversityEquityInclusion/DiversityEquityInclusionForm.tsx
> +      }}
Thanks! I didn't realize how many different places we needed to use this, I pulled it out in [move back to profile to common messages](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3652/commits/c15c83f799b05264428f486dfc870e8cdeab5d06) and added the missing button in [add footer cancel button to dei page](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3652/commits/46050505cc7d303963b0a11f2d9e0b252ff06905)

2022-08-12 17:03 UTC, yonikid15 approved these changes
Looks great!

2022-08-12 17:05 UTC, merged