Submit application e2e test
GCTC-NTGC/gc-digital-talent pull request #4020
Opened 2022-09-21 14:11 UTC by petertgiles

This branch adds an e2e test to submit an application to a pool.

## Notes
1) Submitting an application is not an idempotent operation - doing it once will prevent you from doing it again.  Therefore, this test runs a fresh db migration and seed before every run.  It's slow but I'm not sure how else to do it.  I opened #4019 to look into it.  I wonder if we should consider a special fast seeder for e2e tests?  Maybe we want to consider squashing our migrations at some point?

1) This branch rejigs the user seeding a bit.  It seeds the admin user, then seeds the pools owned by that user, then seeds the rest of users, including one that has the required skills for the pool.

## Testing
`npx cypress run --headed --spec "cypress/integration/talentsearch/submit-application-workflows.spec.js"`

2022-09-21 17:52 UTC, esizer commented
I'm getting the following error when attempting to run the test. 

```
cy.exec('php ../api/artisan migrate:fresh --seed') failed because the command exited with a non-zero code.

...

SQLSTATE[08006] [7] could not translate host name "postgres" to address: nodename nor servname provided, or not known (SQL: select tablename from pg_catalog.p...
```

2022-09-21 18:44 UTC, petertgiles commented
> I'm getting the following error when attempting to run the test.

Shoot, this is another docker vs local issue I'm sure.  You're testing in the php container or maintenance container?

2022-09-22 20:16 UTC, brindasasi commented on frontend/cypress/integration/talentsearch/submit-application-workflows.spec.js
> +    cy.wait("@gqlbrowsePoolsQuery");
I get stuck here. It gets time out.
![Submit Workflow Tests -- Submits an application to the CMO pool (failed)](https://user-images.githubusercontent.com/89482910/191842675-6be48bd1-6e64-443d-9c04-c3d1c908ed6a.png)

2022-09-22 21:36 UTC, brindasasi requested changes
I would think of setting up the data before each run and tear down after the test is done. 
In this case we could delete the application after successful verification. 
We might not need fresh seeding every run.

2022-09-22 21:37 UTC, brindasasi commented on frontend/cypress/integration/talentsearch/submit-application-workflows.spec.js
> +    cy.exec('php ../api/artisan migrate:fresh --seed');
btw , the test works perfectly fine.

2022-09-27 13:16 UTC, closed without merging