Feature - 4228 - Skill picker updates
GCTC-NTGC/gc-digital-talent pull request #4242
Opened 2022-10-07 16:30 UTC by esizer

Resolves #4228 and #4230 

## Summary

This overhauls the `<SkillPicker />` to replace the tab interface with a search bar and select field for skill families.

## Details

The new `<SkillPicker />` has some changes that should also improve accessibility.

- It announces the number of skills found once you search
- Tracks `aria-expanded` on the "See definition" toggle
- Improves context of the "See definition" and "Add skill" buttons
- Announces the definition once opened (not 100% sure if this is a pro or con yet, thoughts?)

## Notes for Designers

Since I was working from a wireframe, the styling is all done by me and I'd love some feedback to improve it!

## TO DO

- [ ] Support `optgroup` in `MultiSelectV2`

## Screenshot

<img width="581" alt="Screen Shot 2022-10-07 at 12 18 08 PM" src="https://user-images.githubusercontent.com/4127998/194600678-88f52516-fa27-46c6-9414-c8daeb54c150.png">

## Testing

> **Warning**
> If you are doing a11y testing in storybook on a mac, there is a known bug that VoiceOVer double announces `aria-live` areas. This means, while searching, you will hear "Found X skills" twice every time. This only occurs in storybook and not on the actual site.

### Storybook

This is fully functional in story book and you can do testing there but, it is recommended to do the testing in context and confirm none of them break.

### Locations

This component can be found the following locations to be tested:

- `/seach`
- `/users/{userId}/profile/experiences/{experiencType}/create`
- `/users/{userId}/profile/experiences/{experiencType}/{experienceId}/edit`
- `/admin/pools/{poolId}/edit`

## Steps

1. [ ] Build both projects `npm run production --workspaces`
2. [ ] Navigate to one of the locations listed in the "Locations" section
3. [ ] Fill out a search term and confirm expected results appear
4. [ ] Select some skill families and confirm expected results appear
5. [ ] Combine steps 3-4 confirm expected results appear
6. [ ] Select "See definition" and confirm the definition appears
7. [ ] Confirm you can hide the definition
8. [ ] Select "Add skill" and confirm it appears
9. [ ] Confirm you can remove a skill with the "Remove skill" and `<Chip />` x icon
10. [ ] Confirm you can scroll the area with skills
11. [ ] Bonus: Do steps 3-10 with a screen reader and just your keyboard 😄

2022-10-07 19:06 UTC, patcon commented
real quick before i sign-off for night: went to scope stories for selectfieldv2 and multiselectfieldv2, and didn't see any. (will do real review next week)

2022-10-07 19:09 UTC, esizer commented
> real quick before i sign-off for night: went to scope stories for selectfieldv2 and multiselectfieldv2, and didn't see any. (will do real review next week)

Are you referring to stories showcasing the `optgroup`? Or are they missing entirely for you? I will add the `optgroup` stories, forgot about them after all the bug hunting 🐛 🏹

2022-10-11 15:36 UTC, tristan-orourke commented on frontend/common/src/components/Pill/Pill.tsx
> +    "data-h2-font-size": "base(caption)",
Just to make it consistent with the other sizes 😅 
```suggestion
    "data-h2-font-size": "base(caption)",
    "data-h2-padding": "base(x.25, x.75)",
```

2022-10-11 19:37 UTC, tristan-orourke approved these changes
Everything looks great. Some interesting new utility components too, and updates to the Select input!

Just before merging, could you translate "Skill Families" and "Found N skills"? Everything else in the picker seems to be already translated.
![image](https://user-images.githubusercontent.com/4313717/195183146-abe65086-8735-4f5b-879b-c26ae515f31e.png)

2022-10-11 19:37 UTC, tristan-orourke commented on frontend/common/src/components/SkillPicker/SkillBlock.tsx
> +                  onClick={() => setIsOpen(!isOpen)}
When a useState setter uses its own value, I think its best practice to pass the current value as an argument:
https://reactjs.org/docs/hooks-reference.html#functional-updates

```suggestion
                  onClick={(currentIsOpen) => setIsOpen(!currentIsOpen)}
```

2022-10-11 20:50 UTC, tristan-orourke requested changes
I guess approval should also be contingent on all the tests passing :/

2022-10-12 19:22 UTC, esizer commented
@tristan-orourke  Added French in [update copy en + fr](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4242/commits/099655808da9d6c47834e8251988ce01cb1a07d2)

2022-10-12 19:32 UTC, tristan-orourke approved these changes
👏

2022-10-12 21:39 UTC, merged