Remove title from individual experience pages
GCTC-NTGC/gc-digital-talent pull request #4537
Opened 2022-11-01 13:34 UTC by petertgiles

Removes the title from the individual experience pages.

https://user-images.githubusercontent.com/8978655/199245688-5aeccbdd-b269-4799-a3ae-894e096d55cd.mp4

Closes #4440

2022-11-01 14:11 UTC, esizer requested changes
Hmm, I'm not sure I agree with this. If users are confused by the title, I think we should change it and not fully remove it. 

Each page should have one unique `<h1>` that acts as the document title describing the content on the page. This also introduces the issue of heading ranks being nested improperly due to `<h2>` now being the first heading on the page.

Could we use something like "Edit/Add Experience" as the title rather than removing it all together?

REF: https://www.a11yproject.com/posts/how-to-accessible-heading-structure/

2022-11-01 14:14 UTC, mnigh commented
> Each page should have one unique `<h1>` that acts as the document title describing the content on the page. This also introduces the issue of heading ranks being nested improperly due to `<h2>` now being the first heading on the page.

Agree with @esizer, see axe Dev Tools for reinforcement:

### Screenshot
![Screen Shot 2022-11-01 at 10 12 40](https://user-images.githubusercontent.com/3046459/199254235-c7247d01-ece1-4bfb-b6c8-2e2795251e29.png)

2022-11-01 14:21 UTC, petertgiles commented
Good call.  I'll bounce it back to Jerbo.

2022-11-01 15:37 UTC, Jerryescandon commented
![image](https://user-images.githubusercontent.com/16977254/199273903-333263c6-4cff-44a3-9c05-df96adccf1cd.png)

2022-11-01 18:32 UTC, petertgiles commented
OK, they're in.  I noticed that two of the 
[translations](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4537/commits/2afaa456b7e39aa05e18ff36cb72e855acef06f6) we received are a bit inconsistent.  @gobyrne could you take a quick look at these?
![image](https://user-images.githubusercontent.com/8978655/199310673-cdfa69d7-2d8e-4b01-8af1-08b9f1349608.png)
![image](https://user-images.githubusercontent.com/8978655/199310770-093a2eaf-d7a0-4dd4-8a38-d8698e510930.png)

2022-11-01 18:40 UTC, esizer commented on frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.tsx
> +
Do we also want a case for if the user is adding a new one or editing an existing one? 😅

2022-11-07 17:03 UTC, esizer commented
Marked requested changes as completed. I think we can merge once the conflict is resolbed based on the convo during standup.

2022-11-07 17:58 UTC, merged

2022-11-08 14:33 UTC, gobyrne commented
Eeak, sorry I'm so late. Can we use "Modifier l'expérience des études" and "Modifier l'expérience communautaire" please?