Display results of ApplicantFilter in SingleSearchRequestTable
GCTC-NTGC/gc-digital-talent pull request #4623
Opened 2022-11-07 16:59 UTC by tristan-orourke

Resolves #3648.

This should be the minimal viable solution to #3648, ie allowing admins to review the list of applicants who meet the requirements of an ApplicantFilter request. We can spin off any non-essential features of #3648 into other tickets.

Testing:
1. ensure ApplicantSearch feature flag is true
2. Go to /search, and submit a request that results in at least some candidates.
3. Sign in to the admin dashboard. View the most recent request.
4. The table of users at the bottom should have the same number of rows as the number of candidates according to the search page.
5. Each row should have a link to the Users page, with the tabs
6. The filters in the table should be editable (without modifying the original request!), but if they're not, make that a new issue.

2022-11-07 20:00 UTC, yonikid15 reviewed
It looks like it's coming together nicely 🎉 

I checked the network requests along with the DB and it looks like it's working as expected, switching seamlessly btw `ApplicantFilterInput` and the soon to be deprecated `PoolCandidateFilterInput`. Appears to be showing the correct Users. One thing we need to improve is seeding the request tables with Users. Most of the time they are empty. However, that's out of scope for this issue.

I'll let you finish up the rest (cleaing up linting errors, removing commented out code, any other refactoring) before a final review. Nice work!

2022-11-08 00:00 UTC, vd1992 commented
Am I missing a step
codegen -> dev -> open up a request at `/talent-requests/:id`

I don't have any users load
![image](https://user-images.githubusercontent.com/40485260/200435455-f026e50d-fb3b-463c-b374-13d51322e7d5.png)

![image](https://user-images.githubusercontent.com/40485260/200435547-453205ae-2ecf-4f79-913a-542666652b77.png)

2022-11-08 00:05 UTC, vd1992 commented
think something might be weird with my request page since it lets me send that request with non-zero candidates/applicants but SQL querying for just pool and active gives zero results

![image](https://user-images.githubusercontent.com/40485260/200441670-0a2245be-455f-4a9e-923d-179b1b746a48.png)

2022-11-08 02:59 UTC, tristan-orourke commented
Made it possible to initialize the filters which appear in a UserTable filter dialog, and used the request.applicantFilter to initialize it!

@vd1992 there are a few extant bugs which might explain why you see non-zero results on the search page, and none on the admin SingleSearchRequest table. #4557 was already on the board, and I just discovered #4660!

2022-11-08 03:01 UTC, tristan-orourke commented
@yonikid15 the searchApplicants query was a leftover from previous implementation - no need to test it if I can delete it! 😝

2022-11-08 13:46 UTC, petertgiles commented
Don't forget your translations. :smile: 
```
{
  "hmacO5": {
    "defaultMessage": "Request doesn't include a filter!",
    "description": "Null state for a request not including a filter."
  }
}
```

2022-11-08 14:13 UTC, patcon commented on frontend/admin/src/js/components/user/UserTableFilterDialog.tsx
> +  );
Just to hint at "initialState", which is var name in useState docs that we pass in:

```suggestion
  const initialFiltersState = activeFilters ?? emptyFormValues;
  const [activeFilters, setActiveFilters] = useState<FormValues>(initialFiltersState);
```

2022-11-08 14:14 UTC, patcon commented on frontend/admin/src/js/components/user/UserTableFilterDialog.tsx
> +  initialActiveFilters?: FormValues;
```suggestion
  activeFilters?: FormValues;
```

2022-11-08 14:18 UTC, patcon commented on frontend/admin/src/js/components/user/UserTable.tsx
> +    setUserFilterInput(formValuesToUserFilterInput(data));
Starting functions with verbs?

```suggestion
    setUserFilterInput(transformUserFormValuesToFilterInput(data));
```

2022-11-08 14:18 UTC, patcon commented on frontend/admin/src/js/components/user/UserTable.tsx
> +function userFilterInputToFormValues(
```suggestion
function transformUserFormValuesToFilterInput(
```

2022-11-08 14:28 UTC, petertgiles requested changes
On my initial test, I expected to get one result but I ended up getting two.  If it's helpful I can dig in and try to find the discrepancy.

![image](https://user-images.githubusercontent.com/8978655/200589708-fe5294a7-e4cb-4c9d-97ed-89cdf2a20f3e.png)

2022-11-08 14:39 UTC, patcon commented on frontend/admin/src/js/components/user/UserTable.tsx
> +  );
```suggestion
  const initialStateFilterInput = initialFilterInput ?? {};
  const [userFilterInput, setUserFilterInput] = useState<UserFilterInput>(initialStateFilterInput);
```

2022-11-08 14:55 UTC, patcon commented on frontend/admin/src/js/components/searchRequest/SingleSearchRequestTable.tsx
> +const transformFilterToInput = (
```suggestion
const transformPoolCandidateFilterToFilterInput = (
```

2022-11-08 14:55 UTC, patcon commented on frontend/admin/src/js/components/searchRequest/SingleSearchRequestTable.tsx
> +    ? transformFilterToInput(filter)
```suggestion
    ? transformPoolCandidateFilterToFilterInput(filter)
```

2022-11-08 14:56 UTC, patcon commented on frontend/admin/src/js/components/searchRequest/SingleSearchRequestTable.tsx
> +const transformApplicantFilterToApplicantFilterInput = (
```suggestion
const transformApplicantFilterToFilterInput = (
```

2022-11-08 15:33 UTC, tristan-orourke commented
@petertgiles I love the translation check! This line is the kind of error message we should never expect to ever be seen, so I just put it through Deepl.

2022-11-08 15:34 UTC, tristan-orourke commented on frontend/admin/src/js/components/searchRequest/SingleSearchRequest.tsx
>    // TODO: data filter data from applicantFilter instead of poolCandidateFilter if possible.
Yes it can!

2022-11-08 15:36 UTC, yonikid15 commented
> @yonikid15 the searchApplicants query was a leftover from previous implementation - no need to test it if I can delete it! 😝

Haha ya I forgot to remove that part of my comment. My bad 😆.

2022-11-08 15:49 UTC, patcon commented
Some naming suggestions that basically follow this recco:

no more things in this format, and instead use => this:
- `fooToFooInput` => `transformXFooToFooInput` (use verb and explicit X)
- `fooInputToFoo` => `transformXFooInputToFoo` (use verb and explicit X)
- `transformXFooToXFooInput` => `transformXFooToFooInput` (X implied same)
- but keep this fully explicit: `transformXFooToYFoo` => explicitly change type

Considered (as discarded) idea of suggesting a different verb for different change types, like:
- `transform` for changes between input and non-input: `transformXFooToFooInput` or `transformXFooInputToFoo`
- `transpose` for changes between types: `tranposeXFooToYFoo`

Seems too premature, but the sort of thinking we could create language for as we extract these things into named functions :)

2022-11-08 15:56 UTC, tristan-orourke commented
@petertgiles whether its fixed in this PR or another, please take a look into that discrepancy 🙏 . But to make sure you're not wasting your time, first check if its caused by https://github.com/GCTC-NTGC/gc-digital-talent/issues/4557 or https://github.com/GCTC-NTGC/gc-digital-talent/issues/4660.

2022-11-08 16:06 UTC, patcon commented
#todo create ticket to improve seeders

2022-11-08 18:33 UTC, petertgiles commented
> whether its fixed in this PR or another, please take a look into that discrepancy

OK, I did the analysis. In this case, the discrepancy was from missing the "would accept temporay" issue that Matt is working on in  #4659.

I did notice some other concerning things though:
- The search page is sending a request for a given number of _pool candidates_ but the admin request page is showing a list of _users_ that match the filters which would be the same for a single pool, usually, I think, but it's weird.
- The requests page also had the "is profile complete" logic.  In theory a user couldn't have a pool candidate match returned if their profile wasn't yet complete but it's just weird.

2022-11-08 18:48 UTC, petertgiles commented
By the way, not sure why the Actions aren't running but this branch isn't building right now for me.
![image](https://user-images.githubusercontent.com/8978655/200649826-aa4437b4-8cd3-4078-a751-b3d7dd2b40b0.png)

2022-11-09 14:07 UTC, petertgiles approved these changes
In my testing I'm continuing to get discrepancies but they're all around language ability which was fixed in #4660 (but I don't think this branch includes) and the wouldAcceptTemporary fixed in #4659 but is not yet merged.  There's a lot of noise but I think this works.  :smile:

2022-11-09 14:08 UTC, petertgiles commented
> Frankly, using UserTable right now is a shortcut, just so we can deploy ASAP.

Fair enough.  Is that needed work represented on the board somewhere?

2022-11-09 14:13 UTC, tristan-orourke commented
Made a ticket for changing it to a list of PoolCandidates #4672

2022-11-09 14:13 UTC, merged