Bug - Search page queries
GCTC-NTGC/gc-digital-talent pull request #4686
Opened 2022-11-09 21:18 UTC by yonikid15

Resolves #4557 

## Notes
- Alright, I believe the solution was filtering by the [available users in pools](https://github.com/GCTC-NTGC/gc-digital-talent/blob/bug/4557-search-page-queries/api/app/Models/User.php#L260-L283) in the CountPoolCandidatesByPool query builder. This ensures the pool candidates are QUALIFIED_AVAILABLE or PLACED_CASUAL, and ensures the pool candidate hasn't expired. 
```php
    public static function filterByAvailableInPools(Builder $query, ?array $poolIds): Builder
    {
        if (empty($poolIds)) {
            return $query;
        }
        $poolFilters = [];
        foreach ($poolIds as $index => $poolId) {
            $poolFilters[$index] = [
                'poolId' => $poolId,
                'expiryStatus' => ApiEnums::CANDIDATE_EXPIRY_FILTER_ACTIVE,
                'statuses' => [ApiEnums::CANDIDATE_STATUS_QUALIFIED_AVAILABLE, ApiEnums::CANDIDATE_STATUS_PLACED_CASUAL]
            ];
        }
        return self::filterByPools($query, $poolFilters);
    }
```

## Testing
- Go to [search page](http://localhost:8000/en/search) and fill out filters. View TOTAL number of candidates, and the number of candidates in each pool. The TOTAL number should never be greater than the sum of all the pool card totals. This is because one applicant can be found in multiple pools.
- Submit a request for candidates.
- Next, on the admin side check to see if the number of candidates is also correct. 
- Go to Requests table. Then click the request you created, scroll down to the table, and ensure that the correct number of candidates show up.

Please feel free to reach out to me for any help testing 🧪

2022-11-09 23:14 UTC, vd1992 commented
playing around with the failing test
first this change is needed, otherwise the randomly generated pool_candidate_status messes with things, need to restrict the status to QUALIFIED_AVAILABLE or PLACED_CASUAL

![image](https://user-images.githubusercontent.com/40485260/200961945-84ec55d7-918d-4860-bf39-d1f39125d3eb.png)

2022-11-09 23:17 UTC, vd1992 requested changes
the filtering by pools doesn't seem to work anymore, it returns all

![image](https://user-images.githubusercontent.com/40485260/200962556-db4f0281-74d6-4d39-8755-88682f7e0177.png)

2022-11-10 00:25 UTC, vd1992 commented
I can see that the shape of the input that goes into `User::filterByAvailableInPools()` is different from what goes into `PoolCandidate::filterByPools`

The former takes an an array of ids seen here

![image](https://user-images.githubusercontent.com/40485260/200969876-0baa94cf-0234-4bb5-b37a-4d33def9b770.png)

Whereas the latter takes an array of pool objects and pulls id from each object seen here

![image](https://user-images.githubusercontent.com/40485260/200969967-7d1b4dcb-7a49-45d0-b8dd-cc3d7edf79ad.png)

even accounting for that I still can't figure out why it isn't working 😵 

### CONCLUSION

the easiest alternative solution might just be to undo the change in pool filtering and just utilize this existing scope

![image](https://user-images.githubusercontent.com/40485260/200970391-0c05e237-78e4-426c-b7dd-5fdb8dd930de.png)

2022-11-10 14:13 UTC, yonikid15 commented
> ### CONCLUSION
> the easiest alternative solution might just be to undo the change in pool filtering and just utilize this existing scope
> 
> ![image](https://user-images.githubusercontent.com/40485260/200970391-0c05e237-78e4-426c-b7dd-5fdb8dd930de.png)

Okay, I think I finally figured it out. Thanks for the advice to use that scope. Previously, I thought that using `filterByAvailableInPools` was the solution, since it combines both the `expiryStatus` and the `poolCandidateStatus` in the query. However, I didn't take into account the `orWhereNull('expiry_date)` clause.

2022-11-10 15:04 UTC, petertgiles requested changes
Looking really good!  Just a few small things to check.

2022-11-10 15:08 UTC, petertgiles commented on api/app/Models/PoolCandidate.php
> +            ->orWhereNull('expiry_date');
Something like this:
https://stackoverflow.com/a/36372109/18246559

2022-11-10 17:09 UTC, yonikid15 commented on api/app/Models/PoolCandidate.php
> +            ->orWhereNull('expiry_date');
Thank you Peter 🙌! This solved everything 😆. It took a while to find out why this line was breaking the query. 

This `orWhereNull('expiry_date')` clause was causing the issue in the test `testPoolFilter` where the user was in multiple pools AND that user has at least ONE poolCandidate object that is valid (valid meaning QUALIFIED_AVAILABLE or PLACED_CASUAL and has  EXPRIRY_FILTER_ACTIVE). So, I believe the countPoolCandidatesByPool query would add that user to the other pools `candidateCount` even if the user wasn't valid.

2022-11-10 17:34 UTC, yonikid15 commented on api/app/GraphQL/Queries/CountPoolCandidatesByPool.php
> +        PoolCandidate::scopeExpiryFilter($queryBuilder, [ 'expiryStatus' => ApiEnums::CANDIDATE_EXPIRY_FILTER_ACTIVE ]);
Added back at the top in [f64b12e](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4686/commits/f64b12ef2f757322fe07a57bcbb6628057ce30bf)

2022-11-10 17:35 UTC, yonikid15 commented on api/tests/Feature/CountPoolCandidatesByPoolTest.php
> +        PoolCandidate::factory()->create($this->poolCandidateData($pool3, $user2, true, false));
Separate tests added in [80f379d](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4686/commits/80f379d5413d492c62404d68cd8439e7407ce3a3) 👍

2022-11-10 17:35 UTC, yonikid15 commented on api/app/Models/PoolCandidate.php
> +            ->orWhereNull('expiry_date');
Should be fixed by [f64b12e](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4686/commits/f64b12ef2f757322fe07a57bcbb6628057ce30bf)

2022-11-10 18:11 UTC, petertgiles approved these changes
Nice! :1st_place_medal:

2022-11-10 18:56 UTC, vd1992 approved these changes
removing myself as a blocker 😄

2022-11-10 19:17 UTC, merged