Bug/sql injection vul scan 3
GCTC-NTGC/gc-digital-talent pull request #484
Opened 2021-09-13 15:46 UTC by jaysonmc

Resolves #389

Adding migration to change column type to string in the DB (which GraphQL was already assuming was the case).

2021-09-13 15:49 UTC, jaysonmc commented
Also, the internet tells me where is no schema DSL for the DB::statement('ALTER TABLE users ALTER COLUMN id SET DEFAULT uuid_generate_v4();'); part, which is why it is not used there, and 'raw sql' is used instead

2021-09-14 14:10 UTC, tristan-orourke requested changes
I'm generally happy with this. A couple of minor points:
- I think you can more succinctly create the primary key with `$table->uuid('id')->primary();`
- Any particular reason why you didn't use [this function](https://www.postgresql.org/docs/current/functions-uuid.html), which is accessible without loading a module?

2021-09-14 14:45 UTC, jaysonmc commented
@tristan-orourke 

Good call on both fronts. Simplified two lines to one, and I didn't use that only because ... I did not know it existed. I have just blindly been using the other one for some time now. So, always happy to find a better way to do things! I removed the new dependency and used the function you recommended instead.

2021-09-14 14:57 UTC, tristan-orourke requested changes
One last thing. I just took another glance at [Eloquent docs](https://laravel.com/docs/8.x/eloquent#primary-keys), they say that models that don't use integer ids should specify that using `protected $keyType = 'string';`. I'm not sure what the consequence is exactly, but we should probably follow suit.

2021-09-15 14:33 UTC, jaysonmc commented
@tristan-orourke 

Added the requested line and fixed a bug in the migrations

2021-09-15 15:15 UTC, tristan-orourke approved these changes

2021-09-15 15:16 UTC, merged