Feature - 4857 - Self declaration form
GCTC-NTGC/gc-digital-talent pull request #4869
Opened 2022-11-22 16:54 UTC by esizer

## 👋 Introduction

This adds the Indigenous Self-Declaration form (in storybook) so it can eventually be added to a page and connected to the API.

## 🧪 Testing

1. Run storybook `npm run storybook --workspace=indigenousapprenticeship `
2. Navigate to the "Self-Declaration Form" story
3. Ensure the following scenarios:
     - Only the "Self Declaration" radio group appears on initial load
     - Disclaimer linking to browse page appears if not identified as Indigenous
     - Icon checkboxes appear after identifying as Indigenous
     - Icons light up when selecting a community
     - Chips appear when selecting a community
     - Dismissing chips removes check on community
     - If "Other" and any other option is selected together and alert appears and the "Other" chip is yellow
     - Dismissing alert changes chip to primary colour
     - First Nations status field appears if user identifies as First Nations
     - Signature and submit button only appear if identified as Indigenous and at least one community is selected

## 🤖 Robot Stuff

Resolves #4857

2022-11-25 20:40 UTC, yonikid15 requested changes
Awesome work Eric, your code is beautiful stuff 👍 
I'm still in the middle of the review, but I found a small problem with the SignAndContinue section of the form, which off the bat I'm not sure really sure of a simple fix. The submit button falls out of line, when an error is triggered. 

<img width="689" alt="image" src="https://user-images.githubusercontent.com/22059495/204053480-5039ef35-d3a7-487f-8492-77b156b7bfff.png">

2022-11-25 20:43 UTC, esizer commented
> I'm still in the middle of the review, but I found a small problem with the SignAndContinue section of the form, which off the bat I'm not sure really sure of a simple fix. The submit button falls out of line, when an error is triggered.

Yeah, I noticed that as well. I'll make a note of this and when I connect with @BrookeCameron we can discuss some solutions to this. I now the submit button was an issue that surfaced during the a11y testing (unrelated to this though)

2022-11-25 22:12 UTC, yonikid15 requested changes
I'm seeing the CommunitySelection component is not responsive.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/22059495/204059229-1bc23ce5-3a08-4446-9d6f-e84172448e70.png">

Should be an easy fix by reducing the padding/margin in mobile view.

However, everything else is looking really great Eric 👍. Like we discussed before, I agree that having a form with no submit button is weird. I'll review this again once those possible issues are addressed.

2022-11-28 17:49 UTC, esizer commented on frontend/indigenousapprenticeship/src/js/components/SelfDeclaration/utils.ts
> +    ],
Removed in [remove duplicate key in community map](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4869/commits/25635eeb8571735a8aa25f70849140dd1c7f02be)

2022-11-30 14:58 UTC, esizer commented on frontend/indigenousapprenticeship/src/js/components/SelfDeclaration/utils.ts
> +    ],
> I'm seeing the CommunitySelection component is not responsive.

@yonikid15 The form should now be good to look at on smaller screen sizes. Only think left is to finalize the copy and send off for translations 😃

2022-11-30 14:58 UTC, esizer commented
> I'm seeing the CommunitySelection component is not responsive.

@yonikid15 The form should now be good to look at on smaller screen sizes. Only think left is to finalize the copy and send off for translations 😃

2022-12-02 20:21 UTC, yonikid15 approved these changes
Looking great eric! Last thing are those translations and its good to go 👍

2023-01-23 21:04 UTC, mnigh requested changes
My review is mostly focused on grammar questions and suggestions but there are a few copy related questions as well that might need to asked to the author of the original English copy. 

⚠️ A warning on some of my suggestions, especially any changes to English `intl` strings: this will change the id and the `fr.json` equivalent id would also need to be changed.

2023-01-24 14:37 UTC, esizer commented on apps/web/src/components/SelfDeclaration/SignAndContinue.tsx
> +                "This Program is for First Nations, Inuit, and Métis peoples within the geographic boundaries of Canada.",
Updated in [grammar updates](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4869/commits/e7978738f9a515c5ad48598d0c3fdf25a1bf13a7)

2023-01-24 14:37 UTC, esizer commented on apps/web/src/components/SelfDeclaration/CommunitySelection.tsx
> +                "The Program is for First Nations, Inuit, and Métis peoples within the geographic boundaries of Canada. At a later step of the application process, you may be asked to provide proof t
Updated in [grammar updates](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4869/commits/e7978738f9a515c5ad48598d0c3fdf25a1bf13a7)

2023-01-24 14:37 UTC, esizer commented on apps/web/src/components/SelfDeclaration/SelfDeclarationForm.tsx
> +                "We recognize the importance of Indigenous voices in the federal government. The Program was designed in partnership with Indigenous peoples. By completing and signing the Indigenous
Updated in [grammar updates](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4869/commits/e7978738f9a515c5ad48598d0c3fdf25a1bf13a7)

2023-01-24 14:37 UTC, esizer commented on apps/web/src/components/SelfDeclaration/SelfDeclarationForm.tsx
> +                  '"I am not a member of an Indigenous group, and I would like to see other opportunities available to me"',
Updated in [grammar updates](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4869/commits/e7978738f9a515c5ad48598d0c3fdf25a1bf13a7)

2023-01-24 14:37 UTC, esizer commented on apps/web/src/lang/fr.json
> +      "defaultMessage": "« Auto-déclaration »",
Updated in [grammar updates](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4869/commits/e7978738f9a515c5ad48598d0c3fdf25a1bf13a7)

2023-01-24 14:37 UTC, esizer commented on apps/web/src/lang/fr.json
> +      "defaultMessage": "Autochtone selon la définition de ce programme :",
Updated in [grammar updates](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4869/commits/e7978738f9a515c5ad48598d0c3fdf25a1bf13a7)

2023-01-24 14:37 UTC, esizer commented on apps/web/src/pages/IAPHomePage/Dialog/DefinitionDialog.tsx
> +            defaultMessage: "Indigenous as defined for this program:",
Updated in [grammar updates](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4869/commits/e7978738f9a515c5ad48598d0c3fdf25a1bf13a7)

2023-01-24 14:57 UTC, mnigh requested changes
Might be out of scope, but I noticed the top left and right corners of the dialogs are not rounded though the [designs](https://www.figma.com/proto/IThJdlxAJqQPJyvX88hAG7/IAP-Honesty-Pledge?node-id=4521%3A20259&scaling=min-zoom&page-id=4521%3A20212&starting-point-node-id=4521%3A20259) are rounded on all corners:

## Screenshot
![Screen Shot 2023-01-24 at 09 48 51](https://user-images.githubusercontent.com/3046459/214327167-f1311173-32df-4eea-a9e6-6135f6d262be.png)

2023-01-24 14:57 UTC, mnigh commented on apps/web/src/lang/fr.json
>        "defaultMessage": " Ce programme s’adresse aux membres des Premières Nations, aux Inuits et aux Métis qui se trouvent au Canada. Lors d’une étape ultérieure de la procédure de demande, vous aur
Remove extra space
```suggestion
      "defaultMessage": "Ce programme s’adresse aux membres des Premières Nations, aux Inuits et aux Métis qui se trouvent au Canada. Lors d’une étape ultérieure de la procédure de demande, vous aurez peut-être à fournir une preuve que vous êtes une personne autochtone. Vous pouvez en savoir plus sur la vérification de votre statut ci-dessous.",
```

2023-01-24 15:26 UTC, esizer commented on apps/web/src/components/SelfDeclaration/SelfDeclarationForm.tsx
> +            {intl.formatMessage(
Updated in [update dialog link colour](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4869/commits/dc44104bad137f9929a2641d05e51de9b60944fe)

2023-01-24 15:32 UTC, esizer commented on apps/web/src/pages/IAPHomePage/Dialog/VerificationDialog.tsx
> +              "At a later step of the application process, you may be asked to provide proof that you are Indigenous. Some of the ways to do this were included in the definition statement at the begi
Updated this in [fix Métis typo](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4869/commits/d86fa9919a4c6c2ac8466b5c1a0a3cd86ed9ca00) to make sure the ID was updated

2023-01-25 18:05 UTC, merged