Refactor user dialogs
GCTC-NTGC/gc-digital-talent pull request #4914
Opened 2022-11-24 20:02 UTC by petertgiles

# :wave: Introduction
The dialogs on the `/admin/users/:userId` page weren't working properly.  The forms were built using raw input partials and managing their own validation and navigation.  I factored them out into their own files and refactored them to use newer form components.

# :test_tube: Testing
![image](https://user-images.githubusercontent.com/8978655/203856194-3992e766-acf4-4a05-b87c-9c15e7f273e6.png)
- [ ] Interact with each of the three dialogs
  - [ ] Start off closed
  - [ ] Can open them by clicking triggers
  - [ ] Can cancel open dialogs
  - [ ] Client-side form validation works (and does not close dialog)
  - [ ] Server-side errors are displayed (and does not close dialog)
    - Try stopping the php container for easy server-side errors
  - [ ] Successful api mutation displays success message and closes the dialog

2022-11-24 21:25 UTC, esizer requested changes
Oh wow, this is awesome! I just had one small suggestion to improve the UX a bit :)

2022-11-24 21:25 UTC, esizer commented on frontend/admin/src/js/components/user/GeneralInformationTab/AddToPoolDialog.tsx
> +  const [, executeMutation] = useCreatePoolCandidateMutation();
Could we pop off `fetching` here and use it to disable the button and update the text content so the user knows something is happening?

> **Note**
> Applies to all three forms

```tsx
const [{ fetching }, executeMutation] = useCreatePoolCandidateMutation();

...

<Button disabled={fetching}>
  {fetching ? intl.formatMessage({
    defaultMessage: "Saving...",
  }) : intl.formatMessage({
     defaultMessage: "Add to new pool",
  })}
</Button>
```

2022-11-25 14:33 UTC, esizer approved these changes
Amazing 🤩

2022-11-25 14:56 UTC, merged

2022-11-25 15:57 UTC, yonikid15 commented
😆 Eric beat me to it