Bug/4908 draft pools policy changes
GCTC-NTGC/gc-digital-talent pull request #4915
Opened 2022-11-24 20:35 UTC by vd1992

closes #4908 
makes changes to policies in schema and some frontend tweaks
some places I skipped changing pool to pool advertisement like in graphql operation `getApplication` because it looks like it could be really risky

### **TESTING**
will be important to test real cautiously to avoid introducing bugs or other problems
issue estimate is higher to reflect this

### ADMIN
login as an admin
go to /admin and bounce around (focus on pool related operations)
nothing should have changed
go to /talentsearch and repeat
nothing should have changed

### APPLICANT 
login as an applicant
go to /talentsearch
nothing should have changed from the stuff you should be able to do
get the id of a draft pool and attempt to navigate to `localhost:8000/en/browse/pools/:id`
you should get the graphQL oh no! message

2022-11-24 23:15 UTC, vd1992 commented
few questions to resolve first, throwing back to in-progress
need to resolve what policy to put on `Pools`

2022-11-25 22:03 UTC, vd1992 commented on frontend/talentsearch/src/js/components/search/SearchContainer.tsx
> +  }, [searchFormData?.publishedPoolAdvertisements]);
this resolves draft pools appearing on /search
it also prevents `countPoolCandidatesByPool` query from looking at draft pools

2022-11-28 18:49 UTC, tristan-orourke requested changes
I've left one suggested change for the schema.

Also, I see that the PoolCandidate object in the schema has both a `pool` and a `poolAdvertisment` attribute. This means that anyone with a PoolCandidate object has access to that Pool, even if they shouldn't according to the PoolPolicy. I think we can remove `pool` entirely from PoolCandidate, and replace any frontend operations that use it with `poolAdvertisement` without any trouble.

2022-11-28 21:16 UTC, vd1992 commented
@tristan-orourke 
no I think that would definitely be troublesome as the Snapshot functions with `Pool` inside `PoolCandidate`
changing to PoolAdvertisement would break Snapshots

![image](https://user-images.githubusercontent.com/40485260/204382434-157beaa0-f8f5-4cd3-89d9-32cdec484faf.png)

2022-11-28 21:17 UTC, vd1992 commented
Snapshot creation comes from

![image](https://user-images.githubusercontent.com/40485260/204382764-bf1f6305-05d3-4098-9199-1d0b3982e773.png)

snapshot test comes from

![image](https://user-images.githubusercontent.com/40485260/204382864-52e30a82-849a-45b5-bc13-1209656b968c.png)

2022-11-28 21:52 UTC, tristan-orourke commented
Ah, good point, Vachan. We'll leave the pool on PoolCandidate for now.

2022-11-28 22:07 UTC, vd1992 commented on api/graphql/schema.graphql
>    poolByKey(key: String! @eq): Pool @find
https://github.com/GCTC-NTGC/gc-digital-talent/pull/4915/commits/3e9c8be603c8b633a9719a8a56dd1dbc1c61c88c

2022-11-29 19:30 UTC, tristan-orourke requested changes
Awww, I found an issue :(
If I log in as an applicant and try to view a draft pool, I get the graphql error.
However, if I logout and try to view the draft pool as a guest... it works 😆

2022-11-30 16:37 UTC, petertgiles commented
It did prevent me from viewing the pool, but the policy is not working well.  Looks like a null dereferencing problem.
![image](https://user-images.githubusercontent.com/8978655/204855884-82771b2a-69f2-465e-bc81-6fdbaa1038d2.png)

2022-11-30 18:02 UTC, vd1992 commented
> It did prevent me from viewing the pool, but the policy is not working well. Looks like a null dereferencing problem. ![image](https://user-images.githubusercontent.com/8978655/204855884-82771b2a-69f2-465e-bc81-6fdbaa1038d2.png)

ah, it would probably be better to check if `$user` exists before calling methods on it
don't think it changes anything but here it is https://github.com/GCTC-NTGC/gc-digital-talent/pull/4915/commits/1c48bf013dde8965a22a211f32a874396e19ab30

2022-11-30 19:36 UTC, tristan-orourke commented
Yep, I can't reproduce either. It's good!

2022-11-30 19:36 UTC, tristan-orourke approved these changes

2022-11-30 20:02 UTC, merged