Improve session-timeout logout experience
GCTC-NTGC/gc-digital-talent pull request #5100
Opened 2022-12-12 15:58 UTC by tristan-orourke

2023-01-16 22:23 UTC, tristan-orourke commented
Resolved the main issue, and this is now working correctly! Leaving it as a draft because I still want to do a last bit of code cleanup.

2023-01-17 22:42 UTC, tristan-orourke commented
Okay, I think this is worth reviewing now. Here's how it works:

If your access token is stale, and refreshing doesn't work (probably because your refresh token is also stale - that means 4 hours afk) the AuthenticationContainer stores your current url in session storage, then triggers a logout. Logout may or may not send you to the SiC logout uri, and then sends you to our /logged-out page. Now the logged-out page checks for a stored url in session storage, and redirects you again if it exists.

It feels a little clumsy to me, and can be a little slow, since it involves a number of hard refreshes, and because the react app must load for the /logged-out page before the final redirect happens. However, I'm not sure how to improve this. I considered moving the redirect logic to the backend (like our /login api route), but we're already interested in moving the auth functionality more towards the frontend exclusively (https://github.com/GCTC-NTGC/gc-digital-talent/issues/4916).

2023-01-19 15:19 UTC, petertgiles commented
> It feels a little clumsy to me, and can be a little slow

I agree that this is worth revisiting after the auth library change since it might look quite different after that.  I believe there is an auth logout option that uses a hidden iframe rather than navigation there and back.  That would remove the navigation to SiC, the one back to logged-out, and the one back to the original location, too.

2023-01-19 15:21 UTC, petertgiles commented
> we just use `getMe` graphql queries. I'll record this as a bug in another issue.

Yeah, using `getMe` everywhere is not great, and now there's another reason to avoid it!  Should probably be relying on our context providers for this instead.

2023-01-19 15:25 UTC, petertgiles requested changes
This is working great for me!  It should really improve quality of life, I think.

Would you consider adding cypress tests to ensure we don't lose this in the upcoming auth change?  It looks like it is possible to manipulate localStorage from Cypress.  https://stackoverflow.com/a/50820733

I could be convinced to spin it off into another issue to avoid scope creep.  :smile:

2023-01-19 15:25 UTC, petertgiles commented on frontend/common/src/components/Auth/AuthenticationContainer.tsx
> +      sessionStorage.setItem(POST_LOGOUT_URI, postLogoutUri);
Nice!  Storing it in sessionStorage should help use with the two "go to login-info first" issues we put in the backlog yesterday!

2023-01-19 22:45 UTC, tristan-orourke commented
> > we just use `getMe` graphql queries. I'll record this as a bug in another issue.
> 
> Yeah, using `getMe` everywhere is not great, and now there's another reason to avoid it! Should probably be relying on our context providers for this instead.

Haha, I had the opposite response - I though `getMe` makes sense and we should remove the id from the url 😆. I've mentioned both options for discussion in a ticket https://github.com/GCTC-NTGC/gc-digital-talent/issues/5413.

2023-01-20 16:23 UTC, petertgiles commented
Will spin off an issue for testing.

2023-01-20 16:23 UTC, petertgiles approved these changes

2023-01-24 14:38 UTC, merged