Debt - 5133 - Remove roles salaries
GCTC-NTGC/gc-digital-talent pull request #5190
Opened 2022-12-21 16:39 UTC by esizer

🤖 Resolves #5133 

## 👋 Introduction

This removes the `expectedSalary`, `expectedClassifications` and `expectedGenericJobTitles` from the application and deprecates the fields in the API.

## 🕵️ Details

We no longer use these anywhere in the application so they are now redundant.

> **Note**
> Some references were left for compatibility reasons.

## 🧪 Testing

1. Refresh API `docker-compose run --rm maintenance bash refresh_api.sh`
2. Build frontend
    1. `npm run codegen --workspaces --if-present`
    2. `npm run production --workspace=admin --workspace=talentsearch`
3. Navigate to `/admin/users`
    1. [ ] Confirm classifications are gone from filters
    2. [ ] Confirm role and salary does not exist on view users
    3. [ ] Print a user and confirm expected role and salary does not appear
    4. [ ] Export CSV and confirm expected role and salary does not appear
5. Navigate to `/talent/profile`
    1. [ ] Confirm role and salary section does not appear
    2. [ ] Confirm you can still complete your profile
6. Create an application
    1. [ ] Confirm role and salary section does not appear
    2. [ ] Confirm you can complete the application with no role and salary expectations

2022-12-22 17:29 UTC, mnigh commented
@tristan-orourke is this meant to be reviewed or should it be moved into the product backlog?

2022-12-22 18:19 UTC, tristan-orourke commented
@mnigh This should be reviewed, unless there's something I'm missing.

2022-12-22 18:22 UTC, mnigh commented
> @mnigh This should be reviewed, unless there's something I'm missing.

@tristan-orourke I wasn't sure, based on the discussion with Gray earlier today about possibly not doing this.

2023-01-03 16:12 UTC, patcon commented
gray: decision was to merge, but then not deploy until ready.

2023-01-05 19:21 UTC, petertgiles approved these changes
Looks good to me!  I found a few bugs but they preexisted this branch. :smile:

2023-01-05 19:25 UTC, esizer commented on frontend/admin/src/js/components/poolCandidate/usePoolCandidateCsvData.tsx
> -      label: intl.formatMessage({
How do I do that? 😅

2023-01-05 19:37 UTC, esizer commented on frontend/admin/src/js/components/poolCandidate/usePoolCandidateCsvData.tsx
> -      label: intl.formatMessage({
Thanks, I thought this was done in the CI. Wasn't aware we had to do it!

2023-01-05 19:43 UTC, petertgiles commented on frontend/admin/src/js/components/poolCandidate/usePoolCandidateCsvData.tsx
> -      label: intl.formatMessage({
Hmm, that would be a good improvement to the translation check CI.  :thinking: I'll throw something up on the board.

2023-01-05 19:45 UTC, esizer commented on api/storage/app/lighthouse-schema.graphql
> +  expectedSalary: [SalaryRange] @deprecated(reason: "Expected role\/salary being removed")
Created https://github.com/GCTC-NTGC/gc-digital-talent/issues/5290

2023-01-05 19:57 UTC, esizer commented on api/tests/Feature/ApplicantTest.php
> +                            'hasDiploma' => null,
Fixed in [run php-cs-fixer](https://github.com/GCTC-NTGC/gc-digital-talent/pull/5190/commits/1803c4649264ee803908495c8d09c7f2f0e1e874)

2023-01-05 19:58 UTC, esizer commented on frontend/admin/src/js/components/poolCandidate/usePoolCandidateCsvData.tsx
> -      label: intl.formatMessage({
Lots of red now lol

[prune translation files](https://github.com/GCTC-NTGC/gc-digital-talent/pull/5190/commits/432bd8ab4704b4da461efa54e18489edd5d56aed)

2023-01-05 20:26 UTC, merged

2023-01-05 20:27 UTC, yonikid15 requested changes
Excellent work Eric!

I got a couple more things to remove: [`RoleSalarySection.tsx`](https://github.com/GCTC-NTGC/gc-digital-talent/blob/feature/5125-add-skills-info-pool-candidates-csv/frontend/common/src/components/UserProfile/ProfileSections/RoleSalarySection.tsx#L88)

https://github.com/GCTC-NTGC/gc-digital-talent/blob/feature/5125-add-skills-info-pool-candidates-csv/frontend/common/src/components/UserProfile/UserProfile.stories.tsx#L84-L85

2023-01-05 20:35 UTC, esizer commented
> Looks like I was too late. I can remove that last file in my PR if you want?

Oh, so sorry. I merged a little too early. That would be great if you could 😜