Fix admin workflows cypress test
GCTC-NTGC/gc-digital-talent pull request #5354
Opened 2023-01-16 23:04 UTC by yonikid15

2023-01-16 23:45 UTC, yonikid15 commented
I'm not sure why this is happening yet, but the problem seems to be cypress redirecting back to the users table (line 365 in image) with all the filters data from the `searchForUser()` command:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/22059495/212780919-cf104ac4-f6c7-44e1-aa35-a349fad5cc7d.png">

2023-01-17 19:55 UTC, mnigh commented
@yonikid15 can you create an issue and attach it to this PR so we can track what you are trying to fix?

2023-01-18 15:11 UTC, mnigh requested changes
Nice work @yonikid15! A few suggestions and one question but happy to see the e2e workflow is passing again.

2023-01-18 15:11 UTC, mnigh commented on apps/e2e/cypress/e2e/admin/admin-workflows.cy.js
> +      .should('be.visible')
```suggestion
      .should("be.visible")
```

2023-01-18 15:11 UTC, mnigh commented on apps/e2e/cypress/e2e/admin/admin-workflows.cy.js
> +      .should('be.visible')
```suggestion
      .should("be.visible")
```

2023-01-18 15:11 UTC, mnigh commented on apps/e2e/cypress/e2e/admin/admin-workflows.cy.js
> +  it("Tests fancy filter is present and triggers graphQL", () => {
```suggestion
  it("Opens filter dialog and triggers GraphQL query", () => {
```

2023-01-18 15:11 UTC, mnigh commented on apps/e2e/cypress/e2e/admin/admin-workflows.cy.js
> +    // tests fancy filter is present and triggers graphQL
```suggestion
```

2023-01-18 16:51 UTC, yonikid15 commented on apps/e2e/cypress/e2e/admin/admin-workflows.cy.js
> +    // find the applicant user to review
No this is needed, this takes the bot to the Users table before testing the dialog

2023-01-18 17:27 UTC, mnigh approved these changes
🚀

2023-01-18 18:38 UTC, merged