documentation/5337-cookies-documentation
GCTC-NTGC/gc-digital-talent pull request #5382
Opened 2023-01-18 19:01 UTC by vd1992

🤖 Resolves #5337 

## 👋 Introduction

Adds documentation for existing cookies on the live site.

## 🕵️ Details

Read from here onward https://github.com/GCTC-NTGC/gc-digital-talent/issues/5337#issuecomment-1387470191 for more information, including various pictures/answers.
Some of these cookies may be disabled later.

2023-01-18 22:06 UTC, mnigh reviewed
Good start! Not sure if this meets the acceptance criteria of listing whether or not we control each cookie or not though.

2023-01-18 22:06 UTC, mnigh commented on documentation/cookies.md
> +This is a cookie controlled by Microsoft Azure. Its purpose is directing clients to specific instances.
```suggestion
This is a cookie controlled by Microsoft Azure. Its purpose is to direct clients to specific instances. 
```

2023-01-18 22:06 UTC, mnigh commented on documentation/cookies.md
> +Additional [reading.](https://azure.microsoft.com/en-us/blog/disabling-arrs-instance-affinity-in-windows-azure-web-sites/)
```suggestion
[Additional information](https://azure.microsoft.com/en-us/blog/disabling-arrs-instance-affinity-in-windows-azure-web-sites/).
```

2023-01-18 22:06 UTC, mnigh commented on documentation/cookies.md
> +Further [reading.](https://support.f5.com/csp/article/K6850)
```suggestion
[Additional information](https://support.f5.com/csp/article/K6850).
```

2023-01-18 22:06 UTC, mnigh commented on documentation/cookies.md
> +This cookie is also controlled by Microsoft Azure. It's similar in purpose to ARRAffinity, but works with a relatively new SameSite browser attribute.
```suggestion
This cookie is also controlled by Microsoft Azure. It is similar in purpose to `ARRAffinity`, but works with a relatively new `SameSite` browser attribute.
```

2023-01-18 22:17 UTC, vd1992 commented
> Good start! Not sure if this meets the acceptance criteria of listing whether or not we control each cookie or not though.

how complete things are for this issue is a bit abstract 🤔 

I think we control or can control the Azure one, per this stack overflow answer, though can't say for sure
![image](https://user-images.githubusercontent.com/40485260/213307366-5b3885f1-048e-4a5e-b10d-34aff42037cf.png)


the F5 one I think probably comes from infrastructure and that's IMTD right?
control of that one 🤷

2023-01-19 00:09 UTC, vd1992 commented
the ASM thing appears to be like a firewall, and therefore should definitely be an infrastructure and security sort of thing

2023-01-19 15:44 UTC, petertgiles commented
Yeah, F5 is a load-balancer/firewall network tool.  Same story as the process Gray is going through to tweak the admin-blocking error: Jira ticket to IMTD to request configuration changes.

2023-01-19 15:47 UTC, petertgiles approved these changes
Interesting read!  Thanks for the links.

2023-01-19 16:11 UTC, mnigh submitted a review, later dismissed
👍

2023-01-19 17:08 UTC, mnigh requested changes
We need to list all the cookies on prod, not just ones with warnings (as per the acceptance criteria).

2023-01-19 18:39 UTC, vd1992 commented
> We need to list all the cookies on prod, not just ones with warnings (as per the acceptance criteria).

hmm yeah, true
further cookies documented here https://github.com/GCTC-NTGC/gc-digital-talent/pull/5382/commits/c5c6d23b0775f6fbde4844d26d1b75232d013faa

/admin side I cannot check

2023-01-19 19:55 UTC, mnigh commented
> > We need to list all the cookies on prod, not just ones with warnings (as per the acceptance criteria).
> 
> hmm yeah, true, you're right further cookies documented here [c5c6d23](https://github.com/GCTC-NTGC/gc-digital-talent/commit/c5c6d23b0775f6fbde4844d26d1b75232d013faa)
> 
> /admin side I cannot check

I also cannot check the `/admin` cookies either and not sure if any additional cookies are set there anyway (not sure who has admin access to prod, @petertgiles?), though we do have some that are set after logging in on the frontend that should probably be documented:

1. gc_digital_talent_session
2. WNYQzIzpI7ZOsRdTyz9OzRnbE03WCnoEUE...
3. XSRF-TOKEN

## Screenshot
![Screen Shot 2023-01-19 at 14 49 11](https://user-images.githubusercontent.com/3046459/213545630-9cfad71b-507d-4397-9830-162ff6532b12.png)

2023-01-19 20:00 UTC, vd1992 commented
right, I didn't want to create a prod login and pollute the user base with too many testing ones

session
XSRF
and the keyboard masher one

will look into them

2023-01-19 23:47 UTC, vd1992 commented
with some help from peter and advice, got some further documentation progress done
https://github.com/GCTC-NTGC/gc-digital-talent/pull/5382/commits/2088f79b499bb6201bfa005196170eac08019d6c and https://github.com/GCTC-NTGC/gc-digital-talent/pull/5382/commits/1fa05567195764deff5de1d2396748888c955fcb

I think the mystery cookie is figured out now, here is some further detail if you want it

![image](https://user-images.githubusercontent.com/40485260/213587032-ba9766a2-9e9b-4463-be16-2fb8800f5194.png)

2023-01-20 15:18 UTC, mnigh reviewed
Thanks for adding the additional cookies 🍪.

To make it a bit easier to read and make it clear whether we "own" it or not, could you format each cookie, something like the following (I am very open to other formatting if other folks have an opinion):

## Cookie name
### Source: _Internal_ or _External_
Paragraph description of the source and purpose of the cookie.
- [Additional information](#)

2023-01-20 15:18 UTC, mnigh commented on documentation/cookies.md
> +## long alphanumeric string cookie, 40 character length
```suggestion
## _long alphanumeric string_, (40 character length)
```

2023-01-20 15:18 UTC, mnigh commented on documentation/cookies.md
> +May be controlled in Azure settings at `Settings -> Configuration -> General Settings -> Platform Settings`.
```suggestion
May be controlled in Azure settings at `Settings > Configuration > General Settings > Platform Settings`.
```

2023-01-20 15:27 UTC, esizer commented
> To make it a bit easier to read and make it clear whether we "own" it or not, could you format each cookie, something like the following (I am very open to other formatting if other folks have an opinion):

I personally like this format, makes it very clear when the cookie is internal or external and highlights the more info link 👍

2023-01-20 16:27 UTC, merged