Feature - 5366 - Changes pagination `pageSizes` options
GCTC-NTGC/gc-digital-talent pull request #5517
Opened 2023-01-26 21:25 UTC by mnigh

🤖 Resolves #5366.

## 👋 Introduction

This PR changes the pagination options for items per page from `10, 20, 30, 40, 50` to `10, 20, 50, 100, 500`.

## 🕵️ Details

Technically speaking, a user can already control the items per page via a url query parameter (ex. `/admin/users?pageSize=1000`) though there is a limit on two of the queries:

### `usersPaginated`
https://github.com/GCTC-NTGC/gc-digital-talent/blob/aa89339bf525d760050427d7da7057ffe03798c6/api/graphql/schema.graphql#L812

### `poolCandidatesPaginated`
https://github.com/GCTC-NTGC/gc-digital-talent/blob/aa89339bf525d760050427d7da7057ffe03798c6/api/graphql/schema.graphql#L866

## 🧪 Testing

1. Navigate to `/admin/pools`
2. Interact with the pagination select element in the table footer
3. Ensure it functions as expected
4. Navigate to `/admin/users`
5. Interact with the pagination select element in the table footer
6. Ensure it functions as expected

## 📸 Screenshot

![Screen Shot 2023-01-26 at 16 24 02](https://user-images.githubusercontent.com/3046459/214953821-0482c687-48e7-4ec1-93e3-a116c5c1ff82.png)

2023-01-26 21:56 UTC, vd1992 requested changes
uh-oh

this query (total 189 users selected)

![image](https://user-images.githubusercontent.com/40485260/214959347-2da8543b-4aaf-4424-9bf9-d3771ae1393b.png)

results in

![image](https://user-images.githubusercontent.com/40485260/214959461-4a8ec277-3e15-4ee5-b902-4f0e5b2c2ad4.png)

2023-01-27 15:44 UTC, brindasasi commented
https://laravel.com/docs/9.x/queries#chunking-results this might help ?

2023-01-27 16:29 UTC, petertgiles commented
Solution: try to solve lazy-load then re-evaluate issue.

2023-01-30 17:12 UTC, esizer commented
I'm still running out of memory when I attempt to select all users when having a page size of 500 😢 

```sh
[2023-01-30 17:04:32] local.INFO: GraphQL Error: Attempted to lazy load [awardExperiences] on model [App\Models\User] but lazy loading is disabled.  
[2023-01-30 17:04:32] local.ERROR: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4198400 bytes) {"userId":"222ca041-3842-4b29-91b1-ed47bd01b2b6","exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Allowed memory size of 134217728 bytes exhausted (tried to allocate 4198400 bytes) at /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Http/Response.php:106)
```

2023-01-30 17:26 UTC, mnigh commented on api/graphql/schema.graphql
> +  experiences: [Experience] @with(relation: "awardExperiences") @with(relation: "communityExperiences") @with(relation: "educationExperiences") @with(relation: "personalExperiences") @with(relation:
Oops, I thought that wasn't needed but it definitely is.

[Add hasMany directive for Applicant type *-Experiences](https://github.com/GCTC-NTGC/gc-digital-talent/pull/5517/commits/451740c14dfcbe3fe8ee3d1ee273fab9fef605ac)

2023-01-30 17:50 UTC, petertgiles commented on api/graphql/schema.graphql
> +  experiences: [Experience] @with(relation: "awardExperiences") @with(relation: "communityExperiences") @with(relation: "educationExperiences") @with(relation: "personalExperiences") @with(relation:
Probably worth adding the `with`s on the User type as well?

2023-01-30 18:01 UTC, mnigh commented on api/graphql/schema.graphql
> +  experiences: [Experience] @with(relation: "awardExperiences") @with(relation: "communityExperiences") @with(relation: "educationExperiences") @with(relation: "personalExperiences") @with(relation:
Ok, that makes sense.

[Add with directives for User type experiences](https://github.com/GCTC-NTGC/gc-digital-talent/pull/5517/commits/e55fd86bf75ac1aeef15b590bd30418c02b8924c)

What about here `Skill` type, should they be added there as well?
https://github.com/GCTC-NTGC/gc-digital-talent/blob/b2820b3644aa1335a2a909c43825e905925dcf72/api/graphql/schema.graphql#L587

2023-01-30 18:45 UTC, vd1992 commented
no more out of memory for 190 users
noticing the selectedUsers operations gets quite slower if you try and grab larger and larger user sets, something to watch out for later

are there any other concerns present with this now?

2023-01-30 19:06 UTC, vd1992 approved these changes
my issue is resolved, nice!
don't know if anyone else has some concerns that merit holding things up

2023-01-30 19:07 UTC, mnigh commented
> are there any other concerns present with this now?

just waiting on feedback from @petertgiles on [this question](https://github.com/GCTC-NTGC/gc-digital-talent/pull/5517#discussion_r1090970048) and then once  would be great for @esizer and @petertgiles to re-review to make sure the changes to the schema haven't 💥 anything unintentional.

2023-01-30 19:13 UTC, petertgiles commented on api/graphql/schema.graphql
> +  experiences: [Experience] @with(relation: "awardExperiences") @with(relation: "communityExperiences") @with(relation: "educationExperiences") @with(relation: "personalExperiences") @with(relation:
I think it probably will but it's out of scope for this issue.  If you're up for it, tag a quick issue on the board for it.

2023-01-30 19:15 UTC, mnigh commented on api/graphql/schema.graphql
> +  experiences: [Experience] @with(relation: "awardExperiences") @with(relation: "communityExperiences") @with(relation: "educationExperiences") @with(relation: "personalExperiences") @with(relation:
Stub issue created: https://github.com/GCTC-NTGC/gc-digital-talent/issues/5529

2023-01-30 19:20 UTC, petertgiles commented
I've seed 500 users into my database and when I try to select them all I'm getting a 500 with no error message.  I'm going to poke at it a bit and see if I can figure out where's it's coming from and if it's something we can reasonably address this sprint.

2023-01-30 19:29 UTC, vd1992 commented
> I've seed 500 users into my database and when I try to select them all I'm getting a 500 with no error message. I'm going to poke at it a bit and see if I can figure out where's it's coming from and if it's something we can reasonably address this sprint.

when I tried to push user select count to 350, it was failing on me due to the operation taking so long laravel cancelled it (30 second timeout)
which is why I raised the point above, but figured things are slower on my device so it may not be a prod problem anytime soon

2023-01-30 19:31 UTC, petertgiles commented
> when I tried to push user select count to 350, it was failing on me due to the operation taking so long laravel cancelled it (30 second timeout)

:laughing: Yeah, mine managed to run out of memory before 30 seconds. 
> FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 421

I'm inclined to say we've pushed this one as far as we reasonably can in this issue.

2023-01-30 19:31 UTC, petertgiles approved these changes
:+1:

2023-01-30 19:33 UTC, esizer approved these changes
Going to side with @petertgiles here. I think the selection can wait until a different issue.

2023-01-30 19:35 UTC, petertgiles commented
I think the next stop on this path would be to switch some sort of "we'll notify you when your file is ready to be downloaded" system.  And I'm not sure we want to go there...

2023-01-30 20:16 UTC, merged