Feature -  5042 - Themed Accordions
GCTC-NTGC/gc-digital-talent pull request #5553
Opened 2023-01-31 21:15 UTC by esizer

🤖 Resolves #5042

## 👋 Introduction

This updates the accordions to allow choosing a mode (simple, card) to use.

## 🕵️ Details

### ❗ Nested Accordion Issues

There are some issues with nesting the accordions right now. The issue is, the nested accordions are inheriting the styles from the root accordion so when we nest the card styles, we cannot use simple accordions inside. This may be my lack of experience with hydrogen. 

I'm not sure how often we nest accordion and the priority of getting this working, do we have the time for me to get some assistance form @substrae on this? Or, do we want to break out the nested accordion styles into a new issue and sort that out at a later time once they have been completed?

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Run storybook `npm run storybook`
2. Navigate to the Accordion stories
3. Confirm they match the provided designs https://github.com/GCTC-NTGC/gc-digital-talent/discussions/5522

## 📸 Screenshot

### Card

<img width="1263" alt="Screenshot 2023-01-31 at 4 14 09 PM" src="https://user-images.githubusercontent.com/4127998/215884802-01e03e38-dfdb-48a8-9540-26c75855aa05.png">

### Simple

<img width="1267" alt="Screenshot 2023-01-31 at 4 14 22 PM" src="https://user-images.githubusercontent.com/4127998/215884845-d47abb06-ef47-4198-9a66-e5adb35bfdc4.png">

2023-02-01 01:22 UTC, substrae commented
Hmm, this shouldn't be a Hydrogen issue unless you're using the `:selectors[]` or `:children[]` and specifying selector values that are vague enough that they target the nested accordions too. I can't look at the code in the next few days, but if you can respond here with more specifics I might be able to help.

2023-02-01 13:15 UTC, esizer commented
> Hmm, this shouldn't be a Hydrogen issue unless you're using the `:selectors[]` or `:children[]` and specifying selector values that are vague enough that they target the nested accordions too. I can't look at the code in the next few days, but if you can respond here with more specifics I might be able to help.

That is exactly what we are doing here. The theme is set at the root and we use `:children[]` to select. I may need to update to use more direct selectors like `:selectors[>.class]` to only target direct children rather than _any_ child 🤔

2023-02-01 15:47 UTC, substrae commented
Yep, that would be my recommendation too. Same idea if we were applying regular ol' CSS.

2023-02-01 17:01 UTC, esizer commented
> Yep, that would be my recommendation too. Same idea if we were applying regular ol' CSS.

Thanks! That worked 🎉

2023-02-01 21:02 UTC, petertgiles requested changes
Wow, another work of art!  :exploding_head: 

I still think you should get a designer to review before merging.  Maybe Jerbo would be willing in Josh's absence?

One small thing to check below.

2023-02-01 21:05 UTC, petertgiles commented
@Jerryescandon would you be willing to provide a designer review in Josh's absence?
https://www.chromatic.com/component?appId=61e099a1bb1465003a73d3ce&csfId=components-accordion&buildNumber=4260&k=63da9ec1a06a8f8f9953fc63-1200-interactive-true&h=50&b=0

2023-02-01 21:43 UTC, Jerryescandon commented
Oh wao, big responsibility, Imma be as nitpicky as possible just to avoid letting Josh down. 

Number 1 nitpickiness is target area. I feel like its important for the full box to be clickable and theres a couple places where it aint. 🤔 
![chrome_jL3KtqKVLU](https://user-images.githubusercontent.com/16977254/216170047-8424749c-98ce-4197-ba9b-5f41fd767dbb.gif)

2023-02-01 22:06 UTC, Jerryescandon commented
Second nitpickyness is the space between items in the simple version. It should be doing 2 things, lowering the padding by half, and removing the space between the items. I think we are reducing the padding but it feels like the space between items is still there cause the list doesn't feel as small as it could be.

![image](https://user-images.githubusercontent.com/16977254/216174135-29e3c222-ba25-40f0-842b-407d01dfc2a8.png)


![image](https://user-images.githubusercontent.com/16977254/216174054-e41b609b-1f97-4170-8428-d7cf93f88490.png)

2023-02-01 22:09 UTC, Jerryescandon commented
That's all I can think of 👍

2023-02-02 13:35 UTC, petertgiles commented on frontend/common/src/components/Accordion/Accordion.tsx
>                <ChevronRightIcon
Looks amazing!  :medal_sports:

2023-02-02 13:36 UTC, petertgiles approved these changes

2023-02-02 15:59 UTC, merged