Debt - 5346 - Replace `react-helmet` with `react-helmet-async`
GCTC-NTGC/gc-digital-talent pull request #5606
Opened 2023-02-03 21:15 UTC by esizer

🤖 Resolves #5346 

## 👋 Introduction

Replaces `react-helmet` with `react-helmet-async` to avoid the unsafe mount error in react strict mode.

## 🕵️ Details

`react-helmet` has no seen any updates in a considerable amount of time and since we have added strict mode it has been throwing an unsafe mount error in the console in dev. This fixes that by replacing it with the forked version `react-helmet-async`

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Build dev `npm run dev`
2. Bounce around the app confirming the title and HTML lang still update
3. Confirm no unsafe mount error appears in console.

2023-02-03 23:54 UTC, vd1992 commented
I pushed that commit up in https://github.com/GCTC-NTGC/gc-digital-talent/pull/5606/commits/71241990f6d7fc54493accd29a653d90ae14e746
that asterisk is unliked by `npm install`, and figured, someone will have to end up pushing it up somewhere and might as well be me right now

2023-02-03 23:56 UTC, vd1992 requested changes
react-helmet is still present in apps/web, you got rid of it from /common
might as well get rid of it there too

https://github.com/GCTC-NTGC/gc-digital-talent/blob/71241990f6d7fc54493accd29a653d90ae14e746/apps/web/package.json#L43

2023-02-04 00:50 UTC, esizer commented
> that asterisk is unliked by `npm install`, and figured, someone will have to end up pushing it up somewhere and might as well be me right now

Thanks, it does that for me sometimes and im not sure why 😕 

> react-helmet is still present in apps/web, you got rid of it from /common
> might as well get rid of it there too

Good catch, i wasn't aware it was even installed there 😅 

[uninstall react-helmet](https://github.com/GCTC-NTGC/gc-digital-talent/pull/5606/commits/bc87a1466726afa286a367f26b3a522ce304acc9)

2023-02-06 15:59 UTC, vd1992 approved these changes

2023-02-06 15:59 UTC, merged