Feature 5730 profile page updates
GCTC-NTGC/gc-digital-talent pull request #5929
Opened 2023-03-14 14:22 UTC by petertgiles

🤖 Resolves #5730 
## 👋 Introduction

This branch updates the profile page with status icons on the sidebar and removes the status and experiences sections. 

## 🕵️ Details

The "profile complete" toast was also disabled since the section it referred to was removed.

The issue scope was expanded to removing the "available for opportunities" and "job looking status" query scopes in [this later discussion](https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1678387944415379) on Slack.  This required a bunch of test changes, too.

## 🧪 Testing

1. Log into the app as an applicant and review the profile page.
2. Manually make the profile complete and incomplete to observe the sidebar and toast changes. 
3. Flip the FEATURE_APPLICANT_DASHBOARD flag to false and confirm the page looks and behaves like before.
4. Search works OK (other than no longer filtering unavailable and inactive candidates).

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/8978655/225031303-7713ff34-bca9-4bfc-9800-a32d2b2ba280.png)

2023-03-14 14:59 UTC, esizer commented
Holy moly this is impressive! One tiny nit pick, can `apps/web/src/component/infoItem` directory use `PascalCase` 😅

2023-03-14 22:12 UTC, vd1992 commented
will need to update the users table as well at some point, spun off to its own issue maybe (not sure if an issue already exists) 

- remove the deprecated field from the table

![image](https://user-images.githubusercontent.com/40485260/225153716-c86d40d4-d30b-4882-a0f1-4820f63a46f6.png)

- update the filter (setting it doesn't break anything, it just does nothing now so should be removed in lockstep with this stuff)

![image](https://user-images.githubusercontent.com/40485260/225153888-94bb94d6-e3de-467a-acdb-3aeb4a793cdf.png)

2023-03-15 12:43 UTC, petertgiles commented
> will need to update the users table as well at some point, spun off to its own issue maybe (not sure if an issue already exists)

Good call.  I've added #5937 to the board.

2023-03-15 17:28 UTC, esizer requested changes
This is looking great! One sorta small suggestion for accessibility 😄

2023-03-15 17:28 UTC, esizer commented on apps/web/src/components/InfoItem/BaseInfoItem.tsx
> +            {title}
You likely don't want to read this but, can we indicate status to assistive technology in some way? Like prending hidden text?

```tsx
<span data-h2-visually-hidden="base(hidden)">Incomplete section, </span>{title}
 
<span data-h2-visually-hidden="base(hidden)">Completed section, </span>{title}
```

2023-03-16 12:38 UTC, esizer commented on apps/web/src/components/InfoItem/BaseInfoItem.tsx
> +            {title}
Nice! Sounds good to me 😄

2023-03-16 12:39 UTC, esizer approved these changes

2023-03-16 13:28 UTC, esizer commented on package.json
> +    "check-intl-merge:i18n": "turbo run check-intl --filter=@gc-digital-talent/i18n -- --dir $INIT_CWD --en ./packages/i18n/src/lang/en.json --fr ./packages/i18n/src/lang/fr.json --rm-orphaned --outp
🤦‍♀️ Oopsies!

2023-03-16 13:49 UTC, merged