[Feature] Application placeholder pages
GCTC-NTGC/gc-digital-talent pull request #6086
Opened 2023-03-24 21:20 UTC by esizer

🤖 Resolves #6027 

## 👋 Introduction

Adds the placeholder pages within a layout component with `Hero`, `Breadcrumbs` and `Stepper` component.

## 🧪 Testing

> **Note**
> In order to test this properly, you will need to add `preventDisble` on the `Stepper` component to easily go through each step unimpeded

1. Add `preventDissable` prop to `Stepper` component
2. Build app `npm run build`
3. Start an application
4. Update the url to `/applications/{applicationId}/welcome
5. Step through the pages ensuring the content that is there matches [the mock ups](https://www.figma.com/file/BXYVsu1fo9LS2IySJDUINY/Applicants---Job-application?node-id=636-59839&t=iIqEBZTRvzLwb9uT-0)

## 📸 Screenshot
![localhost_8000_en_applications_58bafc9c-4760-4750-a5cb-6375a86aed43_welcome](https://user-images.githubusercontent.com/4127998/227643742-5852da0f-aeba-487c-831d-d86b551234dd.png)

2023-03-29 20:28 UTC, tristan-orourke reviewed
I got a console error when clicking around between steps.
`Warning: Cannot update a component (`ApplicationApi`) while rendering a different component (`ApplicationApi`). To locate the bad setState() call inside `ApplicationApi`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render`

2023-03-29 20:44 UTC, esizer commented
> I got a console error when clicking around between steps.
> `Warning: Cannot update a component (`ApplicationApi`) while rendering a different component (`ApplicationApi`). To locate the bad setState() call inside `ApplicationApi`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render`

Were you just using the stepper to get to different pages or something else? I'm having trouble reproducing 😢

2023-03-29 20:59 UTC, tristan-orourke requested changes
I like your solution of putting /introduction at the end of the url as another segment. Makes sense, and makes determining the current step for the stepper nice and easy.

I think you're just missing one page for editing an existing experience - and the it needs to be added to Router as well, along with the add-experience url.

2023-03-30 13:06 UTC, esizer commented
> I like your solution of putting /introduction at the end of the url as another segment. Makes sense, and makes determining the current step for the stepper nice and easy.
> 
> I think you're just missing one page for editing an existing experience - and the it needs to be added to Router as well, along with the add-experience url.

Oops 😅, Looks like I also missed the add page. Added in [add missing resume pages](https://github.com/GCTC-NTGC/gc-digital-talent/pull/6086/commits/b817a8d296e69cbdaf6060d11de3859a2d7cda5b)

> I was just clicking on steps in the stepper when I got the error. But going back to reproduce, I get the error just by refreshing a single page. I suspect its a race condition which has something to do with having `<ApplicationApi>` at multiple levels. ApplicationLayout is wrapped in `<ApplicationApi>`, but so is each individual subpage.
> 
> Here's the full error log: [ApplicationApi error.log](https://github.com/GCTC-NTGC/gc-digital-talent/files/11105488/ApplicationApi.error.log)

Awesome, thanks! Turns out that is exactly what it was. I didn't realize I was wrapping the layout in it as well. Changing it to use cache first worked 👍  [update to use cache-first to avoid race-condition](https://github.com/GCTC-NTGC/gc-digital-talent/pull/6086/commits/02c56289e5d685b955a4df76ba9f5c8709484cdd)

2023-03-30 17:52 UTC, tristan-orourke requested changes

2023-03-30 18:17 UTC, esizer commented on apps/web/src/pages/Applications/ApplicationResumeAddPage/ApplicationResumeAddPage.tsx
> +    crumbs: [
I like this idea! 👍 Do you think we should do this with introduction pages as well? 🤔

2023-03-30 19:53 UTC, tristan-orourke commented on apps/web/src/pages/Applications/ApplicationResumeAddPage/ApplicationResumeAddPage.tsx
> +    crumbs: [
I'd leave the introduction pages as is. Going from the introduction page to the main step doesn't feel like going "back up" the hierarchy in the way implied by breadcrumbs.

2023-03-30 19:58 UTC, esizer commented on apps/web/src/hooks/useRoutes.ts
> +    applicationResumeEdit: (applicationId: string, experienceId: string) =>
Rwemoved in [remove unnecessary path segment](https://github.com/GCTC-NTGC/gc-digital-talent/pull/6086/commits/047bcf8e3ac12167b4547894ad65e3c4b6c9bb01) then fixed in the router in [remove route param from router](https://github.com/GCTC-NTGC/gc-digital-talent/pull/6086/commits/62b21444404ec13fe64b86b580065be65bded4e9)

2023-03-30 19:59 UTC, esizer commented on apps/web/src/pages/Applications/ApplicationResumeAddPage/ApplicationResumeAddPage.tsx
> +    crumbs: [
Sounds good, updated in [update resume page breadcrumbs](https://github.com/GCTC-NTGC/gc-digital-talent/pull/6086/commits/a201f7ee03df29fb03b9dafabd2b79c1e8086b46)

2023-03-30 19:59 UTC, esizer commented on apps/web/src/pages/Applications/ApplicationResumeEditPage/ApplicationResumeEditPage.tsx
> +    crumbs: [
Updated in [update resume page breadcrumbs](https://github.com/GCTC-NTGC/gc-digital-talent/pull/6086/commits/a201f7ee03df29fb03b9dafabd2b79c1e8086b46)

2023-03-30 20:58 UTC, tristan-orourke approved these changes
So... The error is still there, in development mode 😢 . But, since it's not present in production mode, and this is blocking other work, I say let's merge this and make another issue for the bug.

2023-03-30 21:35 UTC, tristan-orourke commented
https://github.com/GCTC-NTGC/gc-digital-talent/issues/6146

2023-03-31 13:07 UTC, merged