Feature - 6039 - intro to resume review
GCTC-NTGC/gc-digital-talent pull request #6261
Opened 2023-04-12 20:43 UTC by vd1992

🤖 Resolves #6039 

## 👋 Introduction

Update the intro to resume review page. 

## 🕵️ Details

Translations remaining
```
  "AOrJqm": {
    "defaultMessage": "Got it, let's go!",
    "description": "Link text to continue the application process"
  },
```

## 🧪 Testing

1. Create a draft application, update with  `"WELCOME", "REVIEW_YOUR_PROFILE"`
2. Head to `/en/applications/:id/resume/introduction`
3. Observe page
4. Run Storybook and ensure no errors

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/40485260/231579787-4ddba42f-5ca7-487d-8389-d0f1f8d22662.png)

2023-04-13 13:20 UTC, esizer requested changes

2023-04-13 15:01 UTC, esizer commented on apps/web/src/pages/Applications/ApplicationResumeIntroductionPage/ApplicationResumeIntroductionPage.tsx
> +            "More specifically, not only do we want to know your work history, but we highly value knowing about your community experience, awards, personal initiatives, and education too!",
It is highly subjective so it is hard to give a good answer. For this use case where we are using it to draw attention to specific terms, i'd say it is useful here 👍

2023-04-13 17:05 UTC, mnigh commented on apps/web/src/pages/Applications/ApplicationResumeIntroductionPage/ApplicationResumeIntroductionPage.tsx
> +            "More specifically, not only do we want to know your work history, but we highly value knowing about your community experience, awards, personal initiatives, and education too!",
Plus précisément, non seulement nous voulons connaître votre **parcours professionnel**, mais également votre **expérience communautaire**, vos **récompenses**, vos **initiatives personnelles** et votre **éducation**!

2023-04-13 17:37 UTC, vd1992 commented on apps/web/src/pages/Applications/ApplicationResumeIntroductionPage/ApplicationResumeIntroductionPage.tsx
> +            "More specifically, not only do we want to know your work history, but we highly value knowing about your community experience, awards, personal initiatives, and education too!",
Thanks!
🇫🇷

2023-04-14 14:51 UTC, esizer approved these changes
LGTM! 💪 Hopefully that translation comes in 🤞

2023-04-14 19:24 UTC, vd1992 commented
> LGTM! 💪 Hopefully that translation comes in 🤞

Got 'em!

![image](https://user-images.githubusercontent.com/40485260/232137415-274d3da5-ed94-4a42-8668-59ba8c1daf76.png)

![image](https://user-images.githubusercontent.com/40485260/232137453-02f003b7-f542-4501-b7fb-2334c0f74376.png)

2023-04-14 20:05 UTC, merged