[Debt] Remove PoolCandidateFilterInput and associated changes
GCTC-NTGC/gc-digital-talent pull request #6676
Opened 2023-05-23 20:21 UTC by vd1992

🤖 Resolves #5193

## 👋 Introduction

Removes the `PoolCandidateFilterInput` and related types, deprecated queries `countPoolCandidates` and `searchPoolCandidates`, testing for the types and queries involved, and rendering a special table for `PoolCandidateFilter` objects. 

## 🕵️ Details

Removing the above was mostly straightforward. Change to request table is that now if it is a `PoolCandidateFilter` instead of `ApplicantFilter`, it loads `<PoolCandidatesTable>` with an empty filter input. The specifics of the request are still on the page, just not loaded into the Fancy Filter by default. 

**NOTE**
The one change that stretched the scope a bit that I threw in, is in easily reversed commit https://github.com/GCTC-NTGC/gc-digital-talent/commit/49746f582bb31c5395489c3ac6a6ca01343e3706.
Basically, there were two expiry scopes present that do the same thing, I had to add the second in the past because the original was entangled in deprecated queries that are now removed. The new one is in a similar pattern to other scopes whereas the old one had a different structure, and due to being stuck in deprecated queries I could not update it without breaking deprecated queries. 
Now that the queries in question are being removed, I thought to sort out that bit and condense to one expiry scope.

## 🧪 Testing

1. Seeder still has `PoolCandidateFilter` requests, I think we should keep those for a bit for testing purposes
2. Navigate to `/en/admin/talent-requests`
3. Open requests of both filter types, observe page behaviour

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/218ca374-0dc9-4bf9-914d-a7881dc9d163)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/9d7e39ef-be22-41c4-aec5-898d41daedd8)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/2f8916b6-d3da-40bc-bac7-3021df167b61)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/b13086a1-79a2-4eb9-9279-69d42fa52a28)

2023-05-23 20:28 UTC, vd1992 commented on api/app/GraphQL/Queries/CountPoolCandidatesByPool.php
> +        PoolCandidate::scopeExpiryStatus($queryBuilder, ApiEnums::CANDIDATE_EXPIRY_FILTER_ACTIVE);
Form of the other expiry scope is the same as the suspended scope, not an array of one key/value pair. 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/044a97e1-54a9-4fa5-a9e0-29c4162216bb)

2023-05-23 20:41 UTC, vd1992 commented on api/graphql/schema.graphql
> +  applicantFilter: ApplicantFilterBelongsTo @rules(apply: ["required"])
Think this To Do is done too

2023-05-30 18:43 UTC, tristan-orourke requested changes
Looks good! The only other thing I'd suggest is that we can probably stop creating PoolCandidateFilters in DatabaseSeeder and PoolCandidateSearchRequestFactory. We've confirmed that the page can still work with them, but I think they're mostly cluttering our dev environments now.

2023-05-30 19:59 UTC, vd1992 commented
And now with passing tests!

2023-05-30 20:07 UTC, merged