[Accessibility] Fix improperly nested Chips
GCTC-NTGC/gc-digital-talent pull request #6820
Opened 2023-06-06 14:21 UTC by yonikid15

🤖 Resolves #6762 

## 👋 Introduction

- Ensures multiple, dismissible chips have the following HTML structure `list > listitem > button`

## 🧪 Testing

1. Open storybook and view Chips stories. Ensure there are no violations.
2. Ensure chips still look and feel the same on throughout site: SkillPicker, CommunitySelection, etc.

2023-06-06 14:30 UTC, esizer requested changes
Really cool solution. Just added a, hopefully small, suggestion 👍

2023-06-07 16:29 UTC, yonikid15 commented on packages/ui/src/components/Chip/Chips.tsx
>    </div>
😆 Ya I wasn't sure if that was intentionally there or not

2023-06-07 18:57 UTC, esizer requested changes
Looking good, just need to remove that bullet now 👍

2023-06-07 18:57 UTC, esizer commented on packages/ui/src/components/Chip/Chips.tsx
>    >
```suggestion
  <ul
    data-h2-display="base(flex)"
    data-h2-flex-wrap="base(wrap)"
    data-h2-gap="base(x.25, x.125)"
    data-h2-list-style="base(none)"
  >
```

2023-06-07 19:07 UTC, yonikid15 commented on packages/ui/src/components/Chip/Chips.tsx
>    >
Nice catch!

2023-06-08 12:54 UTC, esizer approved these changes
Nice! 🆒

2023-06-08 13:03 UTC, merged