[Featrure] Application snapshot resume section
GCTC-NTGC/gc-digital-talent pull request #7075
Opened 2023-06-22 13:51 UTC by yonikid15

🤖 Resolves #6928 

## 👋 Introduction

- Changes Resume section to use experience list without the tree view, on the application snapshot page.
- Adds a null state when no experiences are present (waiting on translations).

## 🧪 Testing

1. Login as admin and go to Pools table.
2. Select "View candidates" on a pool with candidates.
3. Select "View Application" on one of the pool candidates. Scroll down to Resume section.
4. Ensure section looks correct and all sorting works correctly.

2023-06-22 16:54 UTC, esizer requested changes
Much better! 🧑‍🍳 Just one minor suggestion while we wait for translations 😄

2023-06-22 16:54 UTC, esizer commented on apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ResumeSection/index.ts
We have an use to remove barrel exports like this so we should probably avoid introducing additional instances of it 😬

2023-06-27 14:51 UTC, yonikid15 commented on apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ResumeSection/index.ts
Okay I think I got it with [d5c75fb](https://github.com/GCTC-NTGC/gc-digital-talent/pull/7075/commits/d5c75fb2efdb03ab63f2730ea5beac8e3021fbbd)

2023-06-27 14:58 UTC, esizer approved these changes
LGTM! 👍

2023-06-27 19:55 UTC, merged