[Feature] Manager homepage
GCTC-NTGC/gc-digital-talent pull request #7238
Opened 2023-07-12 15:13 UTC by esizer

🤖 Resolves #6193 

## 👋 Introduction

Adds the manager homepage at `/manager`

## ✅ TODO

- [ ] Add translations

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Build `npm run dev`
2. Navigate to `/manager`
3. Confirm it matches [the mockup](https://www.figma.com/file/6Unzr74GyScHAxiAt5KyVR/Manager-Home-Page?type=design&node-id=463-17310&mode=design&t=J6c56SjgJkbtd6sp-0) and links go to correct locations

## 📸 Screenshot

![localhost_8000_en_manager](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/d77efd69-a844-4b38-9c96-0255964625b2)

2023-07-12 23:31 UTC, vd1992 requested changes
Looking great! A few small things

2023-07-12 23:31 UTC, vd1992 commented on apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
Missing a bit of spacing here and capitalizing "Fall"

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/943d4759-883d-4436-ac42-5664bc746a9e)


Per 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/fad3d0de-8d89-47d6-89c9-6d2cdcae94f7)

2023-07-12 23:31 UTC, vd1992 commented on apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
Spacing here too 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/791abf05-2305-48f2-9be8-f28b39195b46)

Per

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/eb84504a-72c4-459c-8125-38043e0d39a8)

2023-07-12 23:31 UTC, vd1992 commented on apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
Does the issue that resolves this exist? If so, it'd be good to mention the TODO there so it doesn't get missed when it is time

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/cb0b71f5-35c6-4ce4-9de1-23274454bfe1)

2023-07-12 23:31 UTC, vd1992 commented on infrastructure/conf/nginx-conf-local/default
I get this in the browser console every load. Is this an nginx issue or am I missing a step somewhere?
Page renders fine regardless. 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/290e98ab-4a2a-42b2-bbd5-461482a9b1c9)

2023-07-12 23:33 UTC, vd1992 commented
Oh, and one other thing. 
Looks good on the small/mobile view, except one bit looks a little odd. 
Is the big empty space under "Create a profile" intended?

https://recordit.co/UupIXLNr8O

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/8524626f-8a16-4f71-bd33-18a0a2d2340b)

2023-07-13 12:53 UTC, esizer commented on apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
So, the lowercase was on purpose to keep it sentence case, @mnigh does that makes sense?

2023-07-13 12:59 UTC, petertgiles commented on apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
I suggest adding an AC to the executive home page issue for this.

2023-07-13 13:00 UTC, petertgiles commented on infrastructure/conf/nginx-conf-local/default
Probably just a reload of the container, but yeah, if you changed the nginx config you'll need to restart nginx.

2023-07-13 13:55 UTC, mnigh commented on apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
I had previously suggested changing this along with removing the year, but it seems it wasn't accepted.

I think it should be sentence case and have a period at the end, including removing the newline at the end of the sentence. @BrookeCameron, is there a reason not to do this?

2023-07-13 13:58 UTC, BrookeCameron commented on apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
Lauren wanted to have an actual date, she didn't want it to be aloof as to when it is coming. She reviewed all this copy one on one in a couple of meetings with me - I think we should leave it.

2023-07-13 13:59 UTC, BrookeCameron commented on apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
and she wanted the new line as well so it aligned better with the rest of the copy block.

2023-07-13 14:01 UTC, BrookeCameron commented
> Oh, and one other thing. Looks good on the small/mobile view, except one bit looks a little odd. Is the big empty space under "Create a profile" intended?
> 
> https://recordit.co/UupIXLNr8O
> 
> ![image](https://user-images.githubusercontent.com/40485260/253122536-8524626f-8a16-4f71-bd33-18a0a2d2340b.png)

This copy should be left aligned, no centred

2023-07-13 16:03 UTC, esizer commented on apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
Thanks everyone, I have reverted it back to the original copy in the mockup 👍. Accidently rolled it into the following commit:

[fix spacing, small screen layout](https://github.com/GCTC-NTGC/gc-digital-talent/pull/7238/commits/5052380e3b625e5849d3ee5658773d834ff87b10)

2023-07-13 16:04 UTC, esizer commented on apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
Fixed a lot of the spacing along with the mobile and text alignment issues in [fix spacing, small screen layout](https://github.com/GCTC-NTGC/gc-digital-talent/pull/7238/commits/5052380e3b625e5849d3ee5658773d834ff87b10)

2023-07-13 16:06 UTC, esizer commented on apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
Great suggestion. Added to the AC of the exec home page ticket and updated the comment to make more sense.

[update to do comment, add context](https://github.com/GCTC-NTGC/gc-digital-talent/pull/7238/commits/936b9b3ff3f7ee11591bb75884eae3e446b6abd8)

2023-07-13 17:03 UTC, vd1992 approved these changes
💯

2023-07-13 19:45 UTC, petertgiles requested changes
This looks so, so good!  :artist:  I love the new reusable containers you made.

I noted a few things to check on below.

2023-07-13 19:45 UTC, petertgiles commented on apps/web/src/assets/img/people-sitting-on-couch-discussing-something.jpg
Is there any chance we can shrink these images while looking good?  Most of our hero images are around 110K.  These are about 250K and this one in particular is approaching 400K.

2023-07-13 19:45 UTC, petertgiles commented on apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
Looks like these links should be button style.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/c58403b3-d7ec-459b-9db1-e83bcf02d69b)

2023-07-13 19:45 UTC, petertgiles commented on apps/web/src/assets/img/manager-profile-hero.jpg
The alignment of this image is not great in mobile view.  Can this be improved?
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/4ee651dd-aff7-4ae5-bf3b-d3c4e31331d6)

2023-07-13 19:45 UTC, petertgiles commented on apps/web/src/pages/Home/HomePage/components/Featured/Featured.tsx
A new alignment problem shows up in the Chromatic diff for the GCDT home page.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/c92dcedf-dbfb-4347-b544-d7da52425a20)

2023-07-13 19:46 UTC, esizer commented on apps/web/src/assets/img/manager-profile-hero.jpg
I think we need a new image that places the focus more on the right 😢 @BrookeCameron Would this be possible?

2023-07-13 19:49 UTC, petertgiles commented
Sorry, one more thing.  Should the background of these containers be black to hide the edge of the photos?
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/1bf09f51-b924-483b-8b86-9c701bbfd00f)
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/8b7f4724-913e-47b8-832d-17ede0832403)

2023-07-13 19:50 UTC, petertgiles commented on apps/web/src/assets/img/manager-profile-hero.jpg
It should crop out all the black, anyway, right?

2023-07-13 19:52 UTC, esizer commented
> Sorry, one more thing. Should the background of these containers be black to hide the edge of the photos?

This has always been an issue with all of the images on our homepages 😢 I think we need to create a ticket to remove the gradient mask from the source images and do it with css instead 😬

2023-07-13 19:55 UTC, esizer commented on apps/web/src/assets/img/manager-profile-hero.jpg
I guess we could just do highly specific positioning, I did my best to make this a re-usable component but that might have been too optimistic based on the focal point slightly shifting for each image.

2023-07-13 19:56 UTC, esizer commented on apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
This one is tough because that is an existing component that appears on the current homepage. I can change it but I think we should at least be consistent in what both look like. @BrookeCameron is it the preference to use buttons instead of links now?

![Screenshot 2023-07-13 155554](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/aa81bdc7-1922-4c0e-bd13-0d045438a76b)

2023-07-13 19:57 UTC, petertgiles commented on apps/web/src/assets/img/manager-profile-hero.jpg
:crying_cat_face:

2023-07-13 20:16 UTC, esizer commented on apps/web/src/assets/img/manager-profile-hero.jpg
This has been updated to use specific positioning, should look much better on all screen sizes.

[fix image position on homepages](https://github.com/GCTC-NTGC/gc-digital-talent/pull/7238/commits/611d71afbc48c6c41576d5b0c91dc8be66e52df4)

2023-07-13 20:16 UTC, esizer commented on apps/web/src/pages/Home/HomePage/components/Featured/Featured.tsx
Fixed as part of [fix image position on homepages](https://github.com/GCTC-NTGC/gc-digital-talent/pull/7238/commits/611d71afbc48c6c41576d5b0c91dc8be66e52df4)

2023-07-13 20:19 UTC, esizer commented on apps/web/src/assets/img/people-sitting-on-couch-discussing-something.jpg
Good catch! Ran them through MozJPEG and got anywhere from 60-75% reduction 👍 

[reduce image file size](https://github.com/GCTC-NTGC/gc-digital-talent/pull/7238/commits/39e2bed67e32c10fbde9201ec651ec419ce5c475)

2023-07-13 20:22 UTC, petertgiles commented on apps/web/src/assets/img/people-sitting-on-couch-discussing-something.jpg
:superhero:

2023-07-13 20:48 UTC, petertgiles commented on apps/web/src/assets/img/manager-profile-hero.jpg
Looks great!

2023-07-13 20:49 UTC, petertgiles approved these changes

2023-07-14 14:31 UTC, BrookeCameron commented on apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
I'm fine with changing it to buttons if it means consistency!

2023-07-14 14:36 UTC, esizer commented
> Sorry, one more thing. Should the background of these containers be black to hide the edge of the photos?

So, @BrookeCameron and I got to the bottom of this. As you can probably tell even though hydrogen says "black", it's really just a dark shade of gray 😓 . Updated to use true black (`#000`) and it looks much better now! 😁

2023-07-14 19:02 UTC, merged