[Fix] Disabled form buttons while submitting
GCTC-NTGC/gc-digital-talent pull request #7318
Opened 2023-07-19 17:26 UTC by esizer

🤖 Resolves #7212 

## 👋 Introduction

Updates our form submit buttons to be disabled while submitting a form preventing duplicate submissions.

## 🕵️ Details

This is partly to do with misunderstanding surrounding `react-hook-form` and some older implementations of `BasicForm`. It seems `react-hook-form` wants `methods.handleSubmit` to be passed a function that returns a `Promise`. Most of our forms actually await thee promise and return nothing. In order to fix this, I added the `fetching` state from `urql` to the disabled prop as well where needed.

I believe it would be in our interest to review forms and get some sort of standard. Our `BasicForm` is a good starting point but this specific issue stemmed from how we defined the `onSubmit` so it may be worth standardizing how we write the `onSubmit` so we can rely more on `react-hook-form` state.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Build `npm run dev`
2. Navigate to forms, confirming that clicking submit it rapid succession does not double submit
3. Make sure you specifically test the "Add experience" form since that was the form that prompted the ticket

2023-07-25 14:58 UTC, petertgiles requested changes
Very cool!  Thanks for fixing these.  I found a few that need a second look, though.  I wouldn't be surprised if most of these are related.

2023-07-25 14:58 UTC, petertgiles commented on apps/web/src/components/EmploymentEquity/dialogs/DialogFooter.tsx
Could you take a second look at the DEI dialogs?  I don't think this one is fixed yet.

https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/e6337259-474d-4c90-92eb-2dfd3963590f

2023-07-25 14:58 UTC, petertgiles commented on apps/web/src/pages/Applications/ApplicationResumePage/ApplicationResumePage.tsx
Could you check the add experience page associated with this page?  I think it needs fixing still.

Uploading simplescreenrecorder-2023-07-25_10.46.09.mp4…

2023-07-25 14:58 UTC, petertgiles commented on apps/web/src/pages/Applications/ApplicationResumePage/ApplicationResumePage.tsx
The "save and continue" on this page, too.

https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/46029584-1755-4999-a436-4f318196c496

2023-07-25 14:58 UTC, petertgiles commented on apps/web/src/pages/Applications/ApplicationSkillsPage/ApplicationSkillsPage.tsx
Could you check the dialog on this page?

Uploading simplescreenrecorder-2023-07-25_10.53.41.mp4…

2023-07-25 14:58 UTC, petertgiles commented on apps/web/src/pages/Applications/ApplicationSkillsPage/ApplicationSkillsPage.tsx
And the "save and continue"?

https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/b5073793-56a3-45ed-8406-2366a3435443

2023-07-25 14:59 UTC, petertgiles commented
> I believe it would be in our interest to review forms and get some sort of standard. Our BasicForm is a good starting point but this specific issue stemmed from how we defined the onSubmit so it may be worth standardizing how we write the onSubmit so we can rely more on react-hook-form state.

Good idea!  Any interest in contributing to the docs in this PR as well?  :sweat_smile:

2023-07-25 15:41 UTC, esizer commented on apps/web/src/components/EmploymentEquity/dialogs/DialogFooter.tsx
Not sure if this was the best approach but I rolled all of them up into one commit.

[use urql to disable application submit buttons](https://github.com/GCTC-NTGC/gc-digital-talent/pull/7318/commits/b3e2a6430f9f63e968f4e077da0159b01ef1e452)

2023-07-25 20:29 UTC, petertgiles commented on apps/web/src/pages/Applications/ApplicationSkillsPage/ApplicationSkillsPage.tsx
The "save and continue" is fixed but the "link an experience" dialog is not fixed yet.

2023-07-25 21:09 UTC, vd1992 commented
Bouncing around, things all seem to work right, I can't replicate the issue with linking skills to experiences as it works for me. 

https://recordit.co/6sHhyRjp7N

Found other small issues though instead, spun off
#7390 
#7391

2023-07-25 21:22 UTC, esizer commented on apps/web/src/pages/Applications/ApplicationSkillsPage/ApplicationSkillsPage.tsx
Updated the submission handler to be async and await the mutation. Seems to have fixed the issue.

[improve stability of skill form button disable](https://github.com/GCTC-NTGC/gc-digital-talent/pull/7318/commits/7927ef1ff13c76bf1a5da8f47084fb409d7eb6ea)

2023-07-26 12:09 UTC, petertgiles commented on apps/web/src/pages/Applications/ApplicationSkillsPage/ApplicationSkillsPage.tsx
Got it!  :dart:

2023-07-26 12:09 UTC, petertgiles approved these changes

2023-07-26 12:12 UTC, merged