[Copy] Update language evaluation labels
GCTC-NTGC/gc-digital-talent pull request #7458
Opened 2023-07-31 23:01 UTC by vd1992

🤖 Resolves #7385

## 👋 Introduction

Updates the labels as requested. 

## 🕵️ Details

Changed the label that also lists the three as I thought that was straightforward and should be in sync with the inputs. 
Also changed one place to reuse the labels from the utils file. 

## 🧪 Testing

1. Navigate to `/en/users/:id/profile#language-section`
2. Play with updating the language levels, observe the copy, and switch to French to check as well

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/a4010366-c9e6-4022-88df-957601f41494)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/ccf6461b-e0c6-4714-bf28-39c4f514c4e3)

`/fr/admin/users/:id/profile#language-section`

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/fd631409-8c4a-4a9a-9a81-70764b5a4c52)

2023-07-31 23:51 UTC, vd1992 commented
Storybook run

https://www.chromatic.com/review?appId=61e099a1bb1465003a73d3ce&number=7458&type=linked

2023-07-31 23:52 UTC, vd1992 commented
Oops, this label probably should've stuck around https://github.com/GCTC-NTGC/gc-digital-talent/pull/7458/commits/03385f9e26e8410b57e649962da2782943cc621e
Though, it is part of the old `LanguageInformationForm` which I don't think you can access anymore, conveniently.

2023-08-01 16:25 UTC, mnigh requested changes
A few suggestions. Also, for consistency, could you also change Comprehension Level, Written Level, Verbal Level, and Second language level (Comprehension, Written, Verbal) in:

1. `usePoolCandidateCsvData`
2. `useUserCsvData`
3. `ProfileDocument`

## English then French
- Reading level = Niveau de lecture
- Writing level = Niveau d’écriture
- Oral interaction level = Niveau d’expression orale

2023-08-01 16:25 UTC, mnigh commented on apps/web/src/components/UserProfile/ProfileSections/LanguageInformationSection.tsx
> +                    "Second language level (Reading, Writing, Oral interaction):",
Change to **Second language level (reading, writing, oral interaction)** and remove the colon from the string. Add the dividing colon message instead:

`{intl.formatMessage(commonMessages.dividingColon)}`

2023-08-01 16:25 UTC, mnigh commented on apps/web/src/lang/fr.json
> +    "defaultMessage": "Niveau de connaissance de la langue seconde (Lecture, Écriture, Expression orale)",
```suggestion
    "defaultMessage": "Niveau de connaissance de la langue seconde (lecture, écriture, expression orale)",
```

2023-08-01 16:25 UTC, mnigh commented on apps/web/src/components/Profile/components/LanguageProfile/Display.tsx
> +              "Second language level (Reading, Writing, Oral interaction)",
Change to **Second language level (reading, writing, oral interaction)** for  `defaultMessage` and `description`.

2023-08-01 17:50 UTC, vd1992 commented
Found a bug too #7467

2023-08-01 18:01 UTC, mnigh approved these changes
Ça roule!

2023-08-01 18:16 UTC, merged