[Copy] Update skill hero card
GCTC-NTGC/gc-digital-talent pull request #7459
Opened 2023-08-01 13:14 UTC by esizer

🤖 Resolves #7392 

## 👋 Introduction

Updates the skill showcase hero card on the "Profile and applications" page.

## 🕵️ Details

We have added new paths for the upcoming pages in `useRoutes` and used those for the skill showcase card.

> **Note**
> This does not create the pages, so interacting with the links takes you to a 404.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Build `npm run dev`
2. Login and navigaqte to `/applicant/profile-and-application`
3. Confirm the "Skill showcase" card link labels and urls match [the mockup](https://github.com/GCTC-NTGC/gc-digital-talent/issues/7392)

## 📸 Screenshot

![Screenshot 2023-08-01 091027](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/7f2133fc-2646-4d20-8e27-5e8132e13969)

2023-08-01 17:04 UTC, yonikid15 requested changes
Nice work Eric 👍 

Everything looks good, just missing two translation messages (Top Skills, Skills to improve):

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/22059495/b61d1bce-8217-4a96-a234-273f54aab9e6)

2023-08-01 17:09 UTC, yonikid15 commented
Also, shouldn't this issue be blocked until the [Skill Library page ](https://github.com/GCTC-NTGC/gc-digital-talent/issues/6936)is completed? Since there are links leading to incomplete pages (404 pages), plus the hardcoded statuses and skill counts?

2023-08-01 17:16 UTC, esizer commented
> Also, shouldn't this issue be blocked until the [Skill Library page ](https://github.com/GCTC-NTGC/gc-digital-talent/issues/6936)is completed? Since there are links leading to incomplete pages (404 pages), plus the hardcoded statuses and skill counts?

That is correct. Though, this is behind a feature flag (`FEATURE_SKILL_LIBRARY`) which should be false in prod. @tristan-orourke is that assumption correct?

2023-08-01 17:28 UTC, tristan-orourke commented
This issue doesn't need to be blocked. Yes, there are broken links, but as @esizer pointed out this is behind a feature flag, which we won't turn on until the pages are built out.

2023-08-01 19:01 UTC, yonikid15 commented
> This issue doesn't need to be blocked. Yes, there are broken links, but as @esizer pointed out this is behind a feature flag, which we won't turn on until the pages are built out.

Okay perfect 👍

2023-08-03 20:24 UTC, yonikid15 approved these changes
Looks good 👍

2023-08-03 20:29 UTC, merged