[Feature] Update edit pool page
GCTC-NTGC/gc-digital-talent pull request #8119
Opened 2023-10-03 19:44 UTC by esizer

🤖 Resolves #7951 

## 👋 Introduction

Updates the edit pool page to match the new design/layout.

## 🕵️ Details

We have not started the assessment plan yet so screening questions have remained intact for now.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Build `npm run dev`
2. Create a pool
3. Confirm you can update all sections as expected
4. Confirm it matches [the mockup](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=5437-36737&mode=design&t=GpPiwLkrz3NVFru6-4) (keeping in mind it still uses the old theme)

## 📸 Screenshot

![localhost_8000_en_admin_pools_b2e3bb74-2ca6-4f89-840d-56c1cd058af9_edit](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/eda77cf6-6357-4f1e-9927-53b45ae880a9)

2023-10-06 13:37 UTC, petertgiles requested changes

2023-10-06 13:37 UTC, petertgiles commented on apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
Form flips back to readonly even if API error occurred.  Also, missing frontend validation.

https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/335922ab-990b-4741-b420-ccde13f07ed2

2023-10-06 13:37 UTC, petertgiles commented on apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
I think these sections all need Cancel buttons now?
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/85ed911a-7027-438d-8f34-7b3015945f7e)

2023-10-06 13:37 UTC, petertgiles commented on apps/web/src/pages/Pools/EditPoolPage/components/WhatToExpectSection/WhatToExpectSection.tsx
Validator mismatch
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/e3802498-9f42-424b-af73-3e0e23a6431b)

2023-10-06 13:37 UTC, petertgiles commented on apps/web/src/pages/Pools/EditPoolPage/components/SpecialNoteSection/SpecialNoteSection.tsx
I think this section needs a null state.  Also, I think it's in the wrong order.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/eb32222a-7b7c-486b-b1bc-96da527b8639)

2023-10-06 13:37 UTC, petertgiles commented on apps/web/src/pages/Pools/EditPoolPage/EditPoolPage.tsx
Missing back button.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/d79fb1bf-667a-4a29-b8b7-b6bd5126974a)

2023-10-06 13:37 UTC, petertgiles commented on apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
I don't want to kick the time zone hornet's nest again but it seems unintuitive to enter Jan 1 in the form, save, and have it show Jan 2.  I guess it's saving in Pacific and displaying in UTC or local though that's not really clear to me.  It is saving the correct value in the DB though, so it's working correctly.

https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/e5092927-8658-4e00-9822-44f1bd73dcd1

2023-10-06 13:37 UTC, petertgiles commented
Awesome!  :star: A few rough edges to check on but it's looking great!

2023-10-06 15:29 UTC, esizer commented on apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
@Jerryescandon Can we display both local and PST strings here to make it clear?

2023-10-06 15:33 UTC, esizer commented on apps/web/src/pages/Pools/EditPoolPage/components/AssetSkillsSection.tsx
Removed required validation since this field is optional.

[fix asset skill icon](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8119/commits/7ef0c936fb944c30d8a11c19c1d3d836776328df)

2023-10-06 15:33 UTC, esizer commented on apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
Added a min value validation.

[add frontend validation on closing date](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8119/commits/5cd2e8e44541636b9b6bde9970fdd2a2b4346e0c)

2023-10-06 15:33 UTC, Jerryescandon commented on apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
mmmhhh.... sure, that should be fine, ill update it

2023-10-06 15:33 UTC, esizer commented on apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
Oops! 😅 Added in [add cancel buttons to inline forms](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8119/commits/67867b8d3fd7dcec67c1cf8df062c64cb9b1e0d7)

2023-10-06 15:34 UTC, esizer commented on apps/web/src/pages/Pools/EditPoolPage/components/WhatToExpectSection/WhatToExpectSection.tsx
Seems like this field is optional so validation was removed in [make what to expect section option](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8119/commits/5643a3728f7722bf672254f1b9929075aed5204b)

2023-10-06 15:34 UTC, esizer commented on apps/web/src/pages/Pools/EditPoolPage/components/SpecialNoteSection/SpecialNoteSection.tsx
Oh yeah, this one was odd because `null` actually means something here. Went with removing the null state and handled it in the normal display.

[fix special note display, re-order](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8119/commits/a81417fa90d3a6b6afdb0849d3424dc17b97462f)

2023-10-06 15:37 UTC, esizer commented on apps/e2e/cypress/e2e/admin/pools.cy.js
> +   * Note: Skipping until #8004 is in
Oops! Yup 😛 Removed in [remove outdated comment](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8119/commits/e386d3403c77b37cbae83ccc25c0710b9de34b54)

2023-10-06 15:38 UTC, Jerryescandon commented on apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
Thoughts? 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/bc2b44af-f267-466e-bb62-fe43c70e4704)

2023-10-06 15:38 UTC, esizer commented on apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
Love it! 👏 Thanks!

2023-10-06 15:45 UTC, esizer commented on apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
Updated with both time zones to add clarity.

[update closing date display with both timezones](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8119/commits/308e16a45b152fee82e39c8c19449bb676890e28)

2023-10-06 17:36 UTC, petertgiles commented on apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
Nice, the validation works.  However, the forms still flip back even if there's an API error.

2023-10-06 17:48 UTC, petertgiles reviewed
Just a few more ideas while working on the review...

2023-10-06 17:48 UTC, petertgiles commented on apps/web/src/pages/Pools/EditPoolPage/components/AssetSkillsSection.tsx
I noticed that the search a filter boxes are absent in the design, and not really needed for these small tables.  Is it possible to easily hide them?
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/ff14346a-1040-4181-95bc-40eecf7bd487)

2023-10-06 17:48 UTC, petertgiles commented on apps/web/src/components/ToggleForm/ToggleForm.tsx
Probably out of scope for this issue, but when a form saves there is a period of time where it flips back to the readonly view but is displaying the stale information.  Once the "page data" query completes it refreshes to the new data.  I find this a bit unnerving.  What do you thing about some sort of pending state for these toggles?

2023-10-06 17:59 UTC, esizer commented on apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
Is there a specific API error that is occurring that we aren't handling on the frontend to prevent these from closing?

2023-10-06 18:03 UTC, esizer commented on apps/web/src/components/ToggleForm/ToggleForm.tsx
Yeah, this was sort of bothering me too. It isn't awful if you are on a quick connection but I feel like it will become an issue for average users. I'll take a stab at it.

Though, this raises another question; should we start to think about [optimistic UI](https://www.apollographql.com/docs/react/v2/performance/optimistic-ui/)? Or do we just want to keep sticking spinners everywhere? 😅

2023-10-06 18:11 UTC, petertgiles commented on apps/web/src/components/ToggleForm/ToggleForm.tsx
Cool, thanks.  

I mean, it shouldn't even be optimistic, the form shouldn't flip back until it got confirmation that the form submission was successful.  :sweat_smile: 

In theory, urql should have the updated data in the mutation response but I think it won't be straightforward to use it since the component is actually being populated by a parent query in the page component, right?  I'd be happy if even just the toggle forms got a grey overlay or something while the query was busy.

2023-10-06 18:12 UTC, petertgiles commented on apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
I was responding with the 403 from the firewall simulator - which could definitely happen on these forms.

2023-10-06 18:15 UTC, petertgiles commented on apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
This came up originally because of the missing frontend validator and the API was kicking out the dates in the past.

2023-10-06 18:19 UTC, esizer commented on apps/web/src/components/ToggleForm/ToggleForm.tsx
The problem is, the way `urql` works with its cache is the query is never busy 😢 or at least, not long enough to actual do anything useful.

1. Query marked as busy
2. Finds a cache -> this is like 10ms at most, usually
3. Query no longer busy
4. Document marked stale
5. Request sent
6. Document updated

Unless there is something obvious missing. 🤔 I assumed waiting on the promise would solve this but it does not seem to 👎 

```tsx
await onSave(formValuesToSubmitData(formValues)).then(() => {
  methods.reset(formValues, {
    keepDirty: false,
  });
  setIsEditing(false);
});
```

2023-10-06 18:58 UTC, esizer commented on apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
Already, it seems that our error handler was short-circuiting the promise. This was causing the promise to resolve and close the form. Throwing an error from the handler and returning the promise seems to have resolved this without needing to handle all specific errors 👏 

I just threw a generic error since we are already handling it in the context provider. Do you think it is worth trying to throw the same API error or will the generic one be fine? 🤔 

[prevent forms closing on API error](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8119/commits/5983cc888488e5fec247e7781acfa534c638a03d)

2023-10-10 12:57 UTC, petertgiles approved these changes

2023-10-10 19:06 UTC, merged