[Debt] Refactors Search Request table to use `ResponsiveTable`
GCTC-NTGC/gc-digital-talent pull request #8365
Opened 2023-10-31 20:36 UTC by mnigh

🤖 Resolves #7694.

## 👋 Introduction

This PR refactors Search Request table to use `ResponsiveTable`.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Navigate to `/admin/talent-requests`
2. Observe new table

2023-11-03 19:41 UTC, yonikid15 requested changes
Looking good so far 👍 Just some name changes that need to be made

- Pagination works
- Searching works
- Sorting works
- Hidden columns are working
- Returning back to page while maintaining search/filter/sort/hidden columns params is working

2023-11-03 19:41 UTC, yonikid15 commented on apps/web/src/components/SearchRequestTable/SearchRequestTable.tsx
> +        detailsAccessor(searchRequest, intl),
Forgot to change the name to `detailsCell`

2023-11-03 19:41 UTC, yonikid15 commented on apps/web/src/components/SearchRequestTable/SearchRequestTable.tsx
> +        notesAccessor(searchRequest, intl),
This should be named `notesAccessor`

2023-11-03 19:41 UTC, yonikid15 commented on apps/web/src/components/SearchRequestTable/SearchRequestTable.tsx
> +        statusAccessor(searchRequest.status, intl),
This should be named `statusCell`

2023-11-03 20:08 UTC, mnigh commented on apps/web/src/components/SearchRequestTable/SearchRequestTable.tsx
> +        notesAccessor(searchRequest, intl),
I think you meant `notesCell`, right?

2023-11-03 20:24 UTC, yonikid15 commented on apps/web/src/components/SearchRequestTable/SearchRequestTable.tsx
> +        notesAccessor(searchRequest, intl),
Yup 😆

2023-11-07 15:21 UTC, yonikid15 reviewed
Last week I was seeing that flash of empty table, were you or @esizer able to fix that.
I found that adding a `!isLoading` check to `hasNoVisibleRows` prevents the flash from happening. However, it doesn't address the failing query that causes it in the first place.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/7916-finalize-assessment-plan-page/apps/web/src/components/Table/ResponsiveTable/ResponsiveTable.tsx#L282-L283

2023-11-07 15:58 UTC, brindasasi commented
In the mobile view some cards have Group and Level , Steams fields on the same line and some others in next line. 
Is it possible to have them consistent? Like always in next line ? 
![Screenshot 2023-11-07 at 10 55 54 AM](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/16e2a7ca-74ae-404b-b3a2-b911dd729ea1)

2023-11-07 17:41 UTC, mnigh commented
> In the mobile view some cards have Group and Level , Steams fields on the same line and some others in next line. Is it possible to have them consistent? Like always in next line ?

Updated in [08615d8](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8365/commits/08615d82389dd630bd56576440408c9621e0c7a1).

## Screenshot
![Screen Shot 2023-11-07 at 12 41 39](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/760eef18-e039-463d-a0d0-821274b0c288)

2023-11-07 18:05 UTC, mnigh commented
> Last week I was seeing that flash of empty table, were you or @esizer able to fix that. I found that adding a `!isLoading` check to `hasNoVisibleRows` prevents the flash from happening. However, it doesn't address the failing query that causes it in the first place.
> 
> https://github.com/GCTC-NTGC/gc-digital-talent/blob/7916-finalize-assessment-plan-page/apps/web/src/components/Table/ResponsiveTable/ResponsiveTable.tsx#L282-L283

Updated in [4057ff1](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8365/commits/4057ff1e07725dffaa0c9b45b18578f3f977103e). Also, made a few more small changes since your last review.

2023-11-07 19:21 UTC, yonikid15 approved these changes
Excellent work 🎉 looks good on my end

2023-11-07 20:07 UTC, brindasasi approved these changes
LGTM! 🥳

2023-11-07 20:12 UTC, merged