[Debt] Removes `hasDiploma`, `has_diploma`
GCTC-NTGC/gc-digital-talent pull request #8783
Opened 2023-12-13 18:28 UTC by mnigh

🤖 Resolves #8661.

## 👋 Introduction

This PR removes the hasDiploma field as well as any strings or components that are otherwise useless without it.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Run `refresh_api.sh`
2. Run fresh seed for database
3. `npm run build`
4. Ensure no references to `hasDiploma`, `has_diploma` in the codebase (other than old migrations)
5. Ensure no columns in database named `has_diploma` by running SQL query:
```
select table_name from INFORMATION_SCHEMA.COLUMNS 
where COLUMN_NAME like '%has_diploma%' 
order by TABLE_NAME
```

2023-12-14 15:02 UTC, esizer reviewed
Looking great! I just had one question about data retention.

2023-12-14 15:26 UTC, mnigh commented on api/database/migrations/2023_12_13_180500_drop_has_diploma_column.php
> +        });
i'm not sure, i was following the acceptance criteria that includes:

> Removed from where decided in Proposed solution
> 🙋‍♀️ Proposed Solution
> Remove it
> - Database

@tristan-orourke can you weigh in on whether or not these columns should be kept or dropped from the database?

2023-12-14 16:19 UTC, petertgiles commented on api/database/migrations/2023_12_13_180500_drop_has_diploma_column.php
> +        });
Decision from scrum: drop from users table, keep in requests tables

2023-12-14 16:34 UTC, esizer submitted a review, later dismissed
Nice 🪓 ! Assuming the tests all pass, this LGTM! 👍

2023-12-14 16:39 UTC, mnigh commented on api/database/migrations/2023_12_13_180500_drop_has_diploma_column.php
> +        });
Changed in [39cab07](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8783/commits/39cab07ad29632d9d69c4c806b1dfe03e599558e).

2023-12-15 17:16 UTC, tristan-orourke requested changes
Sorry, we need to keep some of this for now!

Even if it doesn't correspond directly to a field on the User model, its useful for recruitment team to know whether talent seekers require someone with a diploma.

So the following is all good:
- remove has_diploma from users table
- remove scopes from PoolCandidate and User models
- remove hasDiploma from the user model in the schema
- remove references to hasDiploma from backend user/candidate search functions, since that is meaningless
- remove hasDiploma option from search filters on the admin tables, if its not already gone

However, please restore the following:
- hasDiploma remains part of the ApplicantFilter and PoolCandidateFilter models, in php and in schema
- Talent Seekers can continue to select that they require diplomas (see image below)
- hasDiploma can continue to be attached to the ApplicantFilter submitted with requests
- Request Responders can continue to see whether a request requires diplomas or not (see image below)

Talent Seekers should be able to add education requirement:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/891cb2ac-4a07-49ff-ade8-4c809efd9f33)


Education Level visible on admin view of request:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/1e2884f6-625e-4e7b-be5b-74edc6c719ed)

2023-12-18 16:12 UTC, petertgiles commented
Waiting for #8821 before moving with this one

2024-03-07 17:25 UTC, mnigh commented
Closing due to uncertainty.

2024-03-07 17:25 UTC, closed without merging