[Fix] Table date sort
GCTC-NTGC/gc-digital-talent pull request #8842
Opened 2023-12-19 17:49 UTC by esizer

🤖 Resolves #8838 

## 👋 Introduction

Fixes the issue with tables not sorting date columns properly.

## 🕵️ Details

We had the `accessor` and `cells` mixed up 😅 . This updates it so the accessor returns a `Date` and adds a `cell` to handle the formatting of said date.

> [!NOTE]
> We have been sorting the `PoolTable`  by `ceatedDate` so I was hesitant to change this. Do we still want to be changing this to `updatedDate`.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Build `npm run dev`
2. Navigate to tables in the admin
3. Sort any date columns
4. Confirm they are sorted properly

## 📸 Screenshot

![Screenshot 2023-12-19 124640](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/ae4a8036-6170-4d27-83a1-2eaa6074809c)

2023-12-20 18:42 UTC, brindasasi commented
I don't mind sorting by created date. But the thing is it is hidden by default 😅
Default visible column is "Updated" on that table. 
I would recommend doing the default sorting on default visible columns.

could we make "Created" column as visible by default? 
cc: @GCTC-NTGC/designers

2023-12-20 19:49 UTC, brindasasi requested changes
Thank you for prioritizing this ticket. Sorting works nicely.
but on the pool candidates table , if we go to second or third pages, and then try to change the sorting order on the date column, it sorts randomly. 
If you look at the screen shot , I sorted by descending order on the 3rd page, it gets Oct ,Nov and then oct again.
![Screenshot 2023-12-20 at 2 41 37 PM](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/0aab5e00-deff-4ea1-8feb-c13477f649ba).
Could you check why it is happening?

2023-12-20 19:57 UTC, esizer commented
> Thank you for prioritizing this ticket. Sorting works nicely.
> but on the pool candidates table , if we go to second or third pages, and then try to change the sorting order on the date column, it sorts randomly.
> If you look at the screen shot , I sorted by descending order on the 3rd page, it gets Oct ,Nov and then oct again.

heh, yeah. So, this is _highly_ confusing but, it technically is sorting properly. We have multiple sorts going on here where two take precedence over the submitted date. It sorts like this:

1. Status
2. Category
3. Date (user controlled)

So what it happening is, when you sort by date received it first sorts by Status, then if two users have the same status it will sort by category, then if both the status and category are the same it finally sorts by date received.

Hopefully that clears things up 😅

2023-12-20 22:17 UTC, brindasasi approved these changes
you are right! It goes by that logic. After picking up specific status & category, sorting looks fine by the date. Thanks!👏

2023-12-20 22:21 UTC, RM-1978 commented
Humm, I wonder if that logic might be a little complex for a user who simply wants to see the most recently updated pools? Do we need instructional text?

2023-12-21 13:14 UTC, esizer commented
> Humm, @esizer I wonder if that logic might be a little complex for a user who simply wants to see the most recently updated pools? Do we need instructional text?

We may need to ask DCM, they were the ones who originally requested this functionality so we can prioritize certain groups.

2023-12-21 13:15 UTC, merged