[Debt] Update the admin hero
GCTC-NTGC/gc-digital-talent pull request #8848
Opened 2023-12-20 18:53 UTC by esizer

🤖 Resolves #8584 

## 👋 Introduction

This updates the admin hero to be consistent across all pages under `/admin`

## 🕵️ Details

There were 3 variants created:

- Default, no nav
- Sub nav, contains links styled like tabs to sub pages
- Breadcrumbs, contains breadcrumb links

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Build `npm run dev`
2. Navigate to pages under `/admin`
3. Confirm they have a consistent hero

## 📸 Screenshot

### Default

![Screenshot 2023-12-20 134508](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/59094987-7f1f-4594-aa71-373de43bf338)

### Sub Navigation

![Screenshot 2023-12-20 134502](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/e541cc7d-26d7-48ac-8d93-f20a9bcd77fa)

### Breadcrumbs

![Screenshot 2023-12-20 134454](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/9fb3b58c-687f-4d0b-b416-0f182b0c6d5a)

2023-12-20 23:08 UTC, vd1992 requested changes
Found some stuff for you to take a look at

2023-12-20 23:08 UTC, vd1992 commented on apps/web/src/pages/Skills/UpdateSkillPage.tsx
Crumbs were apparently broken on this page for a long while 🙃 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/fdf4a599-8532-492a-8832-cbb6243dd665)

From

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/19ddcc9f-8998-4bed-92a0-31f64a82c4c6)

2023-12-20 23:08 UTC, vd1992 commented on packages/ui/src/components/Tabs/utils.ts
I think you want to keep that padding

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/8bb3481f-2d6f-4555-8ea8-1e38d1cc8b05)

2023-12-21 13:41 UTC, esizer commented on apps/web/src/pages/SkillFamilies/IndexSkillFamilyPage.tsx
> +      </AdminContentWrapper>
Oops, yeah that was an early test I forgot to swap back 😅 

Fixed in [fix sub nav mode](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8848/commits/2ecd10d81f869a46503c7833f775a586e4ed4f99)

2023-12-21 13:41 UTC, esizer commented on apps/web/src/pages/Skills/UpdateSkillPage.tsx
ooo! Great catch! fixed in [fix skill breadcrumbs](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8848/commits/b10cfc9802310623098d7625a3ee3a7c3a21f96f)

2023-12-21 13:42 UTC, esizer commented on packages/ui/src/components/Tabs/utils.ts
Oh thats what that was doing 😆 . It was causing problems with the nav version. I moved it to the tabs version to only apply it there.

[fix tabs content padding](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8848/commits/15ec8ac4222f0820a3f72374d34e20318be3d51e)

2023-12-21 18:06 UTC, vd1992 approved these changes
Appears all good to me, fantastic!

2023-12-21 18:11 UTC, merged