[Feature] Table downloads async
GCTC-NTGC/gc-digital-talent pull request #8970
Opened 2024-01-09 15:33 UTC by esizer

🤖 Resolves #8956 

## 👋 Introduction

This fixes an issue where downloads were empty on the first attempt. It achieved this by making the data query asynchronous. 

## 🕵️ Details

### Problem/Solution

There seemed to be a race condition where we were loading the data at the same time as generating either the CSV or print document. This refactors things to avoid this. We now load the data on click, awaiting it and then generating the document. This has some pros and cons, however I believe the pros outweigh the cons here.

#### Pros

- No more race conditions
- Data is only loaded when it is needed, not before

#### Cons

- Since we are no longer pre-loading data, it is a little longer wait when clicking an action

### CSV

While the existing `react-csv` we were using purported to support async handlers, it did not seem to work and there were many issues on their repo about this. Coupled with the fact that the library had not been updated in 2 years, I switched to the more consistently maintained `react-csv-downloader` instead.

Unfortunately, this did require some refactoring to how we download CSVs.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Install new csv downloader dep `npm i`
2. Build `npm run dev`
3. Login as admin
4. Navigate to `/admin/pool-candidates`
5. Select some rows
6. Note, not query is ran
7. Attempt both download/print
8. Confirm query is ran and expected output document is created
9. Navigate to `/admin/users`
10. Repeat steps 5-8
11. Navigate to an application (`/admin/candidates/{poolCandidateId}/application`)
12. Click "Print application"
13. Confirm it still functions as expected
14. Navigate to a user profile (`/admin/users/{userId}/profile`)
15. Click "Print profile"
16. Select either option
17. Confirm it still functions as expected

2024-01-09 21:26 UTC, tristan-orourke commented
Hey, based on some further dialog with recruitment team, do you mind if I add another Acceptance Criteria?

Basically, the request for data sometimes fails with a server error if you request too many candidates at once. The graphql response is simply `{ "message": "Server Error" }`. Right now this seems to fail silently. Could you make sure we throw a toast if the request fails like this, ideally with a suggestion to reduce the number of items selected?

2024-01-10 13:11 UTC, esizer commented
> Basically, the request for data sometimes fails with a server error if you request too many candidates at once. The graphql response is simply `{ "message": "Server Error" }`. Right now this seems to fail silently. Could you make sure we throw a toast if the request fails like this, ideally with a suggestion to reduce the number of items selected?

Yup! I added it [add error message for too many rows on download](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8970/commits/9b8e15cc070077c5d79a88321c4648c3062ade00). I'm not happy with the actual message but I was just following the same pattern for the "no rows" error. Any suggestions on a better message? 🤔

2024-01-10 15:41 UTC, tristan-orourke commented
I have to admit, it's not obvious to me that this icon is meant to act like a loading spinner. Without moving, it looks more like a "retry" button. 😕 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/d9934541-504e-405c-af23-07292dc330ec)

2024-01-11 17:34 UTC, petertgiles requested changes
Nice!  This is a pretty major refactor, actually.  Turned out great.  :1st_place_medal:  I noticed one bug in the test but overall works really well.

I found it a bit weird that the UI throws up spinners beside both links regardless of which one was clicked.  I know there was no design provided so I won't block on that but I think it would make a bit more sense if there was a single shared spinner associated with the entire footer, maybe.

2024-01-11 18:08 UTC, esizer commented on apps/e2e/cypress/e2e/admin/admin-workflows.cy.ts
> +  it.only("Selects a user and downloads a CSV", () => {
Oof, goo catch! Fixed in [undo single admin workflow test debug](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8970/commits/9e7bb34ff34c6fedf2789e4ffedb2078d4d3873d)

2024-01-11 18:08 UTC, esizer commented
> I found it a bit weird that the UI throws up spinners beside both links regardless of which one was clicked. I know there was no design provided so I won't block on that but I think it would make a bit more sense if there was a single shared spinner associated with the entire footer, maybe.

I agree, it was a simple fix so I did it in [only show loading icon for specific action](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8970/commits/5a36bd440d5ba00967b2a11ad9b018504baae1db)

2024-01-12 13:44 UTC, petertgiles approved these changes
Looks great!

2024-01-12 15:23 UTC, esizer commented on apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
> +        if (result.error) {
oh my, yeah sorry. I totally read the first comment incorrectly 🤦‍♀️ I thought it said "no candidates" not "too many" 😬

2024-01-12 15:50 UTC, esizer commented on apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
> +        if (result.error) {
I am having trouble reproducing this exact type of error. May need some help with that for testing but, I added a catch statement and used the generic unknown error message (which _should_ cover it).

2024-01-15 14:49 UTC, tristan-orourke approved these changes
Thanks! 👍

2024-01-15 15:17 UTC, merged