[Feature] Add ROD columns to `PoolCandidatesTable`
GCTC-NTGC/gc-digital-talent pull request #9007
Opened 2024-01-11 17:00 UTC by esizer

🤖 Resolves #8675 

## 👋 Introduction

Updates the `PoolCandidatesTable` to add new ROD related columns.

## 🕵️ Details

### Bookmarking

For bookmarking, the functionality in the assessment step tracker was moved to a component so it could be re-used.

### Sorting

The sorting for final decision and job placement were locked since we are sorting by status and they effectively did nothing which was confusing. We will need to unlock these when we get proper sorting for these columns.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Build `npm run dev`
2. Login as admin
3. Navigate to `/admin/pool-candidates`
4. Confirm new columns exist
5. Confirm you can bookmark and sorting does not change until refresh
6. Confirm the view link takes you to the application
7. Confirm the status column is hidden by default when ROD feature flag is enabled
8. Confirm final decision matches the expected outcome from [the ticket description](https://github.com/GCTC-NTGC/gc-digital-talent/issues/8675)
9. Confirm job placement matches the expected outcome from [the ticket description](https://github.com/GCTC-NTGC/gc-digital-talent/issues/8675)

## 📸 Screenshot

![localhost_8000_en_admin_pool-candidates](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/22906029-0486-4154-8d66-edd37f1177f0)

2024-01-16 14:48 UTC, petertgiles requested changes
Very cool!  :sunglasses: I love the factoring out of the bookmark component and the status logic is very clean.  I flagged a few things to check on next.

2024-01-16 14:48 UTC, petertgiles commented on apps/web/src/components/CandidateBookmark/CandidateBookmark.tsx
I'm not sure the bookmark sorting is working properly.  When I bookmarked someone on the first page and refreshed I expected them to rise in the table but instead the descended to a later page.  And when I unbookmarked them they didn't return to the first page.  

https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/13380909-5b64-49db-af09-6b85bb26e092

2024-01-16 14:48 UTC, petertgiles commented on apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
I don't think it should be possible to have N/As on qualified candidates, right?
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/38a2ecb9-547c-4ac4-a2c7-826695438b0a)

2024-01-16 14:48 UTC, petertgiles commented on apps/web/src/components/CandidateBookmark/CandidateBookmark.tsx
Seems unpredictable with the RoD flag off, too.

2024-01-16 16:02 UTC, esizer commented on apps/web/src/components/CandidateBookmark/CandidateBookmark.tsx
Hmm, maybe that is because we never actually sort by bookmarked 😅 I guess we will need to add this to the `schema.graphql`?

https://github.com/GCTC-NTGC/gc-digital-talent/blob/0d34f25e0440655207e36861f0a926cf331d779f/api/graphql/schema.graphql#L706-L723

2024-01-16 21:45 UTC, esizer commented on apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
oo, good catch! Fixed in [fix not placed status](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9007/commits/96ad2970ccf7a79f690f8ca856c05a42ecf32bcf)

2024-01-16 21:46 UTC, esizer commented on apps/web/src/components/CandidateBookmark/CandidateBookmark.tsx
okay, I got this working by changing the column to be non-nullable and false by default.

[set is_bookmarked to non nullable for better sorting](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9007/commits/bf4ec14de585dc2ad55ef88e42cdf6b0ea3efee1)

2024-01-17 13:51 UTC, petertgiles commented on apps/web/src/components/CandidateBookmark/CandidateBookmark.tsx
Hmm, the migration sets the default for me, but the column is still nullable.  To make that change safely you probably need to add an update command to change all the nulls to false, too.

2024-01-17 13:53 UTC, esizer commented on apps/web/src/components/CandidateBookmark/CandidateBookmark.tsx
Hmm, I'll check that nullable issue but line 15 contains the `null` to `false` portion.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/bf4ec14de585dc2ad55ef88e42cdf6b0ea3efee1/api/database/migrations/2024_01_16_201038_pool_candidates_table_is_bookmarked_non_nullable.php#L15

2024-01-17 13:57 UTC, esizer commented on apps/web/src/components/CandidateBookmark/CandidateBookmark.tsx
Oh, jeeze. I missed a big part 😅 

Should no longer be nullable after [update to make is_bookmarked not nullable](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9007/commits/eb445610d27aaf2b72cf1c4aa3e1ac6b6c622267)

![Screenshot 2024-01-17 085656](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/01cb5a1b-03af-4fdc-8008-a60874946dd4)

2024-01-17 14:05 UTC, petertgiles commented on apps/web/src/components/CandidateBookmark/CandidateBookmark.tsx
Oh, jeeze, I missed line 15.  :laughing:   Looks good now.

2024-01-17 14:24 UTC, petertgiles approved these changes

2024-01-17 21:55 UTC, merged

2024-01-17 22:34 UTC, Jerryescandon commented
I have a couple questions for @gobyrne about this, maybe we can spinoff in future tickets.

1. Locked column order: I think we can remove these, I believe these were implemented to reduce assessment bias. Order the candidates in whichever order SHOULD theoretically be followed for assessment. But now that we have a page dedicated to organize and record assessment progress, locking these columns feels unnecessary, and reduces the possibilities for power-users.

2. The "View" in front of every name. I am unsure what prompted this, could we remove it from the text, and maybe keep it on the Aria label if necessary? It doesn't really add much, and makes scanning for a name a lot harder.