[Feature] New update pool candidate notes mutation
GCTC-NTGC/gc-digital-talent pull request #9228
Opened 2024-02-07 14:27 UTC by esizer

🤖 Resolves #9193 

## 👋 Introduction

Adds a new mutation that updates only the notes for a pool candidate, removing that field from the general mutation.

## 🕵️ Details

The acceptance criteria was to make this field non-nullable. However, we have made it so empty strings are converted to `null` so I had to make this field nullable.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/6024938731b710d61d42ed639242ddaa45731ba7/api/app/Http/Kernel.php#L23

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Build `npm run dev`
2. Login as admin
3. Navigate to a pool candidate
4. Open the notes dialog
5. Edit the notes and save
6. Confirm success
7. Repeat steps 4-6 with empty notes
8. Navigate to a user information page
9. Edit the candidate notes
10. Confirm success
11. Turn off the record of decision feature flag
12. Rebuild
13. Navigate to a pool candidate
14. Edit the notes in the application status form
15. Confirm success

2024-02-07 15:51 UTC, petertgiles requested changes
Looks really good!  Might need to check on the handling of clearing notes, though.

2024-02-07 15:51 UTC, petertgiles commented on apps/web/src/pages/Users/UserInformationPage/components/NotesSection.tsx
Uh oh, it's not saving the empty form.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/31f22ed2-3fbb-4a74-8217-b3a28c23cfa3)

2024-02-07 15:51 UTC, petertgiles commented on apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/NotesDialog.tsx
This is probably out of scope but it's not possible to clear notes with the ROD dialog, either.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/457e9f08-0bc1-4e62-9a4e-4bd3c8d229b6)

2024-02-07 15:55 UTC, esizer commented on apps/web/src/pages/Users/UserInformationPage/components/NotesSection.tsx
Oh shoot, I forgot to update the frontend mutations. I'm going to wait until standup to ask about this due to the issue around empty strings being converted to `null` by laravel.

2024-02-07 15:55 UTC, esizer commented on apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/NotesDialog.tsx
Yeah, I'll need to confirm this in standup. I assume this field is required for a reason 🤔

2024-02-07 16:49 UTC, tristan-orourke commented
Huh, looks like that ConvertEmptyStringToNull middleware _was_ Laravel default! Git blame sources that line to this commit https://github.com/GCTC-NTGC/gc-digital-talent/commit/6e0f2424cbdd138fb4258bc38b944883a3d03cab#diff-af7289a2ef0f7c535e944676e9ba627c246b0adda48463a7b6bd931ade98abf7

2024-02-07 16:50 UTC, tristan-orourke commented on apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/NotesDialog.tsx
We decided in standup it should definitely be possible to save this dialog with an empty string.

2024-02-07 16:51 UTC, esizer commented
> Huh, looks like that ConvertEmptyStringToNull middleware _was_ Laravel default! Git blame sources that line to this commit

Huh, interesting! Maybe the ticket I found for lighthouse was older than that being default? 🤔

2024-02-07 17:00 UTC, esizer commented on apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/NotesDialog.tsx
Alright, while it will still throw an error...The form now lets you at least submit with empty notes 😛 [make notes field optional in dialog](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9228/commits/fb1700d398bf73e83e41884aec20595d72b6523b)

2024-02-13 15:38 UTC, tristan-orourke commented
@esizer for now, just let this field be nullified.

But could you write up a ticket about looking into this ConvertEmptyStringToNull middleware? A spike, I guess. Do we really want it, how much trouble would it be to remove it, etc.

2024-02-13 15:44 UTC, esizer commented on apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/NotesDialog.tsx
> @esizer for now, just let this field be nullified.

Updated to be nullable in [make candidate notes filed nullable](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9228/commits/d16f71b458c7269ac5f3ba12a68dd063c1725497)

2024-02-13 21:35 UTC, petertgiles approved these changes
Works great!  :medal_sports:

2024-02-13 22:10 UTC, merged