[Copy] Rename candidates tab for a process
GCTC-NTGC/gc-digital-talent pull request #9305
Opened 2024-02-09 21:20 UTC by vd1992

🤖 Resolves #9235

## 👋 Introduction

Changes the copy to "Talent placement". 

## 🧪 Testing

1. With RoD on navigate to `/en/admin/pools/:id/pool-candidates`
2. Observe tabs

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/a5a256cb-4835-4e1e-9804-7c6752abe9da)

2024-02-09 21:25 UTC, mnigh commented on apps/web/src/utils/poolUtils.tsx
> +                description: "Title for a process's candidates tab",
```suggestion
                description: "Title for candidates tab for a process",
```

2024-02-09 21:36 UTC, vd1992 commented on apps/web/src/utils/poolUtils.tsx
> +                description: "Title for a process's candidates tab",
Sure https://github.com/GCTC-NTGC/gc-digital-talent/pull/9305/commits/87b5ee2e39a02f4cedfb166fa7515b6d1fa43796

2024-02-12 17:06 UTC, mnigh requested changes

2024-02-12 17:06 UTC, mnigh commented on apps/web/src/lang/fr.json
> +    "description": "Title for a process's candidates tab"
```suggestion
    "description": "Title for candidates tab for a process"
```

2024-02-12 17:25 UTC, mnigh approved these changes

2024-02-12 17:56 UTC, merged