[Feature] Pool opportunity length field
GCTC-NTGC/gc-digital-talent pull request #9395
Opened 2024-02-16 19:59 UTC by esizer

🤖 Resolves #8824 

## 👋 Introduction

Adds a new opportunity length field to the pools table to allow admins to communicate the employment duration.

## 🧪 Testing

> [!IMPORTANT]
> Do not run a fresh migration while testing this. We want to test updating existing records!

### Migration/Seeders

1. Run migrations `docker-compose exec -w /home/site/wwwroot/api webserver sh -c "php artisan migrate"`
2. Confirm `pools` table has new column and existing rows are set to `VARIOUS`
3. Seed new data `docker-compose exec -w /home/site/wwwroot/api webserver sh -c "php artisan db:seed"`
4. Confirm new data has a variation of the enum values

### Publishing a Pool

1. Build app `npm run dev`
2. Login as admin
3. Create a new pool
4. Fill out the pool fields **leaving opportunity length empty**
5. Confirm the pool is still not complete and you cannot publish
6. Select a pool opportunity length
7. Confirm pool is now complete and you can publish

### Viewing a pool

1. View the advertisement on the public facing page
2. Confirm the selected opportunity appears
3. Confirm clicking the info link shows the appropriate page on both English and French

## 📸 Screenshot

![Screenshot 2024-02-16 145126](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/36bd1dc5-d4f0-4be8-b385-ec2014156595)
![Screenshot 2024-02-16 145143](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/22934190-ed54-4a57-a3ce-dfbba79ae5a0)
![Screenshot 2024-02-16 145155](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/e1776b94-e407-4c5b-baad-e7e8a433623e)

2024-02-17 00:06 UTC, vd1992 requested changes
Looking good, just a few small things

2024-02-19 13:00 UTC, esizer commented on apps/web/src/pages/Pools/EditPoolPage/EditPoolPage.tsx
Oh right! Fixed in [fix edit pool basic info null/error state](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9395/commits/d7568568eb1c6d7116fa895e4ac7f853cf616da2)

2024-02-19 13:01 UTC, esizer commented on apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
> +                      defaultMessage: "Employment length",
Oops! At least I was close 😅 Moved in [move length of opportunity field above work location](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9395/commits/cb58c8aa39fbc5ea42b53a693018bdd7023884b5)

2024-02-19 17:31 UTC, vd1992 approved these changes
Looks good to me, nice job!

2024-02-26 17:25 UTC, merged