[Feature] Add new fields to Pool model
GCTC-NTGC/gc-digital-talent pull request #9719
Opened 2024-03-11 20:29 UTC by esizer

🤖 Resolves #8829 

## 👋 Introduction

Adds two new fields ("what to expect post admission" and "about us") to the pool model.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Migrate `php artisam migrate`
2. Build app `npm run dev`
3. Lopgin as admin `admin@test.com`
4. Create a pool
5. Confirm the new sections exist
6. Confirm they save and load data properly
7. Confirm they appear on the advertisement page as expected

## 📸 Screenshot

![Screenshot 2024-03-11 162600](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/b1b1a23c-90a6-4ee1-8266-ed6ca33623a6)
![Screenshot 2024-03-11 162603](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/8c266580-98ff-4769-a422-9bec137ad460)
![Screenshot 2024-03-11 162608](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/f1e9961d-5c34-4a8a-9687-8388b553e478)
![Screenshot 2024-03-11 162646](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/610ef6c8-c90f-49a8-aad1-1d8480fa98c8)
![Screenshot 2024-03-11 162700](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/8515faf5-9a1c-4f2f-af7d-9c8345ba550c)
![Screenshot 2024-03-11 162711](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/e7492b8f-b714-4dfa-983e-b3f8e0192026)

2024-03-13 13:15 UTC, petertgiles requested changes
Cool!  :sunglasses: A few things to check on before merging.

2024-03-13 13:15 UTC, petertgiles commented on apps/web/src/validators/process/aboutUs.ts
It's possible to publish a pool if only one language is filled out and the validation icon doesn't change.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/b34e4956-4755-4169-a613-d49cea3d53dd)

2024-03-13 13:15 UTC, petertgiles commented on apps/web/src/validators/process/aboutUs.ts
@substrae could you please confirm if this should trigger validation to fail?

2024-03-13 13:37 UTC, esizer commented on apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
Oops! Fixed as part of [fix about us display on the advert](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9719/commits/47d966ddd6e8da53998543aeec1fd1e05ef57d96)

2024-03-13 13:37 UTC, esizer commented on apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
Oh yeah, I forgot it was option 😅 Fixed as part of [fix about us display on the advert](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9719/commits/47d966ddd6e8da53998543aeec1fd1e05ef57d96)

2024-03-13 15:04 UTC, tristan-orourke commented on apps/web/src/validators/process/aboutUs.ts
Good catch! Yeah, one language filled and one empty should cause validation to fail.

2024-03-13 16:31 UTC, esizer commented on apps/web/src/validators/process/aboutUs.ts
Alright fixed in [fix about us validation](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9719/commits/bc6aacb047c0b55f7c0d2b0a29eb99d44fcb7e2d)

![Screenshot 2024-03-13 123040](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/b51fafe2-14e6-489c-b477-67759fe87930)

2024-03-13 19:01 UTC, petertgiles commented on apps/web/src/validators/process/aboutUs.ts
Looking better!  Could we expand this out?

Also applies to "what to expect:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/c44dc58b-b517-46b3-9670-1e60f8a60d10)

Also update the TOC:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/8b48ebcf-d05a-4db1-a46a-a70bd7fbff41)

Also update the chip:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/f4bfaa4d-35ba-44a8-91e1-3e0415789b96)

Also add to backend publish validation?

2024-03-14 18:48 UTC, esizer commented on apps/web/src/validators/process/aboutUs.ts
okay, I think I finally got it with [add additional validation for new fields](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9719/commits/0f7fbf7e9e3c4b69ca2d1c491aa2760ac3521bb6) 😅

2024-03-15 12:44 UTC, petertgiles commented on apps/web/src/validators/process/aboutUs.ts
If I clear the fields so that they go back to "optional", the overall chip still says incomplete.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/302d1fa3-96f6-4daa-9d76-a16c078d438e)

2024-03-15 12:46 UTC, petertgiles requested changes
Oops, noticed one more thing.

2024-03-15 12:46 UTC, petertgiles commented on apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
Oops, it looks like the word counter for EN is wired up to the FR side.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/bdec99d3-e325-4608-bba4-083dc892856e)
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/c546d6c8-f18b-483f-a975-7e9171a1eccc)

2024-03-15 19:06 UTC, esizer commented on apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
Oof! This was a larger bug that was impacting all of these editors! Fixed in [fix rich text word count](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9719/commits/cb5809daa16ecd44c8d96dfa74e28ad0edf6f57a)

2024-03-18 12:50 UTC, petertgiles commented on apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
Nice, great fix!

2024-03-18 12:51 UTC, petertgiles approved these changes

2024-03-18 13:10 UTC, merged