Update seeder values with data from prod
GCTC-NTGC/gc-digital-talent pull request #9941
Opened 2024-03-27 21:11 UTC by tristan-orourke

🤖 Resolves #9783 

## 👋 Introduction

Adds new skills and skillFamilies to seeder data

## 🕵️ Details

In the end, these new skills got added in Production manually, through the admin dashboard. This just allows us to keep the UAT and local databases in sync with that.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Run database seeders
2. Go to http://localhost:8000/en/skills
3. Look up the new skills in the mass import tab of [this sharepoint spreadsheet](https://056gc.sharepoint.com/:x:/r/sites/DigitalCommunityManagementOffice-Bureaudegestiondelacollectivdun/_layouts/15/Doc.aspx?sourcedoc=%7BDF7F500A-27CD-4511-8C38-2C5CEC88F095%7D&file=New%20Skills%20.xlsx&wdLOR=cBF34C57E-ABDE-4078-ADCF-14481206D093&action=default&mobileredirect=true) and check they appear correctly in the table.

## 🚚 Deployment

Run the skill and skill family seeders, only on UAT:
`php artisan db:seed --class=SkillFamilySeeder`
`php artisan db:seed --class=SkillSeeder`

2024-03-28 14:04 UTC, mnigh requested changes
This review is only for the data in the JSON files.

2024-03-28 14:04 UTC, mnigh commented on api/database/seeders/SkillSeeder.data.json
Found a few typos that are out of scope for the linked issue but might be convenient to fix at the same time.

1. PstgreSQL to PostgreSQL
https://github.com/GCTC-NTGC/gc-digital-talent/blob/dd7e4537ef6b3b2f62d69f152c2f3e0ec4dc52dd/api/database/seeders/SkillSeeder.data.json#L1876-L1877

2. copywrite to copyright
https://github.com/GCTC-NTGC/gc-digital-talent/blob/dd7e4537ef6b3b2f62d69f152c2f3e0ec4dc52dd/api/database/seeders/SkillSeeder.data.json#L3148

4. gagnate to gagnante
https://github.com/GCTC-NTGC/gc-digital-talent/blob/dd7e4537ef6b3b2f62d69f152c2f3e0ec4dc52dd/api/database/seeders/SkillSeeder.data.json#L5180

5. `executive_leadership_digtial_business_line_advisory` should be `executive_leadership_digital_business_line_advisory`
https://github.com/GCTC-NTGC/gc-digital-talent/blob/dd7e4537ef6b3b2f62d69f152c2f3e0ec4dc52dd/api/database/seeders/SkillSeeder.data.json#L2693

6. `executive_leadership_instrastructure_operations` to `executive_leadership_infrastructure_operations`
https://github.com/GCTC-NTGC/gc-digital-talent/blob/dd7e4537ef6b3b2f62d69f152c2f3e0ec4dc52dd/api/database/seeders/SkillSeeder.data.json#L2777

7. `policies_procedures_quidelines_development` to `policies_procedures_guidelines_development`
https://github.com/GCTC-NTGC/gc-digital-talent/blob/dd7e4537ef6b3b2f62d69f152c2f3e0ec4dc52dd/api/database/seeders/SkillSeeder.data.json#L5150

2024-04-02 13:38 UTC, petertgiles reviewed
The sort function provided will sort the main "skills" array but isn't smart enough to sort the properties or keyword arrays.  I like the Thinker.sort-json extension for this.

2024-04-02 13:38 UTC, petertgiles commented on api/database/seeders/SkillSeeder.data.json
It looks like this seeder is already out of date!  Do you want to continue with this or sync up again?
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/c06d1e2d-067a-4f2f-918b-357cb76b1a94)

2024-04-02 13:39 UTC, petertgiles commented on api/database/seeders/SkillSeeder.data.json
Skill families is in sync right now though.

2024-04-05 14:55 UTC, tristan-orourke commented on api/database/seeders/SkillSeeder.data.json
I don't want to change the keys, since the whole point is those stay constant. That allows the seeders to update entries instead of creating new ones. But I've made the other changes in the PR, and in production!

2024-04-05 14:56 UTC, tristan-orourke commented on api/database/seeders/SkillSeeder.data.json
Okay, updated with production details again.

2024-04-05 15:07 UTC, mnigh commented on api/database/seeders/SkillSeeder.data.new.json
@tristan-orourke why have a new file called `SkillSeeder.data.new.json` instead of replacing `SkillSeeder.data.json`

2024-04-05 15:14 UTC, tristan-orourke commented on api/database/seeders/SkillSeeder.data.new.json
fixed!

2024-04-05 15:44 UTC, mnigh requested changes

2024-04-05 15:44 UTC, mnigh commented on api/database/seeders/SkillSeeder.data.json
> +          "en": "Demonstrated ability to design, write and iterate code and scripts in lanugages such as Python, R, Julia, C++, Java along the model lifecycle from concept, to development, to prototy
```suggestion
          "en": "Demonstrated ability to design, write and iterate code and scripts in languages such as Python, R, Julia, C++, Java along the model lifecycle from concept, to development, to prototype, to production, through to deployment.",
```

2024-04-05 15:44 UTC, mnigh commented on api/database/seeders/SkillSeeder.data.json
> +            "GraphQL.",
Does this need a period?

2024-04-05 15:44 UTC, mnigh commented on api/database/seeders/SkillSeeder.data.json
> +            "GraphQL.",
Does this need a period?

2024-04-05 15:44 UTC, mnigh commented on api/database/seeders/SkillSeeder.data.json
i think **copywriting** is meant here based on the french translation as _pratiques de rédaction_, but **copyright** could also make sense in the sentence context but french would need to be changed. **copywrite** is not correct though: https://github.com/GCTC-NTGC/gc-digital-talent/pull/9941/files#diff-ede683bccd951cc8500c542e0538eda2f51a88a1023cc8d54f00f280a0aab224R3791

2024-04-05 17:12 UTC, tristan-orourke commented on api/database/seeders/SkillSeeder.data.json
> +            "GraphQL.",
Definitely not, lol

2024-04-05 17:35 UTC, tristan-orourke commented on api/database/seeders/SkillSeeder.data.json
Yeah, copywriting seems to make more sense.

2024-04-05 18:07 UTC, mnigh approved these changes
not sure if it is already out of date with production (likely 😆), but LGTM 👍

2024-04-05 18:10 UTC, merged