[Debt] Update skill browser
GCTC-NTGC/gc-digital-talent pull request #9958
Opened 2024-04-02 15:26 UTC by esizer

🤖 Resolves #9623 

## 👋 Introduction

Updates the skill browser with the following changes:

- Remove category field
- Update skill family label
- Remove skill counts from options
- Add a link to the not found skill suggestion

## 🧪 Testing

1. Build `pnpm run dev`
2. Navigate to a page with the skill browser
3. Confirm it matches [the mock up](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=97-31278&mode=design&t=q0CnoXe0a8womMfK-4)
4. Confirm it still functions as expected
5. Run storybook `pnpm run storybook:web`
6. Navigate to the skill browser stories
7. Confirm each story matches  [the mock up](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=97-31278&mode=design&t=q0CnoXe0a8womMfK-4)
4. Confirm it still functions as expected

## 📸 Screenshot

![screenshot_02-Apr-2024_11-23-1712071424](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/6a661d04-034f-414e-9c9b-dc7e65efe875)
![screenshot_02-Apr-2024_11-26-1712071576](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/45ae63b8-df86-4c19-a49c-e62ca3599546)

2024-04-05 19:29 UTC, yonikid15 requested changes
Looking great so far Eric! 

I found an edge case that if fixed would improve the UX. We should probably reset the skill selection form value (and the other form values too) when the use switches the family.



https://github.com/GCTC-NTGC/gc-digital-talent/assets/22059495/94bc300f-3298-43ff-a9a8-0840f3c8a575

2024-04-05 19:47 UTC, brindasasi commented
> Looking great so far Eric!
> 
> I found an edge case that if fixed would improve the UX. We should probably reset the skill selection form value (and the other form values too) when the use switches the family.
> 
>  Skill.library._.GC.Digital.Talent.Firefox.Developer.Edition.2024-04-05.15-08-59.mp4

 I was going to comment the samething 😅
The video doesn't run for me but the screenshot that I was going to post 
<img width="875" alt="Screenshot 2024-04-05 at 3 45 19 PM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/aae3c02b-d086-410e-9ce5-a9f4e95c3410">

2024-04-05 20:20 UTC, esizer commented
> I found an edge case that if fixed would improve the UX. We should probably reset the skill selection form value (and the other form values too) when the use switches the family.

This should do it @yonikid15 and @brindasasi 


[clear out combobox when field value is null](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9958/commits/e523a2dc445d06acafa7cf7ba6dab599098b60a0)

2024-04-08 17:28 UTC, yonikid15 approved these changes
LGTM 👍

2024-04-09 16:49 UTC, merged